const $=id=>document.getElementById(id),keys=[];let shown='',revoking=null;
function toast(message){$('toast').textContent=message;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',3000)}
function el(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('已复制')}catch{toast('浏览器未允许复制，请从文档页面手动复制')}}
function render(){const list=$('keys');list.replaceChildren();if(!keys.length){list.append(el('div','还没有 API Key。创建一个，让你的 Agent 开始创作。','empty-keys'));return}for(const k of keys){const row=el('div','','key-row');const info=el('div','');info.append(el('div',k.name,'key-name'),el('code',k.prefix+'…'),el('div','完整创作权限 · 最近使用：从未使用（模拟）','key-meta'));const state=el('div','');state.append(el('div',k.revoked?'已撤销':'有效（模拟）',k.revoked?'status-revoked':'status-active'),el('div',`创建 ${k.created} · ${k.days}天有效期`,'key-meta'));row.append(info,state);if(!k.revoked){const revoke=el('button','撤销');revoke.onclick=()=>{revoking=k;$('revoke-text').textContent=`${k.name} 撤销后，使用它的 Agent 将无法继续访问。`;$('revoke-dialog').showModal()};row.append(revoke)}list.append(row)}}
$('create').onclick=()=>{$('key-name').value='';$('create-dialog').showModal();$('key-name').focus()};$('cancel-create').onclick=()=>$('create-dialog').close();
$('confirm-create').onclick=()=>{const name=$('key-name').value.trim();if(!name){$('key-name').focus();toast('给这个 Key 起一个名字');return}shown='DEMO_NOT_VALID_'+crypto.randomUUID().replaceAll('-','');keys.push({name,prefix:shown.slice(0,22),days:$('expiry').value,created:new Intl.DateTimeFormat('zh-CN',{timeZone:'Australia/Sydney'}).format(new Date()),revoked:false});$('once').textContent=shown;$('create-dialog').close();render();$('created-dialog').showModal()};
$('copy-key').onclick=()=>copy(shown);$('done-created').onclick=()=>$('created-dialog').close();$('created-dialog').addEventListener('close',()=>{shown='';$('once').textContent=''});
$('cancel-revoke').onclick=()=>$('revoke-dialog').close();$('confirm-revoke').onclick=()=>{if(revoking)revoking.revoked=true;revoking=null;$('revoke-dialog').close();render();toast('演示 Key 已撤销')};
$('copy-instructions').onclick=()=>copy(`请阅读映序 Agent 接入文档：${new URL('agent-docs.html',location.href).href}\n当前是本地界面 Mock，请只了解流程，不发起真实调用、上传或生成。正式接入时使用我在本地安全配置的网站 API Key；不要在聊天或日志输出密钥。创作目标：[在这里写你的需求]。文档地址不含密钥。`);render();
