const $=id=>document.getElementById(id), sessions=[];
let current,editing=null,pendingSwitch=null,clipTarget=null;const timers=new Set();
const defaults=()=>({duration:'5 秒',resolution:'768P',ratio:'16:9 横屏',count:'1',sound:true,workflow:'自动匹配素材',seed:'',steps:'50',sampler:'res_multistep',scheduler:'auto',denoise:'1',refsize:'max',shiftvideo:'',shiftaudio:'',decode:'tiled',encoder:'cpu',crf:'18',tilesize:'512',overlap:'64',temporal:'64',temporaloverlap:'8'});
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function button(text,action,cls=''){const b=el('button',cls,text);b.onclick=action;return b}
function toast(text){$('toast').textContent=text;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',2600)}
function fresh(){current={id:crypto.randomUUID(),title:'新的创作',turns:[],assets:[],draft:'',model:'Gemini 3.8 Flash',settings:defaults()};sessions.unshift(current);render()}
function change(s){current.draft=$('prompt').value;current=s;render()}
function renderHistory(){const nav=$('history');nav.replaceChildren();sessions.forEach(s=>nav.append(button(s.title,()=>change(s),s===current?'active':'')))}
function media(a){if(a.type==='image'){const n=el('img');n.src=a.url;n.alt=a.name;return n}return el('span','fileicon',a.type==='audio'?'♫':'▻')}
function effectiveMode(settings,assets){if(settings.workflow!=='自动匹配素材')return settings.workflow;return assets.some(a=>['首帧','尾帧'].includes(a.role))?'首尾帧':'全能参考'}
function included(a,mode){return mode==='首尾帧'?a.type==='image'&&['首帧','尾帧'].includes(a.role):!['首帧','尾帧'].includes(a.role)}
function activeAssets(assets,settings){const mode=effectiveMode(settings,assets);return assets.filter(a=>included(a,mode))}
function requestSwitch(mode,action,assets=current.assets){const problem=inputProblems(assets.filter(a=>included(a,mode)),mode,{countsOnly:true});if(problem.length){toast(problem.join(' '));return}const excluded=assets.filter(a=>!included(a,mode));if(!excluded.length){action();return}pendingSwitch=action;$('switch-description').textContent=`切换为${mode}后，${excluded.length}份不兼容素材会留在输入框，但本轮不使用。素材和历史记录不会删除。`;$('switch-mode').showModal()}
function roleChange(a,role){const mode=['首帧','尾帧'].includes(role)?'首尾帧':'全能参考';if(['首帧','尾帧'].includes(role)&&current.assets.some(x=>x.id!==a.id&&x.role===role)){toast(`只能指定一张${role}，请先调整原图片用途`);renderAssets();return}const proposed=current.assets.map(x=>x.id===a.id?{...x,role}:x);const problems=inputProblems(proposed.filter(x=>included(x,mode)),mode,{countsOnly:true});if(problems.length){toast(problems.join(' '));renderAssets();return}const apply=()=>{a.role=role;current.settings.workflow=mode;renderAssets()};if(mode!==effectiveMode(current.settings,current.assets)){requestSwitch(mode,apply,current.assets.map(x=>x.id===a.id?{...x,role}:x));renderAssets()}else apply()}
function renderAssets(){const area=$('assets');area.replaceChildren();const mode=effectiveMode(current.settings,current.assets);current.assets.forEach(a=>{const active=included(a,mode);const card=el('div','asset'+(active?'':' inactive'));card.append(media(a));const info=el('div');info.append(el('div','asset-name',a.name));const select=el('select');select.setAttribute('aria-label',a.name+'的用途');const roles=a.type==='image'?['参考图片','首帧','尾帧']:a.type==='audio'?['声音参考']:['视频 / 动作参考'];roles.forEach(r=>{const o=el('option','',r);o.value=r;o.disabled=['首帧','尾帧'].includes(r)&&current.assets.some(x=>x.id!==a.id&&x.role===r);select.append(o)});select.value=a.role;select.onchange=()=>roleChange(a,select.value);info.append(select);if(a.type!=='image'){info.append(button(`片段 ${Number(a.clipEnd-a.clipStart).toFixed(2)}秒`,()=>openClip(a)));}if(!active)info.append(el('small','','保留 · 本轮不使用'));card.append(info,button('×',()=>{current.assets=current.assets.filter(x=>x.id!==a.id);renderAssets()}));card.lastChild.setAttribute('aria-label','从本轮移除 '+a.name);area.append(card)});$('inherit').textContent=current.turns.length?'素材和设置沿用上一轮 · × 只移除本轮引用，不删除历史素材':'';const note=$('mode-note');note.replaceChildren();note.append(el('span','',mode==='首尾帧'?'首尾帧模式 · 普通参考不参与本轮；独立时间锚点另设入口。':'全能参考模式 · 使用参考图片、视频、音频，首帧/尾帧不参与本轮。'));if(current.assets.some(a=>!included(a,mode)))note.append(button(mode==='首尾帧'?'切换全能参考':'切换首尾帧',()=>{const next=mode==='首尾帧'?'全能参考':'首尾帧';requestSwitch(next,()=>{current.settings.workflow=next;renderAssets()})}));note.hidden=!current.assets.length&&current.settings.workflow==='自动匹配素材';$('settings-summary').textContent=`${current.settings.duration} · ${current.settings.resolution} · ${current.settings.count}份`;renderLimits()}

function renderLimits(){const mode=effectiveMode(current.settings,current.assets),active=activeAssets(current.assets,current.settings),counts=referenceCounts(active);$('limits-summary').textContent=mode==='首尾帧'?`首帧 ${active.filter(a=>a.role==='首帧').length}/1 · 尾帧 ${active.filter(a=>a.role==='尾帧').length}/1 · 可不放素材`:`图片 ${counts.image}/9 · 视频 ${counts.video}/3 · 音频 ${counts.audio}/3 · 合计 ${active.length}/12 ｜视频、音频单段2–15秒，各类累计≤15秒`;
 const errors=inputProblems(active,mode);$('input-errors').textContent=errors.join(' ');$('send').disabled=errors.length>0||!!current.loading;const full=mode==='首尾帧'?active.length>=2:active.length>=12||counts.image>=9&&counts.video>=3&&counts.audio>=3;$('upload').disabled=full||!!current.loading;$('upload').textContent=current.loading?'正在读取本地素材…':full?'本轮素材名额已满':'＋ 添加图片、视频或音频';$('files').accept=mode==='首尾帧'?'image/*':['image','video','audio'].filter(t=>counts[t]<H3Limits[t]).map(t=>t+'/*').join(',')}
function addAsset(a,s=current){const mode=effectiveMode(s.settings,s.assets);if(s.assets.some(x=>x.id===a.id))return '这份素材已在输入框里';if(!included(a,mode))return '素材用途与当前模式不兼容，请先切换生成方式';const errors=inputProblems([...activeAssets(s.assets,s.settings),a],mode,{countsOnly:true});if(errors.length)return errors.join(' ');s.assets.push({...a});return ''}
function readDuration(url,type){return new Promise((resolve,reject)=>{const node=document.createElement(type);node.preload='metadata';const timer=setTimeout(()=>done(false),10000);function done(ok){clearTimeout(timer);const d=node.duration;node.removeAttribute('src');node.load();ok&&Number.isFinite(d)&&d>0?resolve(d):reject(Error('无法读取媒体时长，请换一个浏览器支持的文件'))}node.onloadedmetadata=()=>done(true);node.onerror=()=>done(false);node.src=url})}
async function files(list){const s=current;if(s.loading)return;s.loading=true;renderLimits();const errors=[];for(const f of list){const type=f.type.split('/')[0];if(!['image','video','audio'].includes(type)){errors.push(f.name+'：请选择图片、视频或音频');continue}const mode=effectiveMode(s.settings,s.assets);if(mode==='首尾帧'&&type!=='image'){errors.push(f.name+'：首尾帧模式不接受视频或音频参考，请先切换全能参考');continue}const a={id:crypto.randomUUID(),name:f.name,type,url:URL.createObjectURL(f),role:type==='image'?(mode==='首尾帧'?(!s.assets.some(x=>x.role==='首帧')?'首帧':'尾帧'):'参考图片'):type==='audio'?'声音参考':'视频 / 动作参考'};try{if(type!=='image'){a.duration=await readDuration(a.url,type);if(a.duration<2||a.duration>3600)throw Error('源文件需在2秒至1小时内；长素材请先在本地裁短');a.clipStart=0;a.clipEnd=a.duration}const problem=addAsset(a,s);if(problem)throw Error(problem)}catch(e){URL.revokeObjectURL(a.url);errors.push(f.name+'：'+e.message)}}s.loading=false;if(current===s){renderAssets();$('upload-errors').textContent=errors.join('；')}}
function openClip(a){clipTarget=a;$('clip-source').textContent=`${a.name} · 原片 ${a.duration.toFixed(2)}秒`;$('clip-start').value=a.clipStart;$('clip-end').value=a.clipEnd;$('clip-error').textContent='';const media=document.createElement(a.type);media.src=a.url;media.controls=true;media.style.width='100%';media.style.maxHeight='180px';$('clip-preview').replaceChildren(media);$('clip-editor').showModal()}

function chipAsset(a,s){const b=button(a.role+' · '+a.name,()=>{if(!current.assets.some(x=>x.id===a.id)){const error=addAsset(a);renderAssets();toast(error||'已加入本轮素材')}else toast('这份素材已经在本轮输入里')},'chip');b.draggable=true;b.ondragstart=e=>e.dataTransfer.setData('application/x-yingxu-asset',JSON.stringify({session:s.id,asset:a.id}));b.title='点击或拖到输入框，重新使用';return b}
function openEdit(t=null){editing=t||{composer:true,settings:{...current.settings},prompt:$('prompt').value,state:'draft'};const s=editing.settings;$('editor-title').textContent=t?'把这个镜头调到位':'下一轮 · 高级控制';$('editor-scope').textContent=t?'只修改这张草稿卡；已有任务不受影响':'用于下一张任务卡，不修改历史卡片';$('edit-prompt').parentElement.hidden=!editing.composer?false:true;$('edit-prompt').value=editing.prompt;for(const key of Object.keys(defaults())){if(key==='sound')$(key).checked=s[key];else $(key).value=s[key]}$('workflow-help').textContent='首尾帧与全能参考互斥。切换后不兼容的素材会保留，但不会加入任务。';$('editor').querySelectorAll('details').forEach(d=>d.open=false);$('editor').showModal()}
function makeResults(t){const out=el('div','results');t.results.forEach((r,i)=>{const block=el('div','result');const p=el('div','placeholder',r.failed?'模拟失败\n可以单独重试':`▷  第 ${i+1} 份\n视频占位 · 没有真实生成`);block.append(p);const bar=el('div','result-bar',`种子 ${r.seed} · ${t.settings.duration}`);if(r.failed){bar.append(button('重试这一份（模拟）',()=>{r.failed=false;renderThread();toast('已模拟重试成功，其他结果不变')}))}else{bar.append(button('以此继续修改',()=>{current.assets=t.assets.map(a=>({...a}));current.settings={...t.settings};$('prompt').value='基于这一版，';current.draft=$('prompt').value;$('prompt').focus();renderAssets();toast('已沿用该轮输入；没有自动把输出视频加入参考')}),button('用作视频参考',()=>toast('这里是视频占位，正式版会把真实输出加入参考素材')))}block.append(bar);out.append(block)});return out}
function task(t,s){const c=el('div','task');const top=el('div','task-top');top.append(el('h3','',t.title),el('span','badge',t.state==='draft'?'待确认':t.state==='done'?'模拟完成':'模拟生成中'));c.append(top);const body=el('div','task-body');body.append(el('p','task-prompt',t.prompt));const chips=el('div','chips');[t.settings.workflow,t.settings.duration,t.settings.resolution,t.settings.ratio,t.settings.sound?'有声音':'无声音'].forEach(x=>chips.append(el('span','chip',x)));body.append(chips);const assets=el('div','chips');t.assets.forEach(a=>assets.append(chipAsset(a,s)));body.append(assets);if(t.state==='running'){body.append(el('p','muted',t.phase));const progress=el('div','progress');const fill=el('span');fill.style.width=t.progress+'%';progress.append(fill);body.append(progress)}if(t.state==='done')body.append(makeResults(t));c.append(body);const foot=el('div','task-footer');if(t.state==='draft'){foot.append(button('编辑提示词与参数',()=>openEdit(t)));const label=el('label','','抽卡 ');const count=el('select');count.setAttribute('aria-label','生成份数');[1,2,3,4].forEach(n=>{const o=el('option','',n+' 份');o.value=n;count.append(o)});count.value=t.settings.count;count.onchange=()=>{t.settings.count=count.value;current.settings={...t.settings}};label.append(count);const go=button('开始生成',()=>start(t,s),'primary');const issues=inputProblems(t.assets,effectiveMode(t.settings,t.assets),{requireReference:true});go.disabled=issues.length>0;foot.append(label,go);if(issues.length)foot.append(el('span','input-warning',issues.join(' ')));foot.append(el('span','cost','模拟费用 ¥0 · 正式版提交前显示整批预估'))}else if(t.state==='running'){foot.append(button('取消剩余任务',()=>{t.state='cancelled';renderThread()}),el('span','cost','模拟运行，不占用 GPU'))}else{foot.append(button('复制为新任务卡',()=>{const next={...t,id:crypto.randomUUID(),settings:{...t.settings},assets:t.assets.map(a=>({...a})),results:[],state:'draft',title:'新版本 · '+t.title};s.turns.push({text:'沿用这一轮，再做一个版本',model:current.model,task:next});renderThread();scrollBottom()}));if(t.state==='done'&&t.results.length>1)foot.append(button('体验部分失败',()=>{t.results[t.results.length-1].failed=true;renderThread()}));if(t.state==='cancelled')foot.append(el('span','cost','已模拟取消'))}c.append(foot);return c}
function renderThread(){const area=$('thread');area.replaceChildren();$('welcome').hidden=current.turns.length>0;current.turns.forEach((turn,i)=>{const node=el('article','turn');node.append(el('div','user-message',turn.text),el('div','turn-label',`✧ ${turn.model} · 第 ${i+1} 轮 · 模拟回复`));node.append(el('div','assistant-text',turn.reply||'已整理成一张草稿卡。你可以调整后开始生成。'));if(turn.task)node.append(task(turn.task,current));area.append(node)});$('title').textContent=current.title;renderHistory()}
function render(){renderThread();renderAssets();$('prompt').value=current.draft;$('model').value=current.model}
function scrollBottom(){requestAnimationFrame(()=>window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'}))}
function start(t,s){if(t.state!=='draft')return;const issues=inputProblems(t.assets,effectiveMode(t.settings,t.assets),{requireReference:true});if(issues.length){toast(issues.join(' '));return}const mode=effectiveMode(t.settings,t.assets);if(mode==='全能参考'&&!activeAssets(t.assets,t.settings).length){toast('全能参考需要至少一份参考素材；纯文字创作可选首尾帧模式');return}if(t.assets.some(a=>!included(a,mode))){toast('素材与生成方式冲突，请先编辑参数');return}t.state='running';t.phase='模拟排队…';t.progress=10;s.settings={...t.settings};renderThread();[ ['模拟准备算力…',35],['模拟生成视频…',68],['模拟收集结果…',90],['完成',100]].forEach(([phase,progress],i)=>{const timer=setTimeout(()=>{timers.delete(timer);if(t.state!=='running')return;t.phase=phase;t.progress=progress;if(progress===100){t.state='done';t.results=Array.from({length:Number(t.settings.count)},(_,n)=>({seed:((BigInt(t.settings.seed||'728140')+BigInt(n))%18446744073709551616n).toString(),failed:false}))}if(current===s)renderThread()},(i+1)*900);timers.add(timer)})}
function send(){if(current.loading)return;const issues=inputProblems(activeAssets(current.assets,current.settings),effectiveMode(current.settings,current.assets));if(issues.length){toast(issues.join(' '));return}const text=$('prompt').value.trim();if(!text){toast('先写一点你想拍的画面');return}const previous=[...current.turns].reverse().find(x=>x.task)?.task;let full=text;if(previous)full=previous.prompt+'\n本轮修改：'+text;const isQuestion=/[?？]$/.test(text)&&!/(生成|拍一个|做一个)/.test(text);const t={id:crypto.randomUUID(),title:previous?'镜头 · 新版本':'我的第一个镜头',prompt:full,settings:{...current.settings,workflow:current.assets.length?effectiveMode(current.settings,current.assets):(current.settings.workflow==='自动匹配素材'?'首尾帧':current.settings.workflow)},assets:activeAssets(current.assets,current.settings).map(a=>({...a})),state:'draft',results:[]};current.turns.push({text,model:current.model,task:isQuestion?null:t,reply:isQuestion?'这是讨论回复的占位：正式助手会结合上下文回答问题，不因普通聊天提交视频。你可以继续描述想拍的画面。':previous?'沿用上一轮的素材与设置，把这次修改放进新卡片。这里只演示交互，尚未用模型理解或改写提示词。':undefined});if(current.title==='新的创作')current.title=text.slice(0,18);current.draft='';$('prompt').value='';renderThread();renderAssets();scrollBottom()}
$('new').onclick=fresh;$('upload').onclick=()=>$('files').click();$('files').onchange=e=>{files(e.target.files);e.target.value=''};$('send').onclick=send;$('prompt').oninput=()=>current.draft=$('prompt').value;$('prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send()}};$('model').onchange=e=>current.model=e.target.value;
$('controls').onclick=()=>openEdit();
$('switch-cancel').onclick=()=>{pendingSwitch=null;$('switch-mode').close()};
$('switch-confirm').onclick=()=>{const action=pendingSwitch;pendingSwitch=null;$('switch-mode').close();action?.()};
$('save').onclick=()=>{if(!editing||editing.state!=='draft')return;const isComposer=editing.composer;const prompt=$('edit-prompt').value.trim();if(!isComposer&&!prompt){toast('提示词不能为空');return}const settings={};for(const key of Object.keys(defaults()))settings[key]=key==='sound'?$(key).checked:$(key).value;for(const node of $('editor').querySelectorAll('input[type=number]')){if(!node.checkValidity()){node.reportValidity();return}}if(settings.seed&&(!/^[0-9]{1,20}$/.test(settings.seed)||BigInt(settings.seed)>18446744073709551615n)){toast('种子须为0–18446744073709551615的整数');return}if(Number(settings.overlap)>=Number(settings.tilesize)||Number(settings.temporaloverlap)>=Number(settings.temporal)){toast('解码重叠必须小于对应块大小');return}const assets=isComposer?current.assets:editing.assets;const mode=effectiveMode(settings,assets);const excluded=assets.filter(a=>!included(a,mode));const problems=inputProblems(assets.filter(a=>included(a,mode)),mode,{countsOnly:true});if(problems.length){toast(problems.join(' '));return}const commit=()=>{if(isComposer){current.settings=settings}else{editing.prompt=prompt;editing.settings=settings;editing.assets=activeAssets(assets,settings).map(a=>({...a}))} $('editor').close();renderThread();renderAssets();toast(isComposer?'下一轮设置已保存':'草稿卡已更新')};if(excluded.length&&(!isComposer||mode!==effectiveMode(current.settings,current.assets))){pendingSwitch=commit;$('switch-description').textContent=isComposer?`切换为${mode}后，${excluded.length}份素材保留在输入框，本轮不使用。`:`这张卡切换为${mode}后，将移除${excluded.length}份不兼容的引用；输入框和历史原素材不删除。`;$('switch-mode').showModal()}else commit()};

const drop=$('drop');drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragging')};drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragging');const data=e.dataTransfer.getData('application/x-yingxu-asset');if(data){try{const ref=JSON.parse(data);if(ref.session!==current.id){toast('不同对话的素材保持独立');return}const a=current.turns.flatMap(x=>x.task?.assets||[]).find(x=>x.id===ref.asset);if(a){const error=addAsset(a);if(error)toast(error)}renderAssets()}catch{toast('无法使用这份素材')}}else files(e.dataTransfer.files)};
$('clip-cancel').onclick=()=>{$('clip-editor').close();$('clip-preview').replaceChildren()};
$('clip-save').onclick=()=>{if(!clipTarget)return;const updated={...clipTarget,clipStart:Number($('clip-start').value),clipEnd:Number($('clip-end').value)};const problem=inputProblems([updated],'全能参考');if(problem.length){$('clip-error').textContent=problem.join(' ');return}Object.assign(clipTarget,updated);$('clip-editor').close();$('clip-preview').replaceChildren();renderAssets()};
fresh();
