import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Copy,KeyRound,RefreshCw,ShieldCheck,X} from 'lucide-react';
import {createCloudClient} from './cloud-client.js';
import './api-keys.css';

const profiles={
  create:{label:'创作与生成',scopes:['projects:read','projects:create','projects:write','assets:read','assets:write','jobs:read','jobs:write']},
  edit:{label:'创作与上传，不提交生成',scopes:['projects:read','projects:create','projects:write','assets:read','assets:write','jobs:read']},
  read:{label:'仅查看与下载',scopes:['projects:read','assets:read','jobs:read']},
};
const date=value=>value?new Date(typeof value==='number'?value*1000:value).toLocaleString():'尚未使用';

export default function ApiKeys({account,projects=[],moreProjects=false,initialGrant=null}){
  const client=useMemo(()=>{const api=createCloudClient();api.setAccount(account);return api;},[account]);
  const live=useRef(false),[keys,setKeys]=useState([]),[name,setName]=useState(''),[profile,setProfile]=useState(Object.hasOwn(profiles,initialGrant?.profile)?initialGrant.profile:'edit'),[allProjects,setAllProjects]=useState(initialGrant?.allProjects??true),[selected,setSelected]=useState(initialGrant?.projectIds||[]),[days,setDays]=useState(initialGrant?.expiresInDays||7),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[created,setCreated]=useState(null),[reveal,setReveal]=useState(false),[confirmRevoke,setConfirmRevoke]=useState(null);
  async function refresh(){const data=await client.apiKeys();if(live.current)setKeys(data.api_keys||[]);}
  useEffect(()=>{live.current=true;setCreated(null);setKeys([]);setError('');setBusy(true);refresh().catch(()=>{if(live.current)setError('API Key 列表暂时无法读取，请刷新重试。');}).finally(()=>{if(live.current)setBusy(false);});return()=>{live.current=false;client.reset();};},[client]);
  async function act(fn){setBusy(true);setError('');setNotice('');try{await fn();}catch{if(live.current)setError('操作未完成。请刷新列表核对；创建响应丢失时请撤销对应 Key 后重新创建，不会自动重试。');}finally{if(live.current)setBusy(false);}}
  async function create(e){e.preventDefault();await act(async()=>{const scopes=profiles[profile].scopes.filter(scope=>allProjects||scope!=='projects:create');const result=await client.createApiKey({name:name.trim(),scopes,all_projects:allProjects,project_ids:allProjects?[]:selected,expires_in_days:Number(days)});if(!live.current)return;if(typeof result.api_key!=='string'||!result.api_key)throw Error('Missing key');setCreated({id:result.key.id,secret:result.api_key});setReveal(false);setName('');setNotice('Key 已创建。完整值只在本次创建后提供；关闭后无法再次查看。');try{await refresh();}catch{if(live.current)setError('Key 已成功创建，但列表刷新失败。请先保存上方 Key，再刷新列表。');}});}
  async function copy(){try{await navigator.clipboard.writeText(created.secret);setNotice('已复制。请保存到 Agent 的安全凭据配置中，不要贴进项目文档。');}catch{setReveal(true);setNotice('浏览器未允许复制，请手动复制后收起。');}}
  async function revoke(id){await act(async()=>{await client.revokeApiKey(id);if(!live.current)return;setConfirmRevoke(null);if(created?.id===id){setCreated(null);setReveal(false);}setNotice('Key 已撤销，后续调用会被拒绝；已提交的任务仍可在作品中管理。');try{await refresh();}catch{if(live.current)setError('Key 已撤销，但列表刷新失败，请刷新列表。');}});}
  return <section className="api-key-panel" aria-label="Agent API Key"><div className="cloud-section-head"><h3><KeyRound size={17}/> Agent API Key</h3><button type="button" disabled={busy} onClick={()=>act(refresh)}><RefreshCw size={14}/>刷新</button></div><p>让 Agent 直接创建故事、编辑章节、上传素材并提交任务。结果属于 <b>{account}</b>，可在「我的故事」查看。Key 不能访问其他账户，也不能管理其他 Key。</p>
    {created&&<section className="api-key-created" aria-label="新创建的 API Key"><div><b>请保存这一次显示的 Key</b><button type="button" aria-label="关闭新 Key" onClick={()=>{setCreated(null);setReveal(false);}}><X size={16}/></button></div><input aria-label="新 API Key（仅本次可见）" autoComplete="off" type={reveal?'text':'password'} value={created.secret} readOnly spellCheck={false}/><div><button type="button" onClick={()=>setReveal(!reveal)}>{reveal?'隐藏':'显示 Key'}</button><button type="button" onClick={copy}><Copy size={14}/>复制 Key</button></div><small>完整值只在当前页面内存中保留，不保存到浏览器存储。服务器只保存校验摘要。</small></section>}
    <p><a href="/v1/agent-skill.zip" download>下载 Agent Skill</a> · <a href="/v1/agent-guide" target="_blank" rel="noreferrer">查看 API 使用说明</a></p><form onSubmit={create} className="api-key-form"><label>Key 名称<input required maxLength={80} placeholder="例如：我的编剧 Agent" value={name} disabled={busy} onChange={e=>setName(e.target.value)}/></label><div className="api-key-options"><label>允许的操作<select value={profile} disabled={busy} onChange={e=>setProfile(e.target.value)}>{Object.entries(profiles).map(([id,p])=><option key={id} value={id}>{p.label}</option>)}</select></label><label>有效期<select value={days} disabled={busy} onChange={e=>setDays(Number(e.target.value))}>{[7,30,90,365].map(n=><option key={n} value={n}>{n} 天</option>)}</select></label></div><label>可访问的故事<select value={allProjects?'all':'selected'} disabled={busy} onChange={e=>setAllProjects(e.target.value==='all')}><option value="all">我的全部云故事，包括以后创建的故事</option><option value="selected">仅选定的云故事</option></select></label>{!allProjects&&<fieldset><legend>选择故事</legend>{projects.map(p=><label key={p.id} className="api-key-project"><input type="checkbox" checked={selected.includes(p.id)} disabled={busy} onChange={e=>setSelected(e.target.checked?[...selected,p.id]:selected.filter(id=>id!==p.id))}/>{p.title}</label>)}{!projects.length&&<p>请先创建一个云故事。</p>}{moreProjects&&<small>这里只显示已载入的故事；可先在故事列表加载更多。</small>}<small>指定故事的 Key 不能创建其他新故事。</small></fieldset>}<button className="primary" disabled={busy||!name.trim()||(!allProjects&&!selected.length)}><KeyRound size={14}/>创建 API Key</button></form>
    {error&&<p role="alert" className="cloud-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <div className="api-key-list">{keys.map(k=><article key={k.id}><div><b>{k.name}</b><code>{k.prefix}…</code><small>{k.all_projects?'全部自己的故事':`${k.project_ids?.length||0} 个指定故事`} · {k.revoked_at?'已撤销':Number(k.expires_at)*1000<Date.now()?'已过期':'有效'}</small><small>到期：{date(k.expires_at)} · 最近使用：{date(k.last_used_at)}</small><details><summary>查看权限</summary><p>{k.scopes?.join('、')}</p></details></div>{!k.revoked_at&&(confirmRevoke===k.id?<div className="api-key-revoke"><p>撤销后，这个 Agent 将无法继续调用。</p><button type="button" disabled={busy} onClick={()=>revoke(k.id)}>确认撤销</button><button type="button" disabled={busy} onClick={()=>setConfirmRevoke(null)}>保留</button></div>:<button type="button" disabled={busy} onClick={()=>setConfirmRevoke(k.id)}>撤销</button>)}</article>)}{!busy&&!keys.length&&<p className="muted">还没有 API Key。可以为不同 Agent 分别创建，便于单独撤销。</p>}</div><p className="api-key-hint"><ShieldCheck size={15}/>生成仍受账户预算、执行能力和队列限制。Key 不会自动开启 GPU。</p>
  </section>;
}
