import GeneratedSoundAction from './GeneratedSoundAction.jsx';
import {reviewProgress,shotReviewState,reviewLabels} from './production-model.js';
import React,{useState} from 'react';
import {store} from './store.js';
import {getFile,download} from './media.js';
import AssetPreview from './AssetPreview.jsx';
import {storyboardUrl} from './storyboard.js';
import './v6-journey.css';
const issues=['人物或造型','动作与表演','构图与机位','跨镜连续性','节奏','其他'];
export default function CandidateReview({project:p,shots,currentShot:shot,onChooseShot,onInspect,onReferences}){
 const [addId,setAddId]=useState('');
 if(!shot)return <div className="journey-empty"><h3>先有镜头，再决定候选</h3><button onClick={onReferences}>设计第一个镜头</button></div>;
 const cloudMode=store.getState().workspace.mode==='cloud';
 const progress=reviewProgress(p,shots,shot.id,{cloud:cloudMode}),at=shots.findIndex(s=>s.id===shot.id);
 const review=shot.data.uxReview||{},asset=p.entities.find(e=>e.id===shot.data.selectedAssetId),chosen=asset?null:review.chosen;
 const candidates=[...new Set([...(shot.data.candidateIds||[]),shot.data.selectedAssetId].filter(Boolean))].map(id=>p.entities.find(e=>e.id===id)).filter(Boolean);
 const update=patch=>store.updateEntity(shot.id,{data:{uxReview:{...store.getState().project.entities.find(e=>e.id===shot.id).data.uxReview,...patch}}},{coalesceKey:patch.note!==undefined?'review:'+shot.id+':note':null});
 const choose=(kind,id)=>store.updateEntity(shot.id,{status:'draft',data:{acceptPlaceholder:false,selectedAssetId:kind==='asset'?id:'',uxReview:{...review,chosen:kind==='demo'?id:null,status:'selected',allRejected:false}}});
 const names={placeholder:'本版接受文字占位',selected:'已有选择',revision:'待返修',failed:'演示：失败',retry:'演示：等待重试',processing:'演示：处理中',cancelled:'演示：已取消'};
 return <div className="candidate-review">
 <nav className="review-navigator" aria-label="逐镜审片进度"><p role="status">本章已确认 {progress.done} / {progress.total} 镜 · 还有 {progress.remaining} 镜待选择、复核或返修</p><div className="cloud-actions"><button disabled={at<=0} onClick={()=>onChooseShot(shots[at-1].id)}>上一镜</button><button disabled={at>=shots.length-1} onClick={()=>onChooseShot(shots[at+1].id)}>下一镜</button><button disabled={!progress.next} onClick={()=>onChooseShot(progress.next)}>跳到下一未审镜头</button></div>{!progress.next&&progress.remaining>0&&<p>{progress.total===1?'本章只有当前镜头，请完成这一个选择。':'其他镜头已确认，请处理当前镜头。'}跳转不会自动采用候选。</p>}{!progress.remaining&&<p>本章逐镜选择已完成，可到节奏与声音检查整章衔接。这里不代表客观画质评分。</p>}</nav>
 <label className="journey-field"><span>当前审核镜头</span><select aria-label="当前审核镜头" value={shot.id} onChange={e=>onChooseShot(e.target.value)}>{shots.map(s=><option key={s.id} value={s.id}>{s.title} · {reviewLabels[shotReviewState(p,s,{cloud:cloudMode})]}</option>)}</select></label>
 <p className="journey-review-brief">{(cloudMode?shot.data.prompt:shot.description)||shot.description||'先补充画面描述，才能判断候选是否符合想法。'}</p>
 <div className="journey-soft-panel"><strong>{asset?`当前候选：已有素材「${asset.title}」`:chosen?`当前候选：示例 ${chosen}`:'尚未选定候选'}</strong><p>每个镜头保留自己的版本与返修意见。选择另一个版本不会删除原文件。</p><button onClick={()=>onInspect(shot.id)}>选择已有素材</button></div>
 {asset?.type==='video'&&<GeneratedSoundAction key={shot.id+':'+asset.id} project={p} shot={shot}/>}
 <div className="v6-inline-form"><label>加入候选列表<select aria-label="加入候选列表" value={addId} onChange={e=>setAddId(e.target.value)}><option value="">选择已有图片或视频</option>{p.entities.filter(e=>['image','video'].includes(e.type)&&e.data.fileId&&!candidates.some(c=>c.id===e.id)).map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><button disabled={!addId} onClick={()=>{store.updateEntity(shot.id,{data:{candidateIds:[...new Set([...candidates.map(c=>c.id),addId])]}});setAddId('')}}>加入此镜头候选</button></div>
 {!!candidates.length&&<div className="journey-candidates">{candidates.map(c=><article className={'journey-candidate '+(asset?.id===c.id?'chosen':'')} key={c.id}><div className="v6-asset"><AssetPreview entity={c}/></div><div><h3>{c.title}</h3>{c.data.simulation&&<p className="cloud-warning">模拟任务产物，不能作为 H3 质量样片。</p>}{(c.data.oldVersion||(c.data.sourceShotVersion&&c.data.sourceShotVersion!==shot.version))&&<p className="cloud-warning">来自旧镜头版本，需重新核对后采用。</p>}<button disabled={c.data.missingFile||!c.data.fileId} aria-pressed={asset?.id===c.id} onClick={()=>choose('asset',c.id)}>使用候选 {c.title}</button><button className="journey-minor-button" disabled={!c.data.fileId||c.data.missingFile} onClick={async()=>{try{const file=await getFile(c.data.fileId);if(!file)throw Error('文件不可读');download(file,c.data.fileName||c.title);}catch(error){store.notify('下载失败：'+error.message);}}}>下载此候选</button><button className="journey-minor-button" disabled={asset?.id===c.id} onClick={()=>store.updateEntity(shot.id,{data:{candidateIds:candidates.filter(a=>a.id!==c.id).map(a=>a.id)}})}>移出比较列表</button></div></article>)}</div>}
 {!cloudMode&&<details className="v6-demo-candidates" open={!candidates.length}><summary>用同一场戏的 A/B 分镜示意体验审核</summary><p className="journey-demo-note">交互演示，非本次生成。两张图画的是同一个场景的不同构图，只用于分镜取舍；不证明模型效果。自己的故事可加入已有图片或视频。</p><div className="journey-candidates">{['A','B'].map(c=><article key={c} className={'journey-candidate '+(chosen===c?'chosen':'')}><div className="journey-candidate-image"><img src={storyboardUrl(shot,c)} alt={`候选 ${c}：同场分镜示意，非生成结果`}/></div><div><h3>{c==='A'?'A · 靠近主体，突出线索或情绪':'B · 拉开距离，交代人物与空间'}</h3><button aria-pressed={chosen===c} onClick={()=>choose('demo',c)}>选择候选 {c}</button></div></article>)}</div></details>}
 <div className="journey-review-state" data-testid="journey-review-state" role="status"><span>{asset?`保留选择：已有素材「${asset.title}」`:chosen?`保留选择：示例 ${chosen}`:'尚未选择候选'} · <strong data-testid="journey-review-status">{names[review.status]||'等待审核'}</strong></span></div>
 {shot.status==='review'&&(asset||chosen)&&<div className="journey-review-warning"><p>上游内容或参考已改变。旧选择保留，请确认这一个镜头是否仍适用。</p><button onClick={()=>choose(asset?'asset':'demo',asset?.id||chosen)}>确认当前候选仍可用</button></div>}
 <div className="journey-soft-panel"><h3>返修时说清保留什么、只改什么</h3><fieldset className="v6-tags"><legend>需要修改的地方（可多选）</legend>{issues.map(issue=><label key={issue}><input type="checkbox" checked={(review.issues||[]).includes(issue)} onChange={e=>update({issues:e.target.checked?[...(review.issues||[]),issue]:(review.issues||[]).filter(x=>x!==issue)})}/>{issue}</label>)}</fieldset><label className="journey-field"><span>返修说明</span><textarea value={review.note||''} rows={3} maxLength={12000} onChange={e=>update({note:e.target.value})} placeholder="例如：保留人物与机位，只把转身动作放慢。"/></label><div className="v6-actions"><button disabled={!review.note?.trim()} onClick={()=>update({status:'revision'})}>保存返修要求</button>{cloudMode&&<button disabled={!review.note?.trim()} onClick={()=>{const prompt=(shot.data.prompt||shot.description||'').trim();store.updateEntity(shot.id,{data:{prompt:prompt+'\n\n返修要求：'+review.note.trim(),uxReview:{...review,status:'revision'}}});store.notify('返修要求已加入完整提示词。原候选保留；请重新预检，仅提交这个镜头。');onInspect(shot.id);}}>加入提示词，返修这一镜</button>}<button onClick={()=>{update({status:'revision',allRejected:true});store.notify('已标记本轮都不满意。原候选与输入保留，补充返修后再继续。')}}>这一轮都不满意</button></div>{review.allRejected&&<p role="status">这一轮暂不采用。原选择保留作对照，请补充返修说明，再加入新版本或重新选择。</p>}</div>
 {review.status==='failed'&&<div className="journey-failure" role="alert"><strong>演示失败：参考文件暂时无法读取。</strong><p>原选择与返修要求都已保留。可以重试演示，或返回镜头检查参考。</p><button onClick={onReferences}>检查镜头参考</button></div>}
 {!cloudMode&&<details className="journey-demo-states"><summary>体验失败与恢复</summary><p>这些按钮只演练状态，不提交请求或产生费用。</p><div><button onClick={()=>update({status:'processing'})}>演示处理中</button><button onClick={()=>update({status:'failed'})}>演示失败</button><button disabled={!['failed','cancelled','revision'].includes(review.status)} onClick={()=>update({status:'retry'})}>演示重试</button><button onClick={()=>update({status:'cancelled'})}>演示取消</button></div></details>}
 </div>;
}
