import React,{useSyncExternalStore} from 'react';
import {store} from './store.js';
import {cloudController as cloud} from './cloud-controller.js';
import {useCloud} from './CloudStudio.jsx';
import {roughCutSnapshot,roughCutSummary,roughCutJobs} from './roughcut-model.js';
import {stableJSON,activeJobStatuses,jobLabels,jobMessage,estimateLabel} from './cloud-model.js';
import ArtifactResult from './ArtifactResult.jsx';
import {burnCaptionStatus} from './caption-model.js';
import './roughcut.css';

const run=promise=>promise.catch(()=>{});
const number=value=>Number.isFinite(value)?Number(value.toFixed(3)):'未知';
export default function ChapterRoughCut({project,chapterId,onFix}){
  const c=useCloud(),s=useSyncExternalStore(store.subscribe,store.getState,store.getState),cap=c.capabilities?.chapter_render;
  const options=c.renderOptions[chapterId]||c.renderPlans[chapterId]?.options||{resolution:'720P',aspect:project.journey?.delivery?.aspect||project.journey?.brief?.aspect||'9:16',burn_subtitles:false},setOptions=next=>cloud.setRenderOptions(chapterId,next);
  const summary=roughCutSummary(project,chapterId),plan=c.renderPlans[chapterId],pending=c.renderPending[chapterId],jobs=roughCutJobs(c.jobs,project.id,chapterId);
  const generatedUnsupported=summary.tracks.some(t=>t.generatedFrom)&&cap?.generated_audio!==true;
  const trimUnsupported=summary.shots.some(item=>item.shot.data.selectedVideoRange)&&!(cap?.source_trim===true&&cap?.render_contract_version>=2);
  const subtitleSupported=cap?.subtitles===true&&cap?.render_contract_version>=3,subtitles=burnCaptionStatus(project,chapterId),subtitleBlocked=!!options.burn_subtitles&&(!subtitleSupported||subtitles.issues.length>0);
  const stale=!!plan&&plan.sourceSnapshot!==stableJSON(roughCutSnapshot(project,chapterId,options)),held=jobs.some(j=>j.status==='recovery_hold'),active=jobs.some(j=>activeJobStatuses.has(j.status)),submitted=!!plan&&jobs.some(j=>j.plan_id===plan.plan_id);
  const expired=!!plan?.expires_at&&(typeof plan.expires_at==='number'?plan.expires_at*1000:Date.parse(plan.expires_at))<=Date.now();
  return <section className="roughcut" aria-label="章节视频粗剪"><div className="cloud-section-head"><div><span className="eyebrow">CHAPTER ROUGH CUT</span><h3>把本章已采用视频接起来</h3></div><span className="cloud-badge">CPU 粗剪 · MP4 / FLAC</span></div><p>按场戏与镜头顺序，从已保存的剪辑入点截取目标时长；未设选段时从视频开头取片。视频不够长会阻止导出；图片占位不能当作视频。输出保持比例加边。</p>
  {s.workspace.mode!=='cloud'?<p className="cloud-warning">本机仍可编辑和导出创作方案。实际视频粗剪需要打开云项目并同步已采用素材。</p>:!cap?.implemented?<p className="cloud-warning">当前服务还未提供章节粗剪。已有创作方案和素材保持可用。</p>:<>
    {!cap.enabled&&<p className="cloud-warning">章节粗剪执行尚未启用；可以查看素材，不能据此认为已经导出成片。</p>}
    {generatedUnsupported&&<p role="alert" className="cloud-warning">当前服务不支持同次生成声音的来源核对。请升级服务，或明确静音／解除关联后再预检。</p>}
    {trimUnsupported&&<p role="alert" className="cloud-warning">当前服务不支持已保存的剪辑选段。可继续编辑，升级服务后再预检；不会静默从视频开头取片。</p>}
    <div className="roughcut-options"><label>粗剪清晰度<select aria-label="粗剪清晰度" value={options.resolution} onChange={e=>setOptions({...options,resolution:e.target.value})}>{cap.resolutions.map(value=><option key={value}>{value}</option>)}</select></label><label>粗剪画幅<select aria-label="粗剪画幅" value={options.aspect} onChange={e=>setOptions({...options,aspect:e.target.value})}>{!cap.aspects.includes(options.aspect)&&<option value={options.aspect} disabled>{options.aspect} · 不支持</option>}{cap.aspects.map(value=><option key={value}>{value}</option>)}</select></label><div><b>{cap.fps} fps</b><small>时长会对齐到最近一帧</small></div></div>
    <p>当前章 {summary.shots.length} 镜 · 编辑时长 {number(summary.total)} 秒 · {summary.soundMode==='silent'?'明确静音':`${summary.tracks.length} 条未静音音轨`}。声音只用「节奏与声音」中配置的音轨，不混入视频原声；不含转场或专业混音。</p>
    <div className="roughcut-subtitle-choice"><label><input type="checkbox" checked={!!options.burn_subtitles} disabled={!subtitleSupported&&!options.burn_subtitles} onChange={e=>setOptions({...options,burn_subtitles:e.target.checked})}/>把已确认字幕烧进这次 MP4</label><p>{options.burn_subtitles?'字幕将成为画面的一部分，播放时不能关闭；原字幕稿和独立SRT导出保留。':'默认不烧录，输出画面不添加本项目手动字幕。已上传视频内原有的文字不会被删除；SRT仍可单独导出。'}</p>{!subtitleSupported&&<p className="cloud-warning">当前服务尚未提供字幕烧录。可先编辑、确认并导出SRT；刷新服务能力后再核对。</p>}{options.burn_subtitles&&<><p>固定中文短剧版式：白字黑描边，最多2行、每行18个字符；左右8%、底部12%留白。开始向后、结束向前对齐24fps，不自动改字或换行。</p><div className="subtitle-style-example" aria-label="字幕版式示意"><span>这是一句字幕示意<br/>示意不代表最终字体像素</span></div><p className="muted">示意用于说明位置；最终字形与安全区由服务端预检及成片核验。</p>{subtitles.issues.length>0?<div role="alert" className="cloud-warning"><ul>{subtitles.issues.map((issue,index)=><li key={index}>{issue}</li>)}</ul><button onClick={()=>onFix({id:'roughcut-subtitles',stage:6})}>修正并确认本章字幕</button></div>:<p>已人工确认 {subtitles.aligned.length} 条字幕。预检后请再核对实际对齐时间。</p>}</>}</div>
    <div className="cloud-actions"><button disabled={subtitleBlocked||generatedUnsupported||trimUnsupported||c.busy||!chapterId||!summary.shots.length||!!pending||active||held||!cap.aspects.includes(options.aspect)} onClick={()=>run(cloud.prepareRender(chapterId,options))}>1. 同步并预检本章粗剪</button><button onClick={()=>onFix({id:'roughcut-sound',stage:6})}>检查顺序与声音</button></div>
    {plan&&<div className={'roughcut-plan '+(plan.status==='ready'&&!stale?'ready':'')} aria-label="粗剪预检结果"><h4>{stale?'旧计划 · 需要重新预检':plan.status==='ready'?'服务已核对这一版时间线':'粗剪仍有阻塞项'}</h4>{stale&&<p role="alert" className="cloud-warning">时间线、素材或输出设置已改变，请重新预检；旧计划不会用于当前修改。</p>}{expired&&<p role="alert">本次预检已过期，请重新预检。</p>}{plan.simulation&&<p className="cloud-warning">包含模拟来源，整片保留 SIMULATION 水印。可验收剪辑流程，不能当作 H3 的实际生成效果。</p>}
      <p><b>{plan.output_spec?.width} × {plan.output_spec?.height}</b> · {plan.output_spec?.fps} fps · {number(plan.output_spec?.actual_duration)} 秒 · {plan.output_spec?.frame_count} 帧</p><p className="muted">预检验证文件与剪辑规则，不验证上传视频由哪个模型生成。完成粗剪也不代表生成质量已通过审片。</p>
      <ol className="roughcut-timeline">{plan.timeline?.shots?.map(shot=><li key={shot.shot_id}><div><b>{shot.title}</b><small>{shot.source_title}{shot.simulation?' · 模拟来源':''}</small><span>采用 {number(shot.duration)} 秒 / 源视频 {number(shot.source_duration)} 秒</span>{Number.isFinite(shot.source_start)&&<small>实际取源 {number(shot.source_start)}–{number(shot.source_end)} 秒{Number.isFinite(shot.selected_start)?` · 对齐前范围 ${number(shot.selected_start)}–${number(shot.selected_end)} 秒`:""}</small>}</div><button onClick={()=>onFix({id:'roughcut-'+shot.shot_id,stage:4,entityId:shot.shot_id,field:'seconds'})}>调整此镜</button></li>)}</ol>
      {plan.timeline?.audio_tracks?.length>0?<div className="roughcut-audio"><h4>实际混入的音轨</h4>{plan.timeline.audio_tracks.map((track,index)=><p key={index}>{track.title}{track.generated_from?' · 同次生成声音（跟随视频）':''}：从本章 {number(track.timeline_start)} 秒起，取源 {number(track.source_start)}–{number(track.source_end)} 秒 · 音量 {number(track.gain*100)}%</p>)}</div>:<p>本次输出没有混入音轨。</p>}
      {plan.timeline?.subtitles?.burned?<div className="roughcut-subtitle-plan"><h4>这版计划将字幕烧入画面</h4><p>固定中文短剧版式 · {plan.timeline.subtitles.cues?.length||0} 条 · 导出的MP4无法关闭这些字幕。</p><details><summary>核对字幕正文与实际对齐时间</summary><ol>{plan.timeline.subtitles.cues?.map(cue=><li key={cue.id}><b>{number(cue.start)}–{number(cue.end)} 秒 · 帧 {cue.start_frame}–{cue.end_frame}</b><p className="subtitle-cue-text">{cue.text}</p></li>)}</ol></details></div>:<p>{plan.options?.burn_subtitles?'服务尚未确认这版字幕烧录计划，请先解决阻塞项。':'这版计划不烧录本项目的手动字幕。'}</p>}
      {plan.blockers?.length>0&&<div className="cloud-error" role="alert"><ul>{plan.blockers.map((text,index)=><li key={index}>{text}</li>)}</ul><details><summary>定位镜头，调整时长或采用的视频</summary><div className="cloud-actions">{summary.shots.map(shot=><button key={shot.id} onClick={()=>onFix({id:'roughcut-'+shot.id,stage:4,entityId:shot.id,field:'seconds'})}>{shot.title}</button>)}</div></details></div>}
      {plan.warnings?.length>0&&<details open><summary>这版输出的处理规则</summary><ul>{plan.warnings.map((text,index)=><li key={index}>{text}</li>)}</ul></details>}
      <p>{estimateLabel(plan.estimate)}</p><button className="primary" disabled={c.busy||plan.status!=='ready'||stale||expired||!cap.enabled||!!pending||submitted||active||held} onClick={()=>run(cloud.submitRender(chapterId))}>{submitted?'这版粗剪已提交':'2. 确认时间线，开始粗剪'}</button>
    </div>}
    {held&&<p className="cloud-warning">粗剪任务恢复后待核对，先由管理员确认原任务；本章仍可编辑，但不会重新提交。</p>}{pending&&<div className="cloud-warning" role="alert"><p>{c.busy?'正在向服务确认本次提交，请稍候。':'有一次粗剪提交尚未确认。原计划和标识已保留，即使后来修改章节，也只核对这次原任务。'}</p><button disabled={c.busy||held} onClick={()=>run(cloud.submitRender(chapterId))}>用原标识恢复粗剪</button></div>}
    <div className="cloud-section-head"><h4>本章粗剪版本</h4><button disabled={c.busy} onClick={()=>run(cloud.refresh())}>刷新粗剪进度</button></div><p>每次结果属于提交时的时间线快照，不会自动替换你之后的修改。</p>
    {!jobs.length&&<p className="muted">尚未提交本章粗剪。先预检，确认后才会创建任务。</p>}
    <div className="roughcut-jobs">{jobs.map(job=><article key={job.id}><div className="cloud-section-head"><b>{job.simulation?'模拟来源 · ':''}{jobLabels[job.status]||job.status}</b>{activeJobStatuses.has(job.status)&&<button disabled={c.busy} onClick={()=>run(cloud.cancel(job.id))}>请求取消粗剪</button>}</div><p role="status">{job.status==='running'?'正在拼接、对齐与核验视频。':jobMessage(job)}</p><p>{job.effective_request?.render?.version>=3?(job.effective_request.render.subtitles?"这次成片配置：字幕烧入画面，播放器不能关闭。":"这次成片配置：未添加本项目手动字幕。"):("历史版本未提供字幕配置证据；以实际文件为准。")}</p><small>{job.created_at?new Date(typeof job.created_at==='number'?job.created_at*1000:job.created_at).toLocaleString():''}{job.effective_request?.duration?` · ${number(job.effective_request.duration)} 秒`: ''} · 任务 {job.id}</small>{job.status==='succeeded'&&(job.artifacts||[]).filter(a=>['video','audio'].includes(a.kind)).map(artifact=><ArtifactResult key={artifact.id} artifact={artifact} job={job} title={summary.chapterTitle}/>)}</article>)}</div>
  </>}
  </section>;
}
