import React,{useEffect,useState} from 'react';
import {store} from './store.js';
import {captionStatus,exportSrt} from './caption-model.js';
import {chapterHandover,shotListCsv} from './handover-model.js';
import './handover.css';
function TextDownload({text,mime,name,disabled,children}){const [url,setUrl]=useState('');useEffect(()=>{if(disabled){setUrl('');return;}const next=URL.createObjectURL(new Blob([text],{type:mime}));setUrl(next);return()=>URL.revokeObjectURL(next);},[text,mime,disabled]);return disabled||!url?<button disabled>{children}</button>:<a className="handover-download" href={url} download={name} onClick={()=>store.notify('已请求浏览器下载交接文件；素材本体需要另行交付。')}>{children}</a>;}
export default function ChapterHandover({project,chapterId,onFix}){
 if(!chapterId)return null;
 const manifest=chapterHandover(project,chapterId,{cloud:store.getState().workspace.mode==='cloud'}),captions=captionStatus(project,chapterId),name=(project.title+'-'+manifest.chapter_title).replace(/[<>:"/\\|?*\u0000-\u001f]/g,'_');
 return <section className="chapter-handover" aria-label="章节剪辑交接"><h3>交给剪辑师继续做</h3><p>只导出当前章：{manifest.shots.length} 镜、{manifest.assets.length} 份关联素材、{manifest.audio_tracks.length} 条声音安排。表内保留未确认项、返修备注与模拟标记；不把剪辑计划当成成片。</p><div className="cloud-actions"><TextDownload disabled={!manifest.shots.length} text={shotListCsv(manifest)} mime="text/csv;charset=utf-8" name={name+'-镜头清单.csv'}>下载本章镜头清单 CSV</TextDownload><TextDownload disabled={!manifest.shots.length} text={JSON.stringify(manifest,null,2)} mime="application/json;charset=utf-8" name={name+'-素材引用与审片备注.json'}>下载素材引用与审片备注 JSON</TextDownload></div><p>CSV可用于表格审片，JSON保留稳定素材编号、参考选段、锚点和声音位置。都不含文件本体或下载授权；不会自动链接到剪辑软件。</p><details><summary>检查本次交接内容</summary><pre className="handover-preview">{JSON.stringify(manifest,null,2)}</pre></details><h4>本章字幕 SRT</h4><p>{captions.track.cues?.length||0} 条 · {captions.confirmed?'已人工确认文字与时间':'尚未确认这一版文字与时间'}。独立字幕文件，不含自动听写、翻译或烧录。</p><div className="cloud-actions"><button onClick={()=>onFix({id:'caption-edit',stage:6})}>编辑与核对手动字幕</button><TextDownload disabled={!captions.confirmed} text={captions.confirmed?exportSrt(project,chapterId):''} mime="application/x-subrip;charset=utf-8" name={name+'-手动字幕.srt'}>下载已确认的本章 SRT</TextDownload></div>{captions.confirmed&&<details><summary>预览将导出的字幕文本</summary><pre className="handover-preview">{exportSrt(project,chapterId)}</pre></details>}</section>;
}
