import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,ImagePlus,Plus,Shirt,Trash2,Upload,Users} from 'lucide-react';
import {store,children} from './store.js';
import {uploadLookImage} from './media-operations.js';
import {createUploadGate} from './workspace-context.js';
import {getFile,uploadFile} from './media.js';
import {gallerySlots,effectiveLook,characterPath,lookReferences,lookShots,addLook,editLook,bindLook,deleteLook} from './character-model.js';
import './character-studio.css';

function Field({label,children:content}){return <label className="cs-field"><span>{label}</span>{React.isValidElement(content)?React.cloneElement(content,{'aria-label':label}):content}</label>}
function Thumb({asset,label}){
  const [url,setUrl]=useState(''),[error,setError]=useState('');
  useEffect(()=>{let alive=true,objectUrl='';setUrl('');setError('');if(asset?.data.fileId)getFile(asset.data.fileId).then(blob=>{if(!alive)return;if(blob){objectUrl=URL.createObjectURL(blob);setUrl(objectUrl)}else setError('文件缺失，请补传')}).catch(()=>alive&&setError('文件读取失败，请重新上传'));return()=>{alive=false;if(objectUrl)URL.revokeObjectURL(objectUrl)}},[asset?.data.fileId]);
  return <div className="cs-thumb">{url&&!error?<img src={url} alt={label} onError={()=>setError('图片无法解码，请换一张图片')}/>:<><ImagePlus size={25}/><span>{error||(!asset?'还没有这张参考':asset.data.fileId?'正在读取…':'文件缺失，请补传')}</span></>}</div>;
}
function LookDetails({project,character,look,commit}){
  const uploadGate=useRef(createUploadGate());
  const [name,setName]=useState(look.name),[description,setDescription]=useState(look.description||''),[busy,setBusy]=useState('');
  useEffect(()=>{setName(look.name);setDescription(look.description||'')},[look.name,look.description]);
  const images=project.entities.filter(e=>e.type==='image');
  const patch=(data)=>commit(p=>editLook(p,character.id,look.id,data));
  async function upload(slot,file){if(!file)return;await uploadGate.current.run(async()=>{setBusy(slot);try{await uploadLookImage({store,characterId:character.id,lookId:look.id,slot,file,upload:uploadFile});}catch(error){store.notify(error.message)}finally{setBusy('')}})}
  return <div className="cs-look-details" data-testid="character-look-details"><div className="cs-fields"><Field label="造型名称"><input value={name} maxLength={100} onChange={e=>setName(e.target.value)} onBlur={()=>{if(name!==look.name&&!patch({name}))setName(look.name)}} placeholder="例如：第 1 天 · 雨夜外套"/></Field><Field label="服装、发型与剧情状态"><textarea value={description} maxLength={3000} rows={3} onChange={e=>setDescription(e.target.value)} onBlur={()=>description!==look.description&&patch({description})} placeholder="例如：深绿风衣，头发淋湿，右袖沾泥；五官与身份保持一致。"/></Field></div><p className="cs-hint">文字离开输入框后保存 · 版本 {look.version} · 可用顶部“撤销”恢复</p><div className="cs-gallery">{Object.entries(gallerySlots).map(([slot,label])=>{const asset=images.find(e=>e.id===look.gallery?.[slot]);return <section key={slot} className="cs-gallery-slot" data-testid={`look-slot-${slot}`}><h4>{label}参考</h4><Thumb asset={asset} label={`${character.title} ${look.name} ${label}参考`}/><Field label={`选择${label}参考图`}><select value={asset?.id||''} onChange={e=>patch({gallery:{[slot]:e.target.value}})}><option value="">稍后补充</option>{images.map(e=><option key={e.id} value={e.id}>{e.title}{e.data.missingFile||!e.data.fileId?' · 文件缺失':''}</option>)}</select></Field><label className={'cs-upload '+(busy?'busy':'')}><Upload size={14}/>{busy===slot?'正在保存…':`上传${label}图`}<input aria-label={`上传${label}图`} type="file" accept="image/png,image/jpeg,image/webp,image/gif" disabled={!!busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';upload(slot,file)}}/></label>{asset&&<span className="cs-file-name">{asset.data.fileName||asset.title}</span>}</section>})}</div><p className="cs-hint">按镜头需要补图，不强制三张齐全。上传的是你的参考素材；这里不会生成新的人物图。</p></div>;
}

export default function CharacterStudio({project,chapterId,onAdd,onInspect}){
  const characters=project.entities.filter(e=>e.type==='character'),chapters=project.entities.filter(e=>e.type==='chapter').sort((a,b)=>a.order-b.order);
  const [characterId,setCharacterId]=useState(''),[lookId,setLookId]=useState(''),[name,setName]=useState(''),[deleteOpen,setDeleteOpen]=useState(false),[replacement,setReplacement]=useState(''),[activeChapterId,setActiveChapterId]=useState(chapterId||'');
  const character=characters.find(e=>e.id===characterId)||characters[0],looks=character?.data.looks||[],look=looks.find(l=>l.id===lookId)||looks[0];
  const chapter=chapters.find(e=>e.id===(activeChapterId||chapterId))||chapters[0],scenes=chapter?children(project,chapter.id).filter(e=>e.type==='scene'):[];
  useEffect(()=>{if(chapterId)setActiveChapterId(chapterId)},[chapterId]);
  useEffect(()=>{if(project.journey?.focusCharacterId){setCharacterId(project.journey.focusCharacterId);setLookId(project.journey.focusLookId||'');}},[project.journey?.focusCharacterId,project.journey?.focusLookId]);
  const commit=(mutate)=>{let result;const ok=store.editProject(p=>{result=mutate(p);return result.ok});if(!ok&&result?.error)store.notify(result.error);return !!ok};
  const latest=project.journey?.characterChange,affected=(latest?.shotIds||[]).map(id=>project.entities.find(e=>e.id===id)).filter(Boolean);
  const references=character&&look?lookReferences(project,character.id,look.id):[],usedShots=character&&look?lookShots(project,character.id,look.id):[];
  function create(){if(!character)return;const id=`look-${crypto.randomUUID()}`;if(commit(p=>addLook(p,character.id,{id,name}))){setLookId(id);setName('');setDeleteOpen(false)}}
  const switchCharacter=id=>{setCharacterId(id);setLookId('');setDeleteOpen(false)};
  return <section className="character-studio" data-testid="character-studio"><header className="cs-header"><div><span className="cs-kicker">CHARACTER CONTINUITY</span><h3><Shirt size={19}/>同一个人，每场穿对造型</h3><p>先固定身份，再保存衣着与状态。场戏设默认造型，特写或回忆镜头可以单独覆盖。</p></div></header>{!character?<div className="cs-empty"><Users size={28}/><h4>先添加故事中的第一个角色</h4><p>无人或抽象画面可以跳过这里。</p><button onClick={()=>onAdd('character')}><Plus size={15}/>添加角色</button></div>:<><div className="cs-identity"><Field label="选择要设计的角色"><select value={character.id} onChange={e=>switchCharacter(e.target.value)}>{characters.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></Field><div><strong>{character.title} · 固定身份</strong><p>{character.description||'身份与性格尚未填写，可先补一句人物设定。'}</p><button onClick={()=>onInspect(character.id)}>编辑角色身份<ArrowRight size={13}/></button></div></div><div className="cs-looks-head"><h4>造型档案 <span>{looks.length}</span></h4><span>同一身份，不同服装 / 剧情状态</span></div><div className="cs-look-tabs" role="group" aria-label="角色造型">{looks.map(l=><button key={l.id} aria-pressed={l.id===look?.id} data-testid={`character-look-${l.id}`} onClick={()=>{setLookId(l.id);setDeleteOpen(false)}}><Shirt size={14}/>{l.name}{l.id===look?.id&&<Check size={13}/>}</button>)}</div><form className="cs-new-look" onSubmit={e=>{e.preventDefault();create()}}><Field label="新造型名称"><input value={name} maxLength={100} onChange={e=>setName(e.target.value)} placeholder={looks.length?'例如：第 2 天 · 工作制服':'例如：第 1 天 · 日常造型'}/></Field><button type="submit" disabled={!name.trim()}><Plus size={15}/>添加造型</button></form>{look&&<><LookDetails key={`${character.id}:${look.id}`} project={project} character={character} look={look} commit={commit}/><div className="cs-look-use"><span>「{look.name}」用于 {usedShots.length} 个镜头 · {references.length} 处显式绑定</span><button className="cs-delete-button" onClick={()=>{setDeleteOpen(!deleteOpen);setReplacement('')}}><Trash2 size={13}/>删除当前造型</button></div>{deleteOpen&&<div className="cs-delete-panel" data-testid="look-delete-panel"><h4>删除「{look.name}」前，处理它的场次</h4><p>角色身份和参考图片保留。受影响镜头的候选也会保留并提示复核；可撤销。</p>{references.length>0&&<><ul>{references.map(e=><li key={e.id}>{characterPath(project,e.id)}</li>)}</ul><Field label="删除后的绑定处理"><select value={replacement} onChange={e=>setReplacement(e.target.value)}><option value="">解除这些绑定（镜头恢复继承场戏）</option>{looks.filter(l=>l.id!==look.id).map(l=><option key={l.id} value={l.id}>改用「{l.name}」</option>)}</select></Field></>}<div className="cs-actions"><button onClick={()=>setDeleteOpen(false)}>保留造型</button><button data-testid="confirm-delete-look" onClick={()=>{if(commit(p=>deleteLook(p,character.id,look.id,replacement))){setDeleteOpen(false);setLookId('')}}}><Trash2 size={14}/>确认删除造型</button></div></div>}</>}
    <section className="cs-casting" data-testid="character-casting"><div className="cs-looks-head"><h4>把「{character.title}」安排进场戏</h4><span>更换角色可安排其他演员</span></div>{chapters.length>0&&<Field label="造型绑定章节"><select value={chapter?.id||''} onChange={e=>setActiveChapterId(e.target.value)}>{chapters.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></Field>}{!scenes.length?<p className="cs-empty-text">还没有场戏。先在“章节剧本”添加场戏，再把造型用进去。</p>:!looks.length?<p className="cs-empty-text">先给这个角色添加一套造型，再选择它在哪场出现。</p>:scenes.map(scene=>{const sceneBinding=scene.data.cast?.find(c=>c.characterId===character.id),sceneLook=looks.find(l=>l.id===sceneBinding?.lookId),shots=children(project,scene.id).filter(e=>e.type==='shot');return <article className="cs-scene" key={scene.id} data-testid={`cast-scene-${scene.id}`}><div className="cs-scene-top"><button className="cs-scene-name" onClick={()=>onInspect(scene.id)}>{scene.title}<ArrowRight size={12}/></button><Field label={`${scene.title} · 场戏默认造型`}><select value={sceneLook?.id||''} onChange={e=>commit(p=>bindLook(p,scene.id,character.id,e.target.value))}><option value="">这场暂不安排此角色</option>{looks.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></Field></div>{shots.length?<details className="cs-shots"><summary>检查 {shots.length} 个镜头的继承与覆盖</summary>{shots.map(shot=>{const effective=effectiveLook(project,shot,character.id),currentLook=looks.find(l=>l.id===effective?.lookId),own=shot.data.cast?.find(c=>c.characterId===character.id);return <div key={shot.id} className="cs-shot" data-testid={`cast-shot-${shot.id}`}><div><strong>{shot.title}</strong><span className={own?'override':''}>{currentLook?`${effective.inherited?'继承场戏':'单独覆盖'} · ${currentLook.name}`:'尚未安排此角色'}</span></div><Field label={`${shot.title} · 镜头造型覆盖`}><select value={own?.lookId||''} onChange={e=>commit(p=>bindLook(p,shot.id,character.id,e.target.value))}><option value="">{sceneLook?`跟随场戏：${sceneLook.name}`:'跟随场戏（尚未安排）'}</option>{looks.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></Field></div>})}</details>:<p className="cs-hint">新加到这场的镜头会沿用默认造型。</p>}</article>})}</section></>}
    {latest&&<aside className="cs-impact" data-testid="character-impact" role="status"><h4>{latest.characterName} · {latest.reason}</h4><p>{affected.length?`${affected.length} 个镜头需复核；原候选和返修说明已保留。`:'没有镜头的实际造型发生变化。'}</p>{affected.length>0&&<ul>{affected.map(shot=><li key={shot.id}><button onClick={()=>onInspect(shot.id)}>{characterPath(project,shot.id)}<ArrowRight size={13}/></button><span>{shot.status==='review'?'待复核':'已继续处理'}</span></li>)}</ul>}<p className="cs-hint">这里列出最近一次修改的实际影响；使用其他造型、或已单独覆盖的镜头不会被连带改动。</p></aside>}
  </section>;
}
