import {chapterTiming} from './media-timing.js';
import React from 'react';
import {store} from './store.js';
import {download} from './media.js';
import AssetPreview from './AssetPreview.jsx';
import {deliveryIssues,chapterShots} from './delivery-model.js';
import ChapterRoughCut from './ChapterRoughCut.jsx';
import ChapterHandover from './ChapterHandover.jsx';
export default function DeliveryStudio({project:p,chapterId,onFix,focusIssue}){
 const settings=p.journey?.delivery||{},issues=deliveryIssues(p,chapterId),pending=issues.filter(i=>!i.accepted),shots=chapterShots(p,chapterId),cover=p.entities.find(e=>e.id===settings.coverAssetId);
 const set=(key,value)=>store.editProject(q=>{q.journey={...(q.journey||{}),delivery:{...(q.journey?.delivery||{}),[key]:value}}});
 const exportPlan=()=>{const q=store.exportProject();download(new Blob([JSON.stringify({type:'prototype-plan',version:2,executable:false,deliverable:'创作方案与交付检查，不是视频',projectId:q.id,title:q.title,logline:q.logline,chapterId,journey:{...(q.journey||{}),brief:{entry:'idea',aspect:'9:16',seconds:60,...q.journey?.brief},sound:{subtitles:'none',...q.journey?.sound},delivery:{platform:'暂未决定',version:'草案 v1',aspect:q.journey?.brief?.aspect||'9:16',...settings}},entities:q.entities,links:q.links,checklist:issues,remaining:pending.map(i=>({title:i.title,path:i.path})),acceptedPlaceholders:issues.filter(i=>i.accepted),note:'文件本体请用完整备份；示例分镜不是生成结果。'},null,2)],{type:'application/json'}),q.title+'-创作方案草案.json');store.notify('创作方案已下载，含具体待办和已接受占位。没有导出成片。')};
 return <div className="delivery-studio"><div className="journey-delivery-intro"><div><span className="eyebrow">REVIEW & HANDOVER</span><h3>{p.title}</h3><p>先决定这一版怎样交接，再检查具体镜头。</p></div><span className="journey-delivery-badge">制作草案</span></div>
 <div className="v6-requirements v6-delivery-settings"><label>发布目标<select aria-label="发布目标" value={settings.platform||''} onChange={e=>set('platform',e.target.value)}><option value="">暂未决定</option><option>竖屏短剧平台</option><option>YouTube / 横屏视频</option><option>内部审片</option><option>客户提案</option></select></label><label>这一版名称<input value={settings.version||'草案 v1'} maxLength={100} onChange={e=>set('version',e.target.value)}/></label><label>交付画幅<select aria-label="交付画幅" value={settings.aspect||p.journey?.brief?.aspect||'9:16'} onChange={e=>set('aspect',e.target.value)}><option>9:16</option><option>16:9</option><option>1:1</option></select></label><label>封面图片（可稍后决定）<select aria-label="封面图片（可稍后决定）" value={settings.coverAssetId||''} onChange={e=>set('coverAssetId',e.target.value)}><option value="">暂不设置</option>{p.entities.filter(e=>e.type==='image'&&e.data.fileId&&!e.data.missingFile).map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label></div>{cover&&<div className="v6-delivery-cover"><AssetPreview entity={cover}/></div>}
 <div className="journey-summary-grid"><div><span>本章范围</span><strong>{shots.length} 镜头</strong><small>{Number((chapterTiming(shots).at(-1)?.end||0).toFixed(3))} 秒</small></div><div><span>声音决定</span><strong>{p.journey?.sound?.mode==='silent'?'静音先行':p.journey?.sound?.mode?'有声方案':'尚未决定'}</strong><small>可返回节奏与声音试听</small></div><div><span>待处理</span><strong>{pending.length} 项</strong><small>{issues.filter(i=>i.accepted).length} 项占位已接受</small></div></div>
 <ChapterHandover project={p} chapterId={chapterId} onFix={onFix}/>
 <ChapterRoughCut key={p.id+':'+chapterId} project={p} chapterId={chapterId} onFix={onFix}/>
 {!pending.length&&<div className="v6-empty-good" role="status">本章制作草案的必要决定已记录。可交接草案；这不代表已渲染成片或通过画面质量审核。</div>}
 {focusIssue&&!issues.some(i=>i.id===focusIssue)&&<p className="journey-tip" role="status">已返回交付检查。请核对更新后的检查项与粗剪预检结果，再继续交付。</p>}
 <div aria-label="逐项交付检查">{issues.map(issue=><article data-testid={'delivery-issue-'+issue.id} key={issue.id} className={'v6-delivery-issue '+(issue.accepted?'accepted':'')+(focusIssue===issue.id?' v6-target':'')}><div><small>{issue.path}</small><strong>{issue.accepted?'本版接受占位 · ':''}{issue.title}</strong><p>{issue.detail}</p>{issue.placeholderAllowed&&<label><input type="checkbox" checked={!!issue.accepted} onChange={e=>store.updateEntity(issue.entityId,{status:'draft',data:{acceptPlaceholder:e.target.checked,uxReview:{...(p.entities.find(s=>s.id===issue.entityId)?.data.uxReview||{}),status:e.target.checked?'placeholder':null,allRejected:false}}})}/> 本版接受文字占位，保留在交付单中</label>}</div><button onClick={()=>onFix(issue)}>去补充：{issue.title}</button></article>)}</div>
 <details><summary>回看各阶段决定</summary><div className="v6-actions">{[1,2,3,4,5,6].map(n=><button key={n} data-testid={'journey-check-'+n} onClick={()=>onFix({stage:n,id:'stage-'+n})}>返回第 {n} 步</button>)}</div></details>
 <aside className="journey-tip">建议：交付前完整看一遍本章，核对人物造型、动作衔接和声音。封面、发布目标可以稍后决定，未选项会按原样写进草案。</aside>
 <div className="journey-export-box"><div><h3>把这一版的制作决定带走</h3><p>包含章节、候选、造型绑定、参考范围、声音和待办。素材文件请另用顶部「备份」。</p></div><button className="primary" data-testid="journey-export" onClick={exportPlan}>导出创作方案草案</button></div></div>;
}
