import React,{useRef,useState,useSyncExternalStore} from 'react';
import {Upload,Image,Video,Music,Film,Plus,Trash2} from 'lucide-react';
import {store} from './store.js';
import {cloudController as cloud} from './cloud-controller.js';
import {modeAvailability} from './generation-availability.js';
import {uploadFile} from './media.js';
import {createUploadGate} from './workspace-context.js';
import {freestyleRoles,freestyleInputIds,uploadFreestyleFiles} from './media-operations.js';
import {controlsForRecipe,referenceSpecs,effectiveReferenceCount,removeFreestyleInput,selectedRecipe} from './cloud-model.js';
import {effectiveLook,bindLook} from './character-model.js';
import {bindLocation} from './location-model.js';
import AssetPreview from './AssetPreview.jsx';
import ReferenceEditor from './ReferenceEditor.jsx';
import RecipeExecutionNotice from './RecipeExecutionNotice.jsx';
import './media-workspace.css';

const names={image:'图片',video:'视频',audio:'音频'},icons={image:Image,video:Video,audio:Music};
const mediaAccept={image:'image/png,image/jpeg,image/webp,image/gif',video:'video/mp4,video/webm,video/quicktime',audio:'audio/mpeg,audio/wav,audio/x-wav,audio/mp4,audio/ogg,audio/flac,audio/x-flac,audio/webm'};
const find=(project,id)=>project.entities.find(entity=>entity.id===id);

export function InputZone({project,shot,kind,role,title,description,maximum=1,disabled=false,guide=false}){
  const ref=useRef(),uploadGate=useRef(createUploadGate()),[busy,setBusy]=useState(false),[error,setError]=useState(''),[dragging,setDragging]=useState(false),Icon=icons[kind]||Film;
  const roles=freestyleRoles(kind,role),ids=freestyleInputIds(project,shot.id,{kind,role,guide}),assets=[...new Set(ids)].map(id=>find(project,id)).filter(Boolean),directCount=ids.length,countAllReferences=!!kind&&!guide&&!['firstFrame','lastFrame'].includes(role),count=countAllReferences?effectiveReferenceCount(project,shot.id,kind):directCount;
  async function accept(files){
    if(uploadGate.current.busy){setError('这一区域正在保存素材，请完成后再添加。');return;}
    setError('');if(disabled){setError('请先选择支持此输入的生成方式。现有素材会保留。');return;}if(!files.length)return;
    await uploadGate.current.run(async()=>{setBusy(true);try{await uploadFreestyleFiles({store,shotId:shot.id,files,kind,role,guide,maximum,countAllReferences,upload:uploadFile});}catch(error){setError(error.message);}finally{setBusy(false);if(ref.current)ref.current.value='';}});
  }
  const rememberMetadata=(asset,metadata)=>{const current=store.getState().project;if(current.id!==project.id)return;const live=find(current,asset.id);if(!live||live.data.fileId!==asset.data.fileId||Number.isFinite(live.data.metadata?.duration)||Number.isFinite(live.data.metadata?.duration_s))return;store.updateEntity(asset.id,{data:{metadata:{...live.data.metadata,...metadata,source:'browser_preview'}}});};
  return <section className={'h3-input-zone '+(dragging?'is-dragging ':'')+(disabled?'is-disabled':'')} aria-label={title} onDragOver={event=>{event.preventDefault();if(!disabled&&!uploadGate.current.busy)setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={event=>{event.preventDefault();setDragging(false);accept([...event.dataTransfer.files]);}}>
    <header><Icon size={19}/><h4>{title}</h4><span>{count}/{maximum}</span></header><p>{description}{count>directCount?` · 含 ${count-directCount} 份人物或地点继承参考。`:""}</p>
    <input ref={ref} type="file" tabIndex={-1} disabled={disabled||busy||count>=maximum} className="visually-hidden" aria-label={'上传'+title} multiple={maximum>1} accept={kind?mediaAccept[kind]:Object.values(mediaAccept).join(',')} onChange={event=>accept([...event.target.files])}/>
    <button type="button" className="h3-drop-button" disabled={disabled||busy||count>=maximum} onClick={()=>ref.current.click()}><Upload size={18}/>{busy?'正在保存素材…':count>=maximum?'已达到此区上限 · 可先解除一份关联':`拖入${kind?names[kind]:'图片、视频或音频'}，或点击上传`}</button>
    {error&&<p className="cloud-error" role="alert">{error}</p>}
    {!!assets.length&&<div className="h3-media-grid">{assets.map(asset=><article key={asset.id}><div className={'h3-media-preview '+asset.type}><AssetPreview entity={asset} onMetadata={metadata=>rememberMetadata(asset,metadata)}/></div><div className="h3-media-caption"><b>{asset.title}</b><small>{names[asset.type]}{asset.data.metadata?.duration?` · ${Number(asset.data.metadata.duration).toFixed(1)} 秒`:''}</small>{asset.type==='video'&&!guide&&<label className="h3-video-audio"><input type="checkbox" checked={shot.data.h3?.video_audio?.[asset.id]!==false} onChange={event=>{const live=store.getState().project.entities.find(entity=>entity.id===shot.id);store.updateEntity(shot.id,{data:{h3:{...live.data.h3,video_audio:{...live.data.h3?.video_audio,[asset.id]:event.target.checked}}}});}}/>参考视频原声</label>}<button type="button" disabled={busy} onClick={()=>store.editProject(project=>removeFreestyleInput(project,shot.id,asset.id,{guide,roles}))}><Trash2 size={13}/>解除{guide?'锚点':'关联'}</button></div></article>)}</div>}
  </section>;
}

function GuideTiming({project,shot,recipe}){
  const guides=shot.data.h3?.guides||[],duration=controlsForRecipe(recipe,shot.data.h3?.controls,shot.data.seconds).duration||shot.data.seconds||5,[error,setError]=useState('');
  const update=(index,patch)=>store.editProject(project=>{const live=find(project,shot.id);if(!live?.data.h3?.guides?.[index])return false;live.data.h3.guides[index]={...live.data.h3.guides[index],...patch};live.version++;live.status='review';});
  const number=(text,{minimum=0,maximum=Infinity}={})=>text!==''&&Number.isFinite(Number(text))&&Number(text)>=minimum&&Number(text)<maximum;
  return !!guides.length&&<div className="h3-guide-timing">{guides.map((guide,index)=>{const asset=find(project,guide.media_id);return <article key={`${guide.media_id}:${index}`}><strong>{index+1}. {asset?.title||'素材已移除'}</strong><div className="h3-guide-fields"><label>放在生成片段的第几秒<input aria-label={`锚点 ${index+1} · 时间（秒）`} type="number" min="0" max={duration} step="0.01" value={guide.time_seconds} onChange={event=>{if(number(event.target.value,{maximum:duration})){update(index,{time_seconds:Number(event.target.value)});setError('');}else setError('锚点时间须在 0 秒至生成片段结束之前。');}}/></label>{asset?.type==='video'&&<label className="h3-guide-checkbox"><input type="checkbox" checked={!!guide.use_audio} onChange={event=>update(index,{use_audio:event.target.checked})}/>使用这段视频的声音</label>}{asset&&asset.type!=='image'&&<fieldset><legend>原文件有效片段（可选）</legend><label>开始秒数<input aria-label={`锚点 ${index+1} · 原文件开始`} type="number" min="0" step="0.01" value={guide.source_range?.start??''} onChange={event=>{if(number(event.target.value)){update(index,{source_range:{...guide.source_range,start:Number(event.target.value),end:guide.source_range?.end??Number(event.target.value)+1,fileId:asset.data.fileId}});setError('');}}}/></label><label>结束秒数<input aria-label={`锚点 ${index+1} · 原文件结束`} type="number" min="0" step="0.01" value={guide.source_range?.end??''} onChange={event=>{if(number(event.target.value)&&Number(event.target.value)>(guide.source_range?.start??0)){update(index,{source_range:{start:guide.source_range?.start??0,end:Number(event.target.value),fileId:asset.data.fileId}});setError('');}else setError('原片结束须晚于开始。');}}/></label>{guide.source_range&&<button type="button" onClick={()=>update(index,{source_range:null})}>恢复使用完整原文件</button>}</fieldset>}</div><button type="button" onClick={()=>store.editProject(project=>{const live=find(project,shot.id);live.data.h3.guides=live.data.h3.guides.filter((_,i)=>i!==index);live.version++;live.status='review';})}>移除此锚点</button></article>;})}{error&&<p role="alert" className="cloud-error">{error}</p>}<p>锚点素材必须完整放入输出时长。原文件仍保留；云端预检会检查解码、片段长度和边界。</p></div>;
}

export function ShotSharedReferences({project,shot}){
  const scene=find(project,shot.parentId),characters=project.entities.filter(entity=>entity.type==='character'),locations=project.entities.filter(entity=>entity.type==='location');
  const {references}=referenceSpecs(project,shot.id),directIds=new Set(project.links.filter(link=>link.target===shot.id&&['image','video','audio'].includes(find(project,link.source)?.type)).map(link=>link.source)),inherited=references.filter(ref=>!directIds.has(ref.entity.id));
  const commit=mutate=>{let result;const ok=store.editProject(project=>{result=mutate(project);return result?.ok!==false;});if(!ok)store.notify(result?.error||store.getState().notice);};
  return <section className="h3-shared-references"><h4>复用人物与场景</h4><p>选定造型后会带入对应图集；选择地点会带入其参考图片。只在全能参考模式中使用这些图片。</p><div className="h3-cast-fields">{!!locations.length&&<label>这个镜头在哪里<select aria-label={`${shot.title} · 地点`} value={shot.data.locationId||''} onChange={event=>commit(project=>bindLocation(project,shot.id,event.target.value))}><option value="">{scene?.data.locationId?`跟随场戏：${find(project,scene.data.locationId)?.title||'地点已删除'}`:'暂不指定地点'}</option>{locations.map(location=><option key={location.id} value={location.id}>{location.title}</option>)}</select></label>}{characters.map(character=>{const binding=effectiveLook(project,shot,character.id),looks=character.data.looks||[];return !!looks.length&&<label key={character.id}>{character.title} · 造型<select aria-label={`${shot.title} · ${character.title}造型`} value={shot.data.cast?.find(cast=>cast.characterId===character.id)?.lookId||''} onChange={event=>commit(project=>bindLook(project,shot.id,character.id,event.target.value))}><option value="">{binding?.inherited?`跟随场戏：${looks.find(look=>look.id===binding.lookId)?.name||'造型已删除'}`:'此镜头暂不安排'}</option>{looks.map(look=><option key={look.id} value={look.id}>{look.name}</option>)}</select></label>;})}</div>{!!inherited.length&&<div className="h3-inherited-grid">{inherited.map(ref=><article key={ref.key}><AssetPreview entity={ref.entity}/><span>{ref.purpose==='identity'?'人物造型':'地点参考'} · {ref.entity.title}</span></article>)}</div>}{!characters.length&&!locations.length&&<p className="media-workspace-hint">还没有共享人物或地点，也可以直接上传当前镜头参考。</p>}</section>;
}

export default function H3Inputs({project,shot,recipes=[],onInspect,local=false,showShared=true}){
  const capacity=useSyncExternalStore(cloud.subscribe,cloud.getState,cloud.getState);
  const recipe=selectedRecipe(recipes,shot.data.h3),mode=recipe?.mode||(local?shot.data.h3?.inputMode||'fl':null),limits=recipe?.limits||{},draftLimits=local&&!recipe,maximum=(key,fallback)=>limits[key]??(draftLimits?fallback:0);
  const options=recipes.length?recipes:local?[{mode:'fl',label:'文生 / 首尾帧'},{mode:'ref',label:'全能参考'}]:[];
  const choose=option=>{if(!local&&option.id!==recipe?.id){const live=cloud.getState(),status=modeAvailability(live.availability,live.capabilities,{deployment_profile_id:null,recipe_id:option.id});if(!status.available){store.notify(status.message);return;}}const h3={...shot.data.h3,inputMode:option.mode};if(option.id)h3.recipeId=option.id;else delete h3.recipeId;store.updateEntity(shot.id,{data:{h3}});};
  const frameCount=project.links.filter(link=>link.target===shot.id&&['firstFrame','lastFrame'].includes(link.role)).length,referenceCount=project.links.filter(link=>link.target===shot.id&&['image','video','audio'].includes(find(project,link.source)?.type)&&!['firstFrame','lastFrame'].includes(link.role)).length;
  return <section className="h3-input-workspace" aria-label={`${shot.title} · 图片视频音频输入`}><fieldset className="h3-mode-picker"><legend>① 先选择生成方式</legend><div>{options.map(option=><label key={option.id||option.mode} className={(recipe?recipe.id===option.id:mode===option.mode)?'selected':''}><input type="radio" name={'h3-input-mode-'+shot.id} disabled={!local&&option.id!==recipe?.id&&!modeAvailability(capacity.availability,capacity.capabilities,{deployment_profile_id:null,recipe_id:option.id}).available} checked={recipe?recipe.id===option.id:mode===option.mode} onChange={()=>choose(option)}/><span><b>{option.mode==='fl'?'文生 / 首尾帧':option.mode==='ref'?'全能参考':option.label}{!local?' · '+modeAvailability(capacity.availability,capacity.capabilities,{deployment_profile_id:null,recipe_id:option.id}).label:''}</b><small>{option.mode==='fl'?'一句提示词，或指定开始与结尾的画面':'用人物图、动作视频和声音表达你的想法'}</small></span></label>)}</div>{!options.length&&<p role="status">正在读取生成方式；可保留草稿，暂不接受新的模型输入。</p>}{draftLimits&&<p className="media-workspace-hint">本机素材整理，尚未核对云端能力。云端可执行模式、数量和时长以登录后的服务预检为准。</p>}</fieldset>{recipe&&<RecipeExecutionNotice recipe={recipe} project={project} shot={shot}/>}
    <div className="h3-input-title"><h3>② 把素材直接放进这个镜头</h3><p>{mode==='fl'?'不需要参考也能写提示词。上传首帧和尾帧时，请描述两者之间发生的动作。':'图片固定形象，视频示范动作，音频提供对白、音色或节奏。上传后即可预览。'}</p>{mode==='fl'&&showShared&&<p className="media-workspace-hint">故事中的人物与地点安排仍保留；其共享参考图在全能参考模式中使用。</p>}</div>
    {mode==='fl'?<><div className="h3-frame-grid"><InputZone project={project} shot={shot} kind="image" role="firstFrame" title="首帧图片" description="从这张画面开始。"/><InputZone project={project} shot={shot} kind="image" role="lastFrame" title="尾帧图片" description="希望最后停在的画面，可留空。"/></div>{referenceCount>0&&<p className="cloud-warning">保留了 {referenceCount} 项全能参考关联。首尾帧模式不能混用；可切换方式，或在下方解除关联。</p>}</>:mode==='ref'?<>{showShared&&<ShotSharedReferences project={project} shot={shot}/>}<div className="h3-reference-grid"><InputZone project={project} shot={shot} kind="image" role="reference" title="图片参考" description="人物、服装、场景、产品或风格。" maximum={maximum('max_images',9)}/><InputZone project={project} shot={shot} kind="video" role="motion" title="视频 / 动作参考" description="动作、运镜或表演示范。上传长片后可在下方选段。" maximum={maximum('max_videos',3)}/><InputZone project={project} shot={shot} kind="audio" role="audio" title="音频参考" description="对白、音色与节奏；与成片的背景音乐分开。" maximum={maximum('max_audios',3)}/></div>{frameCount>0&&<p className="cloud-warning">保留了 {frameCount} 项首尾帧关联。全能参考不接受首尾帧约束；可切换方式，或在下方解除关联。</p>}</>:null}
    {mode&&<details className="h3-time-guides"><summary>指定时间的画面或声音 · 时间锚点</summary><p>需要“第 2 秒出现某张图”或“第 3 秒开始这段声音”时使用。</p><InputZone project={project} shot={shot} title="时间锚点素材" description="上传图片、视频或音频后，在这里直接调整时刻。" maximum={maximum('max_guides',8)} guide/><GuideTiming project={project} shot={shot} recipe={recipe}/></details>}
    <details className="h3-reuse-details"><summary>复用已有素材 / 设置视频音频片段 / 解除关联</summary><ReferenceEditor project={project} shotId={shot.id} onInspect={onInspect}/></details>
    <p className="media-workspace-hint">上传与关联会保存到当前故事。解除关联会保留原文件；切换生成方式也不会删除素材。</p>
  </section>;
}
