import React from 'react';
import {ChevronRight,Clock,Cpu,Info,Pause,Play,Server,ShieldCheck,Square} from 'lucide-react';
import {age,deadlineLabel,nodeDeadline,nodeRemovalConfirmation,dollars,reasonText,stateLabel,stateTone,providerLabel,operatorOfferReadiness,operatorSlotsLabel,roundedSpec,operatorRankReason} from './operator-model.js';
import {uniqueOperatorReasons,historicalNode,operatorNodeStatus,operatorBootstrap} from './operator-presentation.js';

const known=value=>Number.isFinite(value)?value:'—';
const date=value=>typeof value==='number'&&Number.isFinite(value)?new Date(value*1000).toLocaleString('zh-CN'):'尚未记录';
const short=value=>String(value||'尚未确认').slice(0,12);
export function Reasons({items=[]}){const reasons=uniqueOperatorReasons(items);return reasons.length?<ul className="op-reasons">{reasons.map(item=>{const code=typeof item==='string'?item:item.code;return <li key={code}>{reasonText(item)}<code>{code}</code></li>;})}</ul>:null;}
export function Badge({state,stale=false}){return <span className={'op-badge '+(stale?'warn':stateTone(state))}><i/>{stale?'状态待更新':stateLabel(state)}</span>;}
function Status({node,now}){const status=operatorNodeStatus(node,now);return <span className={'op-badge '+status.tone}><i/>{status.label}</span>;}
export function MachineRow({node,profiles=[],now,onOpen,onExtend,disabled=false}){
  const history=historicalNode(node),profile=profiles.find(p=>p.id===node.runtime_profile_id),status=operatorNodeStatus(node,now),deadline=nodeDeadline(node,now);
  return <article className={'op-machine-row'+(history?' historical':'')}>
    <button type="button" className="op-machine-open" aria-label={`查看 ${providerLabel(node.provider)} ${node.gpu_model||'机器'} ${short(node.id)} 详情`} onClick={()=>onOpen(node)}>
      <span className="op-row-icon"><Server size={19}/></span><span className="op-row-title"><b>{node.gpu_model||'机型待核对'} <small>× {known(node.gpu_count)}</small></b><small>{providerLabel(node.provider)} · {short(node.id)} · {node.mode==='fl'?'FL2VA':node.mode==='ref'?'Ref2VA':'模式待核对'}</small><small>{profile?.label||node.runtime_profile_id||'配方尚未绑定'}</small></span>
      <span className="op-row-state"><Status node={node} now={now}/><small>{history?'历史观测':status.label==='状态待核对'?'待核对观测':'最近观测'} · {age(node.observed_at,now)}</small></span>
      <span className="op-row-window"><b>{history?'原期限':deadline.label}</b><small>{history?date(node.hard_deadline):deadlineLabel(deadline.deadline,now)}</small><small>{history?'原费率上限':'整机费率上限'} {dollars(node.hourly_cost_microusd)} / 小时</small></span><ChevronRight size={17}/>
    </button>{!history&&node.actions?.extend&&<button type="button" className="op-row-extend" disabled={disabled} onClick={()=>onExtend(node)}><Clock size={14}/>延长运行</button>}
  </article>;
}
export function NodeCard({node,profiles=[],disabled,onAction,now=Date.now()}){
  const profile=profiles.find(p=>p.id===node.runtime_profile_id),stopDeadline=nodeDeadline(node,now),removal=nodeRemovalConfirmation(node),history=historicalNode(node),bootstrap=operatorBootstrap(node,now);
  const actionReasons=[...(node.actions?.drain?.allowed?[]:node.actions?.drain?.blockers||[]),...(node.actions?.stop?.allowed?[]:node.actions?.stop?.blockers||[])];
  return <article className={'op-node'+(history?' historical':'')}><header><div className="op-node-icon"><Server size={22}/></div><div className="op-node-title"><h3>{node.gpu_model||'机型待核对'} <small>× {known(node.gpu_count)}</small></h3><p>{providerLabel(node.provider)} · {node.id}</p></div><Status node={node} now={now}/></header>
    <div className="op-node-facts"><div><label>{history||removal?'原整机费率上限':node.hourly_cost_basis==='approved_ceiling'?'整机费率上限':'整机费率'}</label><strong>{dollars(node.hourly_cost_microusd)}<small> / 小时</small></strong></div><div><label>{history?'历史停止上限':removal?'原停止上限':stopDeadline.label}</label><strong className="op-small-value">{history||removal?date(node.hard_deadline):deadlineLabel(stopDeadline.deadline,now)}</strong></div><div><label>运行配方</label><strong className="op-small-value">{profile?.label||node.runtime_profile_id||'尚未绑定'}<small> · {node.mode==='fl'?'首尾帧':node.mode==='ref'?'全能参考':'模式未上报'}</small></strong></div></div>
    {history&&<p className="op-note op-history-context">这是保留的历史记录。下方启动、执行槽和原因均为当时的上报；费用是否结清仍以账本为准。</p>}
    {removal&&<div className={'op-banner op-removal '+removal.tone} role="status"><Info size={17}/><div><b>{removal.label}</b><p>{removal.message}</p>{node.provider==='targon'&&removal.pending&&<p>若账户已没有这台机器且未继续扣费，可点击下方「人工审核」暂停此实例的自动核对。</p>}<p>最近实际核对：{date(removal.last_checked_at)} · {age(removal.last_checked_at,now)}</p>{removal.last_checked_at!=null&&<p>{removal.observationText}</p>}<details className="op-details"><summary>删除核对时间</summary><dl><dt>删除请求</dt><dd>{date(removal.requested_at)}</dd><dt>观测记录</dt><dd>{date(removal.last_observation?.observed_at)}</dd>{removal.pending&&<><dt>下次后台核对</dt><dd>{removal.next_check_at==null?'等待后台安排':date(removal.next_check_at)}</dd></>}</dl>{removal.reviewed&&<p>审核账户：{removal.manual_review?.actor||'已记录'} · {date(removal.manual_review?.observed_at)}</p>}<p>删除确认与费用核对分别记录。</p></details></div></div>}
    {node.reason_code&&!removal&&<div className={'op-banner op-removal '+(history?'neutral':'warn')} role="status"><Info size={17}/><div><b>{history?'历史原因 · ':''}{reasonText(node.reason_code)}</b><p>{history?`记录于 ${date(node.observed_at)}；不表示当前仍在运行或失败。`:'保留原机器和任务记录；此状态不表示机器已停止，也不会自动重复启动。'}</p><code>{node.reason_code}</code></div></div>}
    <details className="op-details op-bootstrap" open={!history&&['starting','preparing','blocked','failed','bootstrapping'].includes(node.runtime_state)}><summary>{history?'历史启动观测':'启动准备进度'} · {bootstrap.freshness==='fresh'?'已观测':bootstrap.freshness==='stale'?'观测已过期':'观测时间未知'}</summary><p>{date(bootstrap.observed_at)} · {age(bootstrap.observed_at,now)}{bootstrap.freshness!=='fresh'&&!history?'；保留上次阶段，当前进度待核对。':''}</p>{bootstrap.slots.length?bootstrap.slots.map(slot=><p key={slot.index}><b>执行槽 {slot.index+1}</b> · {slot.label}{slot.error_code&&<> · {reasonText(slot.error_code)}</>}<br/><small>上报阶段 <code>{slot.phase||'unknown'}</code>{slot.failure_phase&&<> · 失败阶段 <code>{slot.failure_phase}</code></>}{slot.error_code&&<> · 原因 <code>{slot.error_code}</code> · 类型 <code>{slot.error_type||'UnknownSetupError'}</code></>}</small></p>):<p>尚未收到启动阶段上报；当前进度未知。</p>}<p>{history?'保留当时启动检查，不表示当前状态。':'阶段来自工作机上报，未推算百分比或剩余时间。是否可接单以当前有效执行槽为准。'}</p></details>
    <div className="op-slots">{history&&node.slots?.length>0&&<p className="op-note">保留的历史执行槽记录</p>}{node.slots?.length?node.slots.map((slot,index)=><div className="op-slot" key={slot.id}><div><Cpu size={15}/><b>执行槽 {index+1}</b>{history||removal?<span className="op-badge neutral">{history?'历史上报':'上次上报'} · {stateLabel(slot.state)}</span>:slot.admission_allowed===false?<span className="op-badge warn"><i/>暂不接单</span>:<Badge state={slot.state} stale={slot.stale}/>}</div><p>{slot.current_job_id?<>{history?'当时任务':removal?'上次上报任务':'任务'} <code>{slot.current_job_id}</code></>:history||removal?'当时未报告任务':'未报告当前任务'} · GPU {(slot.gpu_ids||[]).join('、')||'待核对'}</p><small>{slot.configuration_id||'配置尚未报告'}</small>{!history&&!removal&&slot.admission_allowed===false&&<p className="op-note">暂不接单 · {reasonText(slot.admission_reason_code||'matching_worker_unavailable')}<br/><code>{slot.admission_reason_code||'matching_worker_unavailable'}</code></p>}</div>):<p className="op-note">{history?'未保留执行槽记录。':'执行槽尚未注册。实例开机不等于模型已就绪。'}</p>}</div>
    <details className="op-details"><summary>机器身份与观测</summary><dl><dt>租赁阶段</dt><dd>{node.state==='ready'?'已就绪':stateLabel(node.state)} · {node.state||'未知'}</dd><dt>运行阶段</dt><dd>{node.runtime_state==='ready'?'模型已就绪':stateLabel(node.runtime_state)} · {node.runtime_state||'未上报'}</dd><dt>供应商实例</dt><dd>{node.provider_instance_id||'尚未确认'}</dd><dt>最近观测</dt><dd>{date(node.observed_at)} · {age(node.observed_at,now)}</dd><dt>持久停止上限</dt><dd>{date(node.hard_deadline)}</dd><dt>供应商期限核对</dt><dd>{history?'历史观测':stopDeadline.verified?'已核对安全停止期限':'未核对或观测已过期'} · {date(node.provider_lifetime_observed_at)}</dd><dt>节点版本</dt><dd>{node.version}</dd></dl><p>停止期限是安全上限，不是保活保证；已过期的观测需要重新核对。模型缓存和驻留以工作机上报为准。</p></details>
    <footer><button disabled={disabled||!node.actions?.drain?.allowed} onClick={()=>onAction('drain',node)}><Pause size={14}/>停止接单</button><button disabled={disabled||!node.actions?.stop?.allowed} onClick={()=>onAction('stop',node)}><Square size={13}/>排空后关机</button>{!history&&node.actions?.extend&&<button disabled={disabled} onClick={()=>onAction('extend',node)}><Clock size={14}/>延长运行</button>}{node.provider==='targon'&&removal?.pending&&<button disabled={disabled||!node.actions?.manual_review?.allowed} onClick={()=>onAction('manualReview',node)}><ShieldCheck size={14}/>人工审核</button>}</footer>
    {node.provider==='targon'&&removal?.pending&&!node.actions?.manual_review?.allowed&&<Reasons items={node.actions?.manual_review?.blockers||[]}/>}<Reasons items={actionReasons}/>
  </article>;
}

export function CandidateCard({row,index,current,busy,onStart}){
  const stock=Number.isFinite(row.available_count)&&row.available_count>0,readiness=!stock?(Number.isFinite(row.available_count)?'暂无库存':'库存数量待核对'):operatorOfferReadiness(row),blocked=!!row.blockers?.length||readiness!=='待启动预览';
  return <article className="op-candidate">
    <header><span className="op-candidate-rank">{String(index+1).padStart(2,'0')}</span><div><span className="op-candidate-provider">{providerLabel(row.provider)} · {row.offer_kind==='resource_sku'?'资源规格 SKU':'指定执行机器'}</span><h4>{row.gpu_type} <span>× {known(row.gpu_count)}</span></h4></div><span className={'op-badge '+(current&&readiness==='待启动预览'?'good':'warn')}>{current?readiness:'库存待刷新'}</span></header>
    <div className="op-candidate-price"><strong>{dollars(row.hourly_cost_microusd,{digits:3})}<small> / 小时</small></strong><span>整组 {known(row.gpu_count)} 张 GPU 的报价<br/>每卡 {dollars(row.price_per_gpu_hour_microusd,{digits:3})} / 小时</span></div>
    <dl className="op-candidate-specs"><div><dt>系统内存</dt><dd>{roundedSpec(row.ram_gib,'GiB')}{Number.isFinite(row.allocation_ram_gib)&&row.allocation_ram_gib!==row.ram_gib&&<small>可分配 {roundedSpec(row.allocation_ram_gib,'GiB')}</small>}</dd></div><div><dt>可用磁盘</dt><dd>{roundedSpec(row.disk_gib,'GiB')}</dd></div><div><dt>下载带宽</dt><dd>{roundedSpec(row.download_mbps,'Mbps')}</dd></div><div><dt>当前可用</dt><dd>{known(row.available_count)} {row.offer_kind==='resource_sku'?'份配置':'台'}</dd></div></dl>
    <p className="op-candidate-slots"><Cpu size={13}/>{operatorSlotsLabel(row)}</p>
    <div className="op-rank-reasons">{(row.rank_reasons||[]).map(operatorRankReason).filter(Boolean).map(text=><span key={text}>{text}</span>)}</div>
    <Reasons items={row.blockers||[]}/>{row.preference_hints?.length>0&&<p className="op-note">{row.preference_hints.map(reasonText).join(' ')}</p>}
    <details className="op-details"><summary>{row.offer_kind==='resource_sku'?'资源规格与观测':'机器身份与观测'}</summary><p><code>{row.offer_id}</code></p><p>{row.offer_kind==='resource_sku'?'这是供应商资源规格，创建后才分配具体主机。':'预览绑定此执行器，不会自动换成同型号的其他机器。'}</p><p>观测于 {date(row.observed_at)}{row.country&&` · ${row.country}`}</p></details>
    <footer><span>{!current?'请刷新库存':!stock?readiness:blocked?'启动条件见上方说明':'点击后核对费用并开机'}</span><button className="op-primary" type="button" disabled={busy||!current||!stock||blocked} onClick={()=>onStart(row)}><Play size={13}/>{row.offer_kind==='resource_sku'?'按此规格启动':'启动这台'}</button></footer>
  </article>;
}
