import React,{useEffect,useMemo,useRef,useState,useSyncExternalStore} from 'react';
import {ArrowLeft,ArrowUpRight,Check,Clock3,Cpu,Download,Info,Layers,LogOut,Pause,Play,Plus,RefreshCw,Server,Settings2,ShieldCheck,Square,X} from 'lucide-react';
import {useCloud} from './CloudStudio.jsx';
import {cloudController as cloud} from './cloud-controller.js';
import {createOperatorController} from './operator-controller.js';
import {age,allowed,deadlineLabel,dollars,duration,profileSelection,reasonText,staleSnapshot,stateLabel,stateTone} from './operator-model.js';
import './operator.css';

const quietly=promise=>promise.catch(()=>{});
const known=value=>Number.isFinite(value)?value:'—';
const date=value=>typeof value==='number'?new Date(value*1000).toLocaleString('zh-CN'):'尚未记录';
function Dialog({title,subtitle,onClose,children}){
  const ref=useRef(),opener=useRef(document.activeElement);
  useEffect(()=>{ref.current.showModal();return()=>{ref.current?.close();opener.current?.isConnected&&opener.current.focus();};},[]);
  return <dialog ref={ref} className="op-dialog" aria-label={title} onCancel={e=>{e.preventDefault();onClose();}}><header><div><span className="op-eyebrow">GPU CONTROL</span><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="op-icon" aria-label="关闭面板" onClick={onClose}><X size={19}/></button></header>{children}</dialog>;
}
function Reasons({items=[]}){return items.length?<ul className="op-reasons">{items.map((item,i)=><li key={i}>{reasonText(item)}{item.code&&<code>{item.code}</code>}</li>)}</ul>:null;}
function Badge({state,stale=false}){return <span className={'op-badge '+(stale?'warn':stateTone(state))}><i/>{stale?'状态待更新':stateLabel(state)}</span>;}
function RecipeEvidence({profile}){
  return <details className="op-details"><summary>查看该配方的历史实测与边界</summary><p>来自独立运行实验，单样本、缓存条件未受控；包含任务内加载，不含租机和下载。不能当成当前等待时间或质量保证。</p><div className="op-table-wrap"><table><thead><tr><th>输入方式</th><th>规格</th><th>步数</th><th>任务实测</th></tr></thead><tbody>{(profile.verified_cases||[]).flatMap(row=>(row.measurements||[]).map((m,index)=><tr key={row.id+'-'+index}><td>{row.mode==='fl'?'首尾帧':'全能参考'}<small>{(row.input_roles||[]).join(' · ')}</small></td><td>{row.width} × {row.height}<small>{row.frames} 帧 / {row.fps} fps</small></td><td>{row.steps}</td><td>{duration(m.total_seconds)}<small>{m.measured_at?.slice(0,10)} · n={m.sample_count}</small></td></tr>))}</tbody></table></div>{!profile.verified_cases?.length&&<p>尚无对应实测记录。</p>}{profile.warnings?.map((warning,index)=><p key={index}>{warning}</p>)}<p>模型与配置标识：<code>{profile.id}</code></p></details>;
}
function Login(){
  const c=useCloud(),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');
  return <section className="op-empty op-login"><ShieldCheck size={32}/><h2>登录管理账户</h2><p>使用现有网站账户。是否具有机器管理权限，由服务器确认。</p><form onSubmit={async e=>{e.preventDefault();setError('');try{await cloud.login(username,password);}catch(error){setError(error.message);}}}><label>用户名<input autoComplete="username" required value={username} onChange={e=>setUsername(e.target.value)}/></label>{!['username-only-test','username-test'].includes(c.auth?.authentication)&&<label>密码<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>}{['username-only-test','username-test'].includes(c.auth?.authentication)&&<p className="op-note">当前为本地测试登录。</p>}{error&&<p role="alert" className="op-error">{error}</p>}<button className="op-primary" disabled={c.busy||!c.auth||c.auth.auth_ready===false}>登录控制台</button></form></section>;
}
function NodeCard({node,profiles,disabled,onAction,now}){
  const profile=profiles.find(p=>p.id===node.runtime_profile_id);
  return <article className="op-node"><header><div className="op-node-icon"><Server size={22}/></div><div className="op-node-title"><h3>{node.gpu_model||'机型待核对'} <small>× {known(node.gpu_count)}</small></h3><p>{node.provider==='lium'?'Lium':node.provider||'供应商未知'} · {node.id}</p></div><Badge state={node.runtime_state||node.state} stale={node.stale&&node.state!=='destroyed'}/></header>
    <div className="op-node-facts"><div><label>{node.hourly_cost_basis==='approved_ceiling'?'整机费率上限':'整机费率'}</label><strong>{dollars(node.hourly_cost_microusd)}<small> / 小时</small></strong></div><div><label>原租赁期限</label><strong className="op-small-value">{deadlineLabel(node.hard_deadline,now)}</strong></div><div><label>运行配方</label><strong className="op-small-value">{profile?.label||node.runtime_profile_id||'尚未绑定'}<small> · {node.mode==='fl'?'首尾帧':node.mode==='ref'?'全能参考':'模式未上报'}</small></strong></div></div>
    <div className="op-slots">{node.slots?.length?node.slots.map((slot,index)=><div className="op-slot" key={slot.id}><div><Cpu size={15}/><b>执行槽 {index+1}</b><Badge state={slot.state} stale={slot.stale}/></div><p>{slot.current_job_id?<>任务 <code>{slot.current_job_id}</code></>:'未报告当前任务'} · GPU {(slot.gpu_ids||[]).join('、')||'待核对'}</p><small>{slot.configuration_id||'配置尚未报告'}</small></div>):<p className="op-note">执行槽尚未注册。实例开机不等于模型已就绪。</p>}</div>
    <details className="op-details"><summary>机器身份与观测</summary><dl><dt>租赁阶段</dt><dd>{stateLabel(node.state)} · {node.state||'未知'}</dd><dt>运行阶段</dt><dd>{stateLabel(node.runtime_state)} · {node.runtime_state||'未上报'}</dd><dt>供应商实例</dt><dd>{node.provider_instance_id||'尚未确认'}</dd><dt>最近观测</dt><dd>{date(node.observed_at)} · {age(node.observed_at,now)}</dd><dt>租赁到期</dt><dd>{date(node.hard_deadline)}</dd><dt>节点版本</dt><dd>{node.version}</dd></dl><p>模型缓存、实际驻留与可接单能力以工作机上报为准，未上报的指标不推算。</p></details>
    <footer><button disabled={disabled||!node.actions?.drain?.allowed} onClick={()=>onAction('drain',node)}><Pause size={14}/>停止接单</button><button disabled={disabled||!node.actions?.stop?.allowed} onClick={()=>onAction('stop',node)}><Square size={13}/>排空后关机</button><span>{age(node.observed_at,now)}</span></footer>
    {(!node.actions?.stop?.allowed||!node.actions?.drain?.allowed)&&<Reasons items={[...(node.actions?.drain?.blockers||[]),...(node.actions?.stop?.blockers||[])]}/>}
  </article>;
}
function PolicyDialog({policy,busy,onSave,onClose}){
  const [draft,setDraft]=useState({...policy}),[error,setError]=useState('');
  const fields=[['max_instances','最多机器数','台'],['max_physical_gpus','最多 GPU 数','张'],['idle_shutdown_seconds','空闲后关机','秒'],['max_ttl_seconds','单次租赁最长时间','秒']];
  return <Dialog title="全局运行上限" subtitle="所有人工启动与自动扩容共同遵守这些上限。" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setError('');try{const {version,...values}=draft;await onSave({...values,expected_version:policy.version});onClose();}catch(error){setError(error.message);}}}><label className="op-check"><input type="checkbox" checked={draft.enabled===true} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/>允许容量服务启动新机器</label><p className="op-note">关闭后保留已接受任务和待核对的租赁，不等于强制停止所有机器。</p><div className="op-form-grid">{fields.map(([key,label,unit])=><label key={key}>{label}<div className="op-unit-input"><input type="number" required min={key==='max_ttl_seconds'?120:key==='idle_shutdown_seconds'?1:0} step="1" value={draft[key]??''} onChange={e=>setDraft({...draft,[key]:Number(e.target.value)})}/><span>{unit}</span></div></label>)}<label>全局整机费率上限<div className="op-unit-input"><input type="number" required min="0" step="0.01" value={draft.max_hourly_cost_microusd==null?'':draft.max_hourly_cost_microusd/1e6} onChange={e=>setDraft({...draft,max_hourly_cost_microusd:Math.round(Number(e.target.value)*1e6)})}/><span>USD / 小时</span></div></label></div><p className="op-note">修改不会重置累计费用或延长已有机器 TTL。保存时核对策略版本 {policy.version}。</p>{error&&<p role="alert" className="op-error">{error}</p>}<footer className="op-dialog-actions"><button type="button" onClick={onClose}>取消</button><button className="op-primary" disabled={busy}>保存上限</button></footer></form></Dialog>;
}

function StartDrawer({catalog,policy,controller,busy,onClose}){
  const profiles=catalog?.profiles||[];
  const [selection,setSelection]=useState({runtime_profile_id:'',mode:'fl',gpu_type:'',node_count:1,gpu_count:1,ttl_seconds:Math.min(3600,policy.max_ttl_seconds||3600),filters:{min_ram_gib:0,min_disk_gib:0,min_cpu_cores:12,min_download_mbps:500,max_price_per_gpu_hour_microusd:2000000,allowed_countries:[]}});
  const [customFilters,setCustomFilters]=useState(false),[preview,setPreview]=useState(null),[offers,setOffers]=useState(null),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[now,setNow]=useState(Date.now());
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
  const profile=profiles.find(p=>p.id===selection.runtime_profile_id);
  const hardware=profile?.gpu_models||[];
  const change=patch=>{setSelection(value=>({...value,...patch}));setPreview(null);setOffers(null);setConfirmed(false);setError('');};
  const filter=(key,value)=>change({filters:{...selection.filters,[key]:value}});
  const expired=preview&&preview.expires_at*1000<=now;
  async function inspect(){setError('');try{const result=await controller.preview(customFilters?selection:((({filters,...body})=>body)(selection)));setPreview(result);setSelection(result.selection?{...result.selection,filters:{...selection.filters,...result.selection.filters}}:selection);setConfirmed(false);}catch(error){setError(error.message);}}
  async function start(){setError('');try{await controller.start(preview);onClose();}catch(error){setError(error.message);}}
  return <Dialog title="启动一组机器" subtitle="先选部署配方和硬件，预览当前条件，再确认租赁。" onClose={onClose}><fieldset disabled={busy}><section className="op-step"><span>01</span><div><h3>运行什么模型</h3><label>部署配方<select aria-label="部署配方" value={selection.runtime_profile_id} onChange={e=>change(profileSelection(profiles.find(p=>p.id===e.target.value),selection))} required><option value="">请选择已登记配方</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.label||p.id}</option>)}</select></label><label className="op-mode-field">这组机器运行的模式<select aria-label="机器生成模式" value={selection.mode} onChange={e=>change({mode:e.target.value})}><option value="fl">首尾帧 · FL2VA</option><option value="ref">全能参考 · Ref2VA</option></select></label>{profile&&<div className="op-recipe-note"><b>{profile.label}</b><p>{profile.model_id||profile.id}</p><small>配方身份保持不变；不会自动量化或替换模型。历史实测不代表当前生产执行器已验收。</small><RecipeEvidence profile={profile}/></div>}</div></section>
    <section className="op-step"><span>02</span><div><h3>选择机器</h3><div className="op-form-grid"><label>GPU 型号<select value={selection.gpu_type} onChange={e=>change({gpu_type:e.target.value})} required disabled={!profile}><option value="">请选择 GPU</option>{hardware.map(item=>{const id=typeof item==='string'?item:item.gpu_type||item.id;return <option key={id} value={id}>{typeof item==='string'?item:item.label||id}</option>;})}</select></label><label>每台 GPU 数<select disabled={!profile} value={selection.gpu_count} onChange={e=>change({gpu_count:Number(e.target.value)})}>{(profile?.gpu_count_options||[1]).map(n=><option key={n} value={n}>{n} 张</option>)}</select></label><label>机器数量<input type="number" required min="1" max={policy.max_instances||1} step="1" value={selection.node_count} onChange={e=>change({node_count:Number(e.target.value)})}/></label><label>本次最长运行时间<div className="op-unit-input"><input type="number" required min="2" max={Math.floor((policy.max_ttl_seconds||3600)/60)} value={selection.ttl_seconds/60} onChange={e=>change({ttl_seconds:Number(e.target.value)*60})}/><span>分钟</span></div></label></div><p className="op-note">{selection.node_count} 台机器，共 {selection.node_count*selection.gpu_count} 张 GPU。多张卡在同一台机器上独立运行同一模式，不是独立节点冗余。</p>
    <details className="op-details"><summary>库存过滤条件</summary><p className="op-note">默认采用服务器已配置的条件；预览后返回实际条件。自定义条件须有匹配部署配置才可启动。</p><label className="op-check"><input type="checkbox" checked={customFilters} onChange={e=>{setCustomFilters(e.target.checked);setPreview(null);setConfirmed(false);}}/>指定自定义过滤条件</label><fieldset disabled={!customFilters}><div className="op-form-grid">{[['min_ram_gib','最低系统内存 / GiB'],['min_disk_gib','最低可用磁盘 / GiB'],['min_cpu_cores','最低 CPU 核数'],['min_download_mbps','最低下载带宽 / Mbps']].map(([key,label])=><label key={key}>{label}<input type="number" min="1" step="1" value={selection.filters[key]} onChange={e=>filter(key,Number(e.target.value))}/></label>)}<label>每卡价格上限 / USD·小时<input type="number" min="0.01" step="0.01" value={selection.filters.max_price_per_gpu_hour_microusd/1e6} onChange={e=>filter('max_price_per_gpu_hour_microusd',Math.round(Number(e.target.value)*1e6))}/></label><label>允许地区代码<input placeholder="留空不限制；例如 SG, US" value={selection.filters.allowed_countries.join(', ')} onChange={e=>filter('allowed_countries',e.target.value.toUpperCase().split(',').map(s=>s.trim()).filter(Boolean))}/></label></div></fieldset></details>
    <button type="button" disabled={busy||!selection.runtime_profile_id||!selection.gpu_type} onClick={async()=>{setError('');try{setOffers(await controller.offers(selection));}catch(error){setError(error.message);}}}><RefreshCw size={14}/>只查询库存</button>{offers&&<p className="op-note" role="status">{offers.status==='available'?`当前返回 ${offers.offers?.length||0} 项库存，确认启动前仍会重新核对。`:reasonText(offers.reason_code)} · {age(offers.observed_at)}</p>}</div></section>
    <section className="op-step"><span>03</span><div><h3>核对费用与启动条件</h3><p className="op-note">预览不会租机；模型下载、准备和空闲期间也可能计费。</p><button type="button" disabled={busy||!selection.runtime_profile_id||!selection.gpu_type} onClick={inspect}><Settings2 size={14}/>{busy?'正在核对…':'预览启动'}</button>{preview&&<div className="op-preview"><div><b>{expired?'预览已过期':preview.can_start?'当前条件允许启动':'暂时不能启动'}</b><span className={'op-badge '+(expired||!preview.can_start?'warn':'good')}>{expired?'需重新预览':preview.can_start?'可启动':'未满足'}</span></div><dl><dt>预计整组每小时</dt><dd>{dollars(preview.estimated_hourly_cost_microusd)}</dd><dt>本次预算预留</dt><dd>{dollars(preview.reservation_microusd)}</dd><dt>预览有效至</dt><dd>{date(preview.expires_at)}</dd></dl><Reasons items={preview.blockers}/><p className="op-note">预留不等于最终账单。刷新页面不会创建第二笔租赁。</p>{preview.can_start&&!expired&&<label className="op-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>确认本次数量、期限和费用预留</label>}</div>}</div></section>
    </fieldset>{error&&<p className="op-error" role="alert">{error}</p>}<footer className="op-dialog-actions"><button onClick={onClose}>关闭</button><button className="op-primary" disabled={busy||!confirmed||!preview?.can_start||expired||preview.policy_version!==policy.version} onClick={start}><Play size={15}/>确认启动</button></footer></Dialog>;
}

export default function OperatorConsole(){
  const c=useCloud(),controller=useMemo(()=>createOperatorController(),[]),state=useSyncExternalStore(controller.subscribe,controller.getState,controller.getState),[dialog,setDialog]=useState(null),[actionError,setActionError]=useState(''),[now,setNow]=useState(Date.now());
  useEffect(()=>{document.title='映序 · GPU 控制台';quietly(cloud.initialize());return()=>controller.destroy();},[controller]);
  useEffect(()=>{setDialog(null);setActionError('');void controller.setAccount(c.account);},[c.account,controller]);
  useEffect(()=>{let stopped=false,timer;const tick=async()=>{setNow(Date.now());if(document.visibilityState!=='hidden')try{await controller.poll();}catch{}if(!stopped)timer=setTimeout(tick,5000);};timer=setTimeout(tick,5000);return()=>{stopped=true;clearTimeout(timer);};},[controller,c.account]);
  const snapshot=state.snapshot,stale=staleSnapshot(snapshot,now),profiles=state.catalog?.profiles||state.catalog?.deployment_profiles||[],busy=state.busy||!!state.pending;
  const refresh=()=>quietly(controller.refresh());
  const content=!c.account?<Login/>:state.denied?<section className="op-empty"><ShieldCheck size={32}/><h2>此账户没有机器管理权限</h2><p>仍可返回创作。GPU 租赁权限不会随普通 API Key 自动授予。</p><a href="/quick-chat">返回快速创作 <ArrowUpRight size={14}/></a></section>:!snapshot?<section className="op-empty"><Server size={34}/><h2>{state.loading?'正在读取控制台…':state.unavailable?'当前服务尚未接入控制台':'暂时无法读取机器状态'}</h2><p>没有确认到的状态不会显示为“零台机器”或“已停止”。</p><button onClick={refresh} disabled={state.loading}><RefreshCw size={14}/>重新读取</button></section>:<>
    <div className="op-overview">{[['可用执行槽',snapshot.summary?.slots_ready,'已就绪且能接单'],['运行 / 排队',`${known(snapshot.summary?.jobs_running)} / ${known(snapshot.summary?.jobs_waiting)}`,'现有任务保持原身份'],['机器 / GPU',`${known(snapshot.summary?.nodes_active)} / ${known(snapshot.summary?.gpus_allocated)}`,'主机与物理卡分别统计'],['整机合计费率',dollars(snapshot.summary?.hourly_cost_microusd),snapshot.summary?.hourly_cost_basis==='approved_ceiling_including_pending_commands'?'批准上限 / 小时 · 含待启动预约':'每小时 · 不是最终账单']].map(([label,value,note])=><div key={label}><label>{label}</label><strong>{stale?'—':value??'—'}</strong><small>{stale?'观测已过期，请刷新':note}</small></div>)}</div>
    <div className={'op-controller-line '+(stale||snapshot.controller?.stale?'warn':'')}><span><i/>{snapshot.controller?.stale?'控制器心跳已过期':stateLabel(snapshot.controller?.state)}</span><span>最近心跳：{age(snapshot.controller?.last_heartbeat_at,now)}</span><span>策略：{snapshot.policy?.enabled?'允许启动新容量':'已暂停新容量'}</span><span>空闲 {duration(snapshot.policy?.idle_shutdown_seconds)} 后关机</span></div>
    <section className="op-machine-section"><div className="op-section-heading"><div><span className="op-eyebrow">CAPACITY</span><h2>我的机器 <span>{snapshot.nodes?.length||0}</span></h2><p>已准备好的匹配执行槽会接收 Quick Chat 与 API 的任务。</p></div><button className="op-primary" disabled={busy||!allowed(snapshot,'start',now)} onClick={()=>setDialog({type:'start'})}><Plus size={16}/>启动机器</button></div>
      {snapshot.nodes?.length?<div className="op-node-grid">{snapshot.nodes.map(node=><NodeCard key={node.id} node={node} profiles={profiles} now={now} disabled={busy||stale} onAction={(kind,node)=>{setActionError('');setDialog({type:'action',kind,node});}}/>)}</div>:<div className="op-empty op-machine-empty"><div className="op-machine-art"><Server size={32}/><Cpu size={24}/></div><h3>尚无已登记的机器</h3><p>选一个部署配方，预览配置和费用后启动。<br/>网站和创作内容不依赖 GPU 一直开机。</p></div>}
    </section><section className="op-operations"><div className="op-section-heading"><div><span className="op-eyebrow">ACTIVITY</span><h2>最近管理操作</h2></div><small>以服务器持久记录为准</small></div>{snapshot.operations?.length?<div className="op-table-wrap"><table><thead><tr><th>操作</th><th>状态</th><th>关联机器</th><th>更新时间</th><th>操作标识</th></tr></thead><tbody>{snapshot.operations.map(op=><tr key={op.id}><td>{{start:'启动机器',drain:'停止接单',stop:'排空后关机'}[op.kind]||op.kind}</td><td><Badge state={op.state}/>{op.reason_code&&<small>{reasonText(op.reason_code)} <code>{op.reason_code}</code></small>}</td><td>{op.node_ids?.join('、')||'待绑定'}</td><td>{age(op.updated_at,now)}</td><td><code>{op.id}</code></td></tr>)}</tbody></table></div>:<p className="op-note">尚无管理操作记录。</p>}</section>
  </>;
  return <div className="op-shell"><a className="skip" href="#operator-main">跳到 GPU 控制台</a><aside className="op-sidebar"><a className="op-brand" href="/quick-chat">Ⅱ <b>映序</b><small>STUDIO</small></a><a className="op-back" href="/quick-chat"><ArrowLeft size={15}/>返回创作</a><div className="op-sidebar-label">运营工作区</div><a className="active" href="/operator" aria-current="page"><Server size={17}/>GPU 控制台</a><div className="op-side-note"><ShieldCheck size={17}/><p>一个控制台，共用现有任务与租赁账本。</p></div><div className="op-sidebar-account"><span>{(c.account||'访').slice(0,1).toUpperCase()}</span><div><b>{c.account||'未登录'}</b><small>管理权限由服务器确认</small></div>{c.account&&<button className="op-icon" aria-label="退出登录" onClick={()=>quietly(cloud.logout())}><LogOut size={16}/></button>}</div></aside>
    <main id="operator-main"><header className="op-topbar"><span>工作室 / 计算资源</span><div><span>{snapshot?`更新于 ${age(snapshot.observed_at,now)}`:'等待连接'}</span><button className="op-icon" aria-label="刷新机器状态" disabled={state.loading||!c.account} onClick={refresh}><RefreshCw size={17}/></button></div></header><div className="op-content"><div className="op-page-heading"><div><span className="op-eyebrow">GPU WORKSPACE</span><h1>让算力准备好。</h1><p>配置机器、看清准备进度，让创作接上真实生成。</p></div><button disabled={busy||!allowed(snapshot,'update_policy',now)} onClick={()=>setDialog({type:'policy'})}><Settings2 size={16}/>运行上限</button></div>
      {state.error&&!state.denied&&<div className="op-banner warn" role="alert"><Info size={17}/><span>{state.error}</span></div>}{snapshot&&stale&&<div className="op-banner warn" role="status">当前机器观测已过期，管理操作暂不可用。保留上次记录，等待重新核对。</div>}{state.pending&&<div className="op-banner warn" role="alert"><div><b>原操作结果待核对</b><p>不要重复开机。刷新和核对沿用原操作标识，账户切换也不会删除记录。</p></div><button disabled={state.busy} onClick={()=>quietly(controller.recover())}>核对原操作</button></div>}{content}
      <footer className="op-page-foot"><ShieldCheck size={14}/>启动、排空和停止均写入同一控制服务；浏览器不直连 Lium。</footer></div></main>
    {dialog?.type==='start'&&snapshot&&<StartDrawer catalog={state.catalog} policy={snapshot.policy} controller={controller} busy={busy||!allowed(snapshot,'start',now)} onClose={()=>setDialog(null)}/>}{dialog?.type==='policy'&&snapshot&&<PolicyDialog policy={snapshot.policy} busy={busy||!allowed(snapshot,'update_policy',now)} onClose={()=>setDialog(null)} onSave={body=>controller.updatePolicy(body)}/>}{dialog?.type==='action'&&<Dialog title={dialog.kind==='drain'?'停止接收新任务':'排空后安全关机'} subtitle={dialog.node.gpu_model||dialog.node.id} onClose={()=>setDialog(null)}><p>{dialog.kind==='drain'?'机器将停止接收新任务，继续处理原有任务和结果收集。':'先停止接单，完成任务、结果收集及必要核对后再销毁实例。存在未确认义务时会保持等待。'}</p><p className="op-note">提交意愿不代表机器已关闭。以管理操作和供应商销毁回执为准。</p>{actionError&&<p className="op-error" role="alert">{actionError}</p>}<footer className="op-dialog-actions"><button onClick={()=>setDialog(null)}>取消</button><button className="op-primary" disabled={busy||stale} onClick={async()=>{try{await controller[dialog.kind](dialog.node);setDialog(null);}catch(error){setActionError(error.message);}}}>确认{dialog.kind==='drain'?'停止接单':'排空后关机'}</button></footer></Dialog>}
  </div>;
}
