import React,{useEffect,useState} from 'react';
import {RefreshCw} from 'lucide-react';
import {store} from './store.js';
import {cloudController as cloud} from './cloud-controller.js';
import {useCloud,JobList} from './CloudStudio.jsx';
import {estimateLabel,capacityWaitMessage} from './cloud-model.js';
import {productionRows,filterProductionRows,selectedProductionRows,batchSummary,queueFilters,reviewLabels} from './production-model.js';
import './production-queue.css';

const run=promise=>promise.catch(()=>{});
const issue=item=>typeof item==='string'?item:item?.message||item?.detail||'请进入镜头核对输入。';
export default function ProductionQueue({project,onInspect}){
  const c=useCloud(),[selected,setSelected]=useState([]),[chapterId,setChapterId]=useState(''),[status,setStatus]=useState('all'),[query,setQuery]=useState(''),[confirmed,setConfirmed]=useState('');
  const rows=productionRows(project,c),visible=filterProductionRows(rows,{chapterId,status,query}),chosen=selectedProductionRows(rows,selected),summary=batchSummary(chosen),visibleIds=new Set(visible.map(row=>row.id)),hidden=chosen.filter(row=>!visibleIds.has(row.id)).length;
  const chapterOptions=project.entities.filter(e=>e.type==='chapter').sort((a,b)=>a.order-b.order),ready=chosen.filter(row=>row.canSubmit),submitReady=summary.total>0&&summary.blocked===0&&summary.total<=100;
  const shownJobs=c.jobs.filter(job=>job.recipe_id!=='chapter-roughcut-v1'&&visibleIds.has(job.client_ref?.shot_id));
  useEffect(()=>{setSelected([]);setChapterId('');setStatus('all');setQuery('');setConfirmed('');},[project.id]);
  useEffect(()=>setSelected(ids=>ids.filter(id=>rows.some(row=>row.id===id))),[project.id,rows.length]);
  const changeSelection=next=>{setSelected(next);setConfirmed('');};
  const openReview=id=>{const row=rows.find(r=>r.id===id);if(!row)return;store.setScope(row.chapter.id);store.setSection('journey');store.updateProject({journey:{...store.getState().project.journey,stage:5,reviewShotId:id}});store.select(null);};
  const preflight=()=>{setConfirmed('');run(cloud.prepareBatch(chosen.map(row=>row.id)));};
  return <section className="cloud-production" aria-label="分章制作队列"><div className="cloud-section-head"><h2>制作队列</h2><button disabled={c.busy} onClick={()=>run(cloud.refresh())}><RefreshCw size={14}/>刷新任务</button></div><p>按章节逐批制作。先预检、核对范围与费用，再明确提交；返修只选需要重做的镜头。</p>
    {c.capabilities?.simulation&&<p className="cloud-warning">当前执行 CPU 模拟，产物带水印，不代表 H3 真实效果；模型费用为 $0。</p>}{!c.capabilities?.execution_enabled&&<p className="cloud-warning">当前没有启用生成容量。预检和项目编辑可用，提交保持关闭。</p>}
    {c.activity?<div className="queue-activity" aria-label="项目任务总览"><b>整个项目 {c.activity.total} 个任务</b><span>已完成 {c.activity.counts?.succeeded||0}</span><span>失败 {c.activity.counts?.failed||0}</span><span>等待容量 {c.activity.counts?.waiting_capacity||0}</span><span>排队 {c.activity.counts?.queued||0}</span><span>恢复后待核对 {c.activity.counts?.recovery_hold||0}</span><span>结果待核对 {c.activity.counts?.submission_unknown||0}</span>{c.activity.billing_pending>0&&<span>费用待核对 {c.activity.billing_pending} 项</span>}<small>包括章节粗剪；这是服务端聚合，不受下面章节筛选影响。已载入 {c.jobs.length} 条记录{c.jobs.length<c.activity.total?'，尚未载入全部历史':''}。</small></div>:<p className="muted">{c.activityError||'当前只展示已读取的任务；尚无项目任务总量，不能据此判断全部完成。'}</p>}
    <div className="queue-filters"><label>制作章节<select aria-label="制作章节筛选" value={chapterId} onChange={e=>setChapterId(e.target.value)}><option value="">全部章节</option>{chapterOptions.map(chapter=><option key={chapter.id} value={chapter.id}>{chapter.title}</option>)}</select></label><label>镜头状态<select aria-label="镜头状态筛选" value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(queueFilters).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>查找镜头<input type="search" aria-label="查找制作镜头" placeholder="镜头、场戏或章节名" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
    {(chapterId||status!=='all'||query)&&<button onClick={()=>{setChapterId('');setStatus('all');setQuery('');}}>清除筛选，显示全部镜头</button>}<div className="cloud-actions queue-select"><span role="status">显示 {visible.length} / {rows.length} 镜 · 已选 {chosen.length} 镜</span><button disabled={c.busy||!visible.some(row=>row.canSelect)} onClick={()=>changeSelection([...new Set([...selected,...visible.filter(row=>row.canSelect).map(row=>row.id)])])}>勾选当前可选镜头</button><button disabled={c.busy||!visible.some(row=>selected.includes(row.id))} onClick={()=>changeSelection(selected.filter(id=>!visibleIds.has(id)))}>取消当前可见勾选</button><button disabled={c.busy||!chosen.length} onClick={()=>changeSelection([])}>清空全部勾选</button></div>
    {hidden>0&&<p className="cloud-warning">已选中 {hidden} 镜不在当前筛选内，它们仍在这次预检和提交范围。请核对下方完整清单。<button disabled={c.busy} onClick={()=>changeSelection(selected.filter(id=>visibleIds.has(id)))}>只保留当前可见勾选</button></p>}
    {!visible.length&&<p className="queue-empty">当前筛选没有镜头。调整筛选，或到故事与章节新增镜头；不会自动选中其他章节。</p>}
    <div className="queue-rows">{visible.map(row=><article key={row.id} data-testid={'queue-shot-'+row.id}><div className="queue-row-main"><label><input type="checkbox" aria-label={`勾选镜头 ${row.shot.title}`} disabled={c.busy||!row.canSelect} checked={selected.includes(row.id)} onChange={e=>changeSelection(e.target.checked?[...selected,row.id]:selected.filter(id=>id!==row.id))}/><span><b>{row.shot.title}</b><small>{row.path}</small></span></label><span>{row.label}</span></div><p>v{row.shot.version} · 剪辑 {row.shot.data.seconds} 秒 · {reviewLabels[row.review]}{row.plan?` · ${estimateLabel(row.plan.estimate)}`:''}</p>{row.phase==='waiting_capacity'&&<p className="cloud-warning">{capacityWaitMessage(row.jobs.find(job=>job.status==='waiting_capacity'))}</p>}{row.phase==='recovery_hold'&&<p className="cloud-warning">服务恢复后暂停核对原任务。可以继续改稿；在管理员核对执行与费用前，不提供重新提交。</p>}{row.error&&<p role="alert" className="cloud-error">上次预检：{row.error} 修改后请重新预检。</p>}{row.current&&row.plan?.blockers?.map((item,i)=><p key={i} className="cloud-error">{issue(item)}</p>)}<div className="cloud-actions"><button onClick={()=>onInspect(row.id)}>{['failed','error','blocked','stale','expired'].includes(row.phase)?'定位这一镜并返修':'配置这一镜'}</button><button onClick={()=>openReview(row.id)}>审核这一镜</button>{c.unknown?.[row.id]&&<button disabled={c.busy} onClick={()=>run(cloud.submit(row.id))}>用原标识核对提交</button>}</div></article>)}</div>
    {c.batchChecking?.projectId===project.id&&<p role="status">正在预检 {rows.find(row=>row.id===c.batchChecking.shotId)?.shot.title||'镜头'} · 已检查 {c.batchChecking.completed} / {c.batchChecking.total} 镜。尚未提交生成。</p>}
    {chosen.length>0&&<section className="queue-summary" aria-label="本次批量范围"><h3>本次明确选择的 {summary.total} 镜</h3><p>可提交 {summary.ready} 镜 · 仍需处理 {summary.blocked} 镜。最多一次提交 100 镜，运行中和待核对提交的镜头不会重新排入。</p><ol>{chosen.map(row=><li key={row.id}><span><b>{row.shot.title}</b><small>{row.path} · {row.label}</small></span><button onClick={()=>onInspect(row.id)}>检查</button></li>)}</ol><div className="cloud-actions"><button disabled={c.busy||!chosen.length||chosen.some(row=>!row.canSelect)} onClick={preflight}>1. 预检已选 {chosen.length} 镜</button>{summary.blocked>0&&ready.length>0&&<button disabled={c.busy} onClick={()=>changeSelection(ready.map(row=>row.id))}>只保留预检通过的 {ready.length} 镜</button>}</div>
      {summary.estimates.map((estimate,i)=><p key={i}>{estimateLabel(estimate)}</p>)}{summary.unknown>0&&<p className="cloud-warning">{summary.unknown} 个可提交镜头的费用仍未知，不能据此当作免费。</p>}
      {summary.waitingCapacity>0&&<p className="cloud-warning">其中 {summary.waitingCapacity} 镜获准进入容量等待队列，但没有已验收的执行槽；确认后沿用原任务等待，不代表立即可运行。审批或预算仍须符合服务限制。</p>}<label className="queue-confirm"><input type="checkbox" disabled={c.busy||!submitReady} checked={submitReady&&confirmed===summary.signature} onChange={e=>setConfirmed(e.target.checked?summary.signature:'')}/>我已核对以上镜头范围、预检状态和费用说明</label><button className="primary" disabled={c.busy||!submitReady||confirmed!==summary.signature||!c.capabilities?.execution_enabled||!!c.batchPending} onClick={()=>run(cloud.submitBatch(chosen.map(row=>row.id)).then(()=>changeSelection([])))}>2. 明确提交这 {chosen.length} 镜</button><p>预检、筛选和审核不会自动提交。改稿、改勾选、计划失效后，需要重新核对。</p>
    </section>}
    {c.batchPending&&<div className="cloud-warning" role="alert"><p>{c.busy?'正在确认本次批次提交，请稍候。':`有 ${c.batchPending.shotIds.length} 镜的批次提交结果未确认。即使筛选改变，恢复也只核对原批次。`}</p><button disabled={c.busy} onClick={()=>run(cloud.recoverBatch())}>恢复未确认批次</button></div>}
    <details className="queue-batches"><summary>最近载入的批次（{c.batches.length}）</summary>{c.batches.map(batch=><article key={batch.id}><b>{({active:'排队或执行中',admitting:'正在确认镜头',completed:'全部完成',finished_with_issues:'部分需要处理',cancel_requested:'正在取消',blocked:'等待执行条件'}[batch.status])||batch.status}</b><small>批次 {batch.id}</small>{batch.items?.filter(item=>item.error_code).map(item=>{const row=rows.find(row=>row.plan?.plan_id===item.plan_id||row.jobs.some(job=>job.plan_id===item.plan_id));return <div key={item.plan_id}><p className="cloud-error">{row?.shot.title||'历史镜头'}未入队；原输入保留，请核对原因后单独重检。</p><details><summary>查看服务原因</summary><code>{item.error_code}</code></details>{row&&<button onClick={()=>onInspect(row.id)}>定位未入队镜头</button>}</div>;})}{['active','admitting','cancel_requested'].includes(batch.status)&&<button disabled={c.busy} onClick={()=>run(cloud.cancelBatch(batch.id))}>请求取消此批次未完成项</button>}</article>)}{c.moreBatches&&<div className="queue-history"><button disabled={c.busy} onClick={()=>run(cloud.loadMoreBatches())}>加载更早的 10 个批次</button><p>仅列出已载入批次，历史状态以最近读取为准；新批次进入时分页可能重叠，刷新最新记录会保留已载历史。</p></div>}</details>
    <h3>当前筛选镜头的任务记录</h3><p>旧版本与失败记录保留。完成后逐镜审核，不会自动采用候选。</p><JobList jobs={shownJobs} project={project} onInspect={onInspect} onReview={openReview}/>{!shownJobs.length&&<p className="muted">已载入的记录中，当前筛选没有匹配任务。</p>}{c.moreJobs&&<div className="queue-history"><button disabled={c.busy} onClick={()=>run(cloud.loadMoreJobs())}>加载更早的 100 条任务</button><p>新任务进入时分页可能重叠，系统按任务编号去重；刷新最新记录会保留已载入的历史。未载入的任务仍可能在运行。</p></div>}
  </section>;
}
