import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Bot,Copy,RefreshCw,KeyRound} from 'lucide-react';
import {ChatDialog} from './QuickChatControls.jsx';
import ApiKeys from './ApiKeys.jsx';
import {createQuickChatClient} from './quick-chat-client.js';
const date=value=>value?new Date(typeof value==='number'?value*1000:value).toLocaleString():'未知';
const scopeNames={'projects:read':'查看创作','projects:create':'新建创作','projects:write':'编辑创作','assets:read':'查看与下载素材','assets:write':'上传素材','jobs:read':'查看任务与结果','jobs:write':'提交视频生成','assistant:run':'调用文本助手'};
const pendingName=account=>`yingxu:agent-connection-intent:${account}`;
function readIntent(account){try{const value=JSON.parse(globalThis.localStorage?.getItem(pendingName(account))||'null');return value&&typeof value.key==='string'&&value.body?.authorization_profile_id?value:null;}catch{return {corrupt:true};}}
export default function QuickChatAgent({account,sessionId,onClose,onLogin}){
  const client=useMemo(()=>{const api=createQuickChatClient();api.setAccount(account);return api;},[account]),[connections,setConnections]=useState([]),[profile,setProfile]=useState(null),[created,setCreated]=useState(null),[name,setName]=useState('我的 Codex'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[manual,setManual]=useState(false),live=useRef(false),epoch=useRef(0),pending=useRef(null),action=useRef(false),refreshSequence=useRef(0);
  const origin=globalThis.location?.origin||'',codeAvailable=!!created?.code&&created.connection.expires_at*1000>Date.now(),authorization=codeAvailable?created.connection.authorization:null,grant=authorization||profile,instructions=codeAvailable?[
    '请连接映序，使用公开 Skill 与 API 帮助我创作。',`先阅读：${origin}/for-agents/SKILL.md`,
    `本次网站：${origin}`,`连接 ID：${created.connection.id}`,`授权账户：${authorization.owner}`,`租户：${authorization.tenant}`,
    `授权 profile：${authorization.profile_id}`,`授权 profile 版本：${authorization.profile_version}`,
    `授权指纹：${created.connection.authorization_fingerprint}`,
    `一次性连接码：${created.code}`,`连接码到期：${date(created.connection.expires_at)}`,`授权到期：${date(authorization.key_expires_at)}`,
    ...(sessionId?[`工作位置：${origin}/quick-chat?session=${encodeURIComponent(sessionId)}`]:[]),
    '使用公开连接 helper 在我的本地 OS 安全凭据库保存你自己生成的正式 Key，再兑换此连接码；生产使用 TLS，本地仅 loopback HTTP 例外。不要打印正式 Key、连接码或 verifier；不要写进 URL、普通 JSON 或日志。',
    '这是本人现有和未来内容的创作、上传、视频生成及助手调用授权，不含账户、预算或基础设施管理。按我的创作要求操作；生成前预检，未知结果核对原记录，不重复提交。',
    '把结果保存到同一会话，并返回网页工作链接。',
  ].join('\n'):'';
  async function refresh(){const generation=epoch.current,sequence=++refreshSequence.current,result=await client.connections();if(live.current&&generation===epoch.current&&sequence===refreshSequence.current){setConnections(result.connections||[]);setProfile(result.authorization_profile||null);setCreated(current=>{if(!current)return null;const latest=result.connections?.find(item=>item.id===current.connection.id);return current.connection.expires_at*1000<=Date.now()||latest&&latest.status!=='pending'?null:current;});}return result;}
  useEffect(()=>{live.current=true;epoch.current++;action.current=false;setCreated(null);setConnections([]);setProfile(null);setError('');setNotice('');setBusy(false);setManual(false);pending.current=account?readIntent(account):null;const generation=epoch.current;if(account){refresh().catch(()=>live.current&&generation===epoch.current&&setError('连接列表尚未读取，请重试。'));let timer;const poll=async()=>{try{await refresh();}catch{}if(live.current&&generation===epoch.current)timer=setTimeout(poll,5000);};timer=setTimeout(poll,5000);return()=>{live.current=false;epoch.current++;clearTimeout(timer);client.reset();};}return()=>{live.current=false;epoch.current++;client.reset();};},[client,account]);
  async function issue(){if(!account){onLogin();return;}if(!profile||action.current||codeAvailable)return;if(pending.current?.corrupt){setError('原发码操作标识无法读取。请先核对并撤销未连接授权，再处理原记录；没有重复发码。');return;}const generation=epoch.current;action.current=true;setBusy(true);setError('');setNotice('');try{
    // Issue metadata can be recovered, but a lost secret code is never replayed.
    const intent=pending.current||{key:'connect-'+crypto.randomUUID(),body:{name:name.trim(),authorization_profile_id:profile.id,authorization_profile_version:profile.version}};
    // Persist only the operation ID and public grant profile. Neither the
    // short-lived code nor a formal API key is ever put into storage.
    try{if(!globalThis.localStorage)throw Error();globalThis.localStorage.setItem(pendingName(account),JSON.stringify(intent));}catch{throw Error('无法保存发码操作标识，未申请新码。请启用浏览器存储。');}pending.current=intent;
    const result=await client.createConnection(intent.body,intent.key);if(!live.current||generation!==epoch.current)return;globalThis.localStorage.removeItem(pendingName(account));pending.current=null;setCreated(result.code?result:null);setNotice(result.code?'连接码只在当前窗口保留，请在到期前复制给 Codex。':'原授权已找到，连接码不再回显。请核对原连接状态，需要新码时先撤销未连接授权。');await refresh();
  }catch(err){if(live.current&&generation===epoch.current){if(err.status>=400&&err.status<500&&![408,429].includes(err.status)){globalThis.localStorage?.removeItem(pendingName(account));pending.current=null;setError('发码请求已拒绝，请刷新固定授权范围后重试。');}else setError(pending.current?'发码结果未确认。请点击“核对原发码”恢复同一授权，不要重复创建。':err.message);}}finally{if(live.current&&generation===epoch.current){action.current=false;setBusy(false);}}}
  async function copy(){if(!codeAvailable){setCreated(null);setNotice('此码已过期，请生成新的连接说明。');return;}const generation=epoch.current;try{await navigator.clipboard.writeText(instructions);if(live.current&&generation===epoch.current)setNotice('已复制说明。把它发给你信任的 Codex，然后在这里查看连接状态。');}catch{if(live.current&&generation===epoch.current)setNotice('自动复制未获允许，请选中下方说明手动复制。');}}
  async function revoke(connection){if(action.current||!window.confirm(`撤销 ${connection.name}？已接受任务仍保留，Agent 后续调用会被拒绝。`))return;const generation=epoch.current;action.current=true;setBusy(true);setError('');try{await client.revokeConnection(connection.id,'revoke-'+connection.id);if(!live.current||generation!==epoch.current)return;if(created?.connection.id===connection.id)setCreated(null);await refresh();setNotice('连接已撤销，原任务与作品保留。');}catch{if(live.current&&generation===epoch.current)setError('撤销结果待核对，请刷新原连接状态。');}finally{if(live.current&&generation===epoch.current){action.current=false;setBusy(false);}}}
  return <ChatDialog title="连接 Codex" onClose={onClose} wide><section className="qc-agent-intro"><Bot size={32}/><div><h3>把工作交给 AI，过程留在这里。</h3><p>生成连接说明 → 复制给 Codex → 回到这里查看连接与创作结果。</p></div></section>{!account?<button className="qc-primary" onClick={onLogin}>登录后连接 Codex</button>:<><div className="qc-agent-grant"><b>当前账户：{authorization?.owner||account}</b><p>{authorization?(authorization.all_projects?'本人现有和未来项目':`本人 ${authorization.project_ids.length} 个指定项目`):profile?.description||'正在读取固定授权范围…'}</p>{grant&&<p>{grant.scopes.map(scope=>scopeNames[scope]||scope).join(' · ')}<br/><small>授权有效期 {grant.key_lifetime_days} 天；连接码 {profile?.code_ttl_seconds?Math.floor(profile.code_ttl_seconds/60):5} 分钟内使用，仅可兑换一次。</small></p>}<small>文本调用和视频生成可能消费额度，仍受服务能力、额度及预检限制。不授予账户、预算或基础设施管理权限；正式 Key 由 Agent 在本地安全保存。</small></div>{!codeAvailable&&<><label className="qc-field">连接名称<input value={name} disabled={busy} onChange={e=>setName(e.target.value)} maxLength={80}/></label><button className="qc-primary" disabled={busy||!profile||!name.trim()} onClick={issue}>{busy?'正在核对…':pending.current?'核对原发码':'生成连接说明'}</button></>}{codeAvailable&&<section className="qc-created-code"><b>连接说明已生成 · {date(created.connection.expires_at)} 到期</b><textarea rows={10} readOnly aria-label="给 Codex 的一次性连接说明" value={instructions} spellCheck={false}/><button disabled={busy} onClick={copy}><Copy size={15}/>复制连接说明</button><button onClick={()=>setCreated(null)}>收起连接码</button><small>说明含一次性凭据，只交给你信任的 Agent。连接成功后这里自动收起；关闭窗口后无法重新显示。</small></section>}<div className="qc-section-heading"><h3>连接状态</h3><button disabled={busy} onClick={()=>refresh().catch(()=>setError('列表刷新失败。'))}><RefreshCw size={14}/>刷新</button></div><div className="qc-connection-list">{connections.map(connection=><article key={connection.id}><div><b>{connection.name}</b><span className="qc-badge">{({pending:'待连接 Codex',connected:'已连接 Codex',expired:'已过期',revoked:'已撤销',unavailable:'需重新授权'})[connection.status]||connection.status}</span><small>{connection.key?`授权到期：${date(connection.key.expires_at)}`:`连接码到期：${date(connection.expires_at)}`}{connection.key?.last_used_at?` · 最近使用：${date(connection.key.last_used_at)}`:''}</small></div>{!['revoked','expired'].includes(connection.status)&&<button disabled={busy} onClick={()=>revoke(connection)}>撤销</button>}</article>)}{!connections.length&&<p className="qc-muted">尚无连接。生成说明后，把它交给 Codex 即可。</p>}</div><details open={manual} onToggle={e=>setManual(e.currentTarget.open)}><summary><KeyRound size={14}/>手动 API Key · 高级备用</summary>{manual&&<ApiKeys account={account}/>}</details></>}{error&&<p className="qc-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<p className="qc-muted"><a href="/for-agents" target="_blank" rel="noreferrer">公开 Agent 使用说明 ↗</a> · <a href="/v1/agent-skill.zip" download>下载 Skill</a></p></ChatDialog>;
}
