import React,{useEffect,useMemo,useRef,useState,useSyncExternalStore} from 'react';
import {Plus,ArrowUp,Settings2,Bot,Menu,X,RefreshCw,LogOut,Upload,Image,Video,Music} from 'lucide-react';
import {useCloud} from './CloudStudio.jsx';
import {cloudController as cloud} from './cloud-controller.js';
import {createQuickChatController,saveMaterialSelection} from './quick-chat-controller.js';
import {CHAT_MODELS,defaultsFor,nextSettingsFor,recipeFor,clone,bindingPayload,bindingParticipates,bindingProblems,bindingsForInputs,mergeTimelineTurns,sessionHref,safeSessionId,effectiveLimits,displaySeconds,effectiveControlSchema,hasOriginalAudio,isInternalDerivedInventory} from './quick-chat-model.js';
import QuickChatControls,{ChatDialog} from './QuickChatControls.jsx';
import QuickChatMaterials from './QuickChatMaterials.jsx';
import QuickChatCard from './QuickChatCard.jsx';
import QuickChatAgent from './QuickChatAgent.jsx';
import OperatorEntry from './OperatorEntry.jsx';
import {DeploymentProfileSelect} from './DeploymentProfile.jsx';
import './quick-chat.css';
const quietly=promise=>promise.catch(()=>{}),date=value=>value?new Date(typeof value==='number'?value*1000:value).toLocaleString():'';
const draftKey=(account,id)=>`yingxu:quick-chat:draft:${account||'anonymous'}:${id||'new'}`;
function readDraft(account,id){try{return localStorage.getItem(draftKey(account,id))||'';}catch{return '';}}
function saveDraft(account,id,text){try{localStorage.setItem(draftKey(account,id),text);return true;}catch{return false;}}
const modeKey=(account,id)=>`yingxu:quick-chat:mode:${account||'anonymous'}:${id||'new'}`;
function readMode(account,id,fallback='auto'){try{const value=localStorage.getItem(modeKey(account,id));return ['auto','fl','ref'].includes(value)?value:fallback;}catch{return fallback;}}
function saveMode(account,id,value){try{localStorage.setItem(modeKey(account,id),value);}catch{}}
const hiddenKey=(account,id)=>`yingxu:quick-chat:hidden-materials:${account||'anonymous'}:${id||'new'}`;
function readHidden(account,id){try{const value=JSON.parse(localStorage.getItem(hiddenKey(account,id))||'[]');return Array.isArray(value)?value.filter(item=>typeof item==='string'):[];}catch{return [];}}
function automaticMode(bindings){return bindings.some(binding=>binding.enabled!==false&&['first_frame','last_frame'].includes(binding.slot))?'fl':bindings.some(binding=>binding.enabled!==false&&['images','videos','audios'].includes(binding.slot))?'ref':'fl';}
function settingsForMode(capabilities,current,mode){const next=capabilities?.recipes?.find(item=>item.mode===mode);if(!next)throw Error('当前服务未公开这种生成方式。');return {...current,recipe_id:next.id,controls:{...defaultsFor(capabilities,next.id,current.deployment_profile_id).controls,...current.controls}};}
function Login({onClose,onDone}){
  const c=useCloud(),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');
  return <ChatDialog title={c.account?'我的账户':'登录后保存这次创作'} onClose={onClose}>{c.account?<><p>当前账户：<b>{c.account}</b></p><p>云端会话、素材和任务按账户隔离。退出不取消已接受任务。</p><button onClick={()=>quietly(cloud.logout().then(onClose))}><LogOut size={14}/>退出登录</button></>:<form onSubmit={async e=>{e.preventDefault();setError('');try{await cloud.login(username,password);onDone();}catch(err){setError(err.message);}}}><p>先选的文件仍是本地待上传；登录后将保存到新创作，原故事不受影响。</p><label className="qc-field">用户名<input autoComplete="username" required maxLength={100} value={username} onChange={e=>setUsername(e.target.value)}/></label>{!['username-test','username-only-test'].includes(c.auth?.authentication)&&<label className="qc-field">密码<input type="password" autoComplete="current-password" required maxLength={72} value={password} onChange={e=>setPassword(e.target.value)}/></label>}{['username-test','username-only-test'].includes(c.auth?.authentication)&&<p className="qc-warning">本地隔离测试登录，不代表公网认证方式。</p>}{error&&<p className="qc-error" role="alert">{error}</p>}<button className="qc-primary" disabled={c.busy||!c.auth||c.auth.auth_ready===false}>登录并继续</button>{!c.auth&&<button type="button" onClick={()=>quietly(cloud.initialize())}>重新检查连接</button>}</form>}</ChatDialog>;
}
export default function QuickChatWorkspace(){
  const c=useCloud(),controller=useMemo(()=>createQuickChatController(),[]),state=useSyncExternalStore(controller.subscribe,controller.getState,controller.getState),[prompt,setPrompt]=useState(()=>readDraft(null,null)),[dialog,setDialog]=useState(null),[rename,setRename]=useState(''),[mobile,setMobile]=useState(false),[staged,setStaged]=useState([]),[localError,setLocalError]=useState(''),[notice,setNotice]=useState(''),[draftSettings,setDraftSettings]=useState(null),[model,setModel]=useState('gemini-3.8-flash'),[assistantMode,setAssistantMode]=useState('assist'),[modeIntent,setModeIntent]=useState(()=>readMode(null,null)),[confirmation,setConfirmation]=useState(null),[dragging,setDragging]=useState(false),[submitting,setSubmitting]=useState(false),input=useRef(),textarea=useRef(),mainRef=useRef(),composerRef=useRef(),uploading=useRef(false),alive=useRef(true),lastAccount=useRef(null),lastDraft=useRef({account:null,id:null}),lastSelected=useRef(null),carryDraft=useRef(false),needsFileReconfirm=useRef(false),stagedRef=useRef([]),textRef=useRef(prompt),confirmationRef=useRef(null),modeRef=useRef(modeIntent),materialOperation=useRef(false);
  const [hiddenAssetIds,setHiddenAssetIds]=useState([]),[toast,setToast]=useState(''),[renameError,setRenameError]=useState(''),controlsSnapshot=useRef(null),renameSnapshot=useRef(null);
  const newSettings=nextSettingsFor(state.capabilities,state.schema);
  const settings=nextSettingsFor(state.capabilities,state.schema,{draft:draftSettings,session:state.session?.next_settings}),recipe=recipeFor(state.capabilities,settings),limits=effectiveLimits(recipe),turns=mergeTimelineTurns(state.timeline),allCards=Object.values(state.cards),busy=state.busy||submitting,modelSchema=(state.schema?.models||state.schema?.assistant?.models||[]).find(item=>item.id===model),assistantEnabled=state.schema?.assistant_enabled===true&&modelSchema?.inputs?.text?.enabled===true;
  useEffect(()=>{alive.current=true;cloud.initialize();const stop=cloud.startPolling();document.title='映序 · 开始创作';return()=>{alive.current=false;confirmationRef.current?.resolve(false);stop();controller.destroy();for(const item of stagedRef.current)URL.revokeObjectURL(item.url);};},[controller]);
  useEffect(()=>{let active=true;const previous=lastAccount.current;lastAccount.current=c.account;const wasAnonymous=previous===null;const previousText=textRef.current;saveDraft(previous,lastDraft.current.id,previousText);if(previous&&previous!==c.account){setStaged([]);for(const item of stagedRef.current)URL.revokeObjectURL(item.url);needsFileReconfirm.current=false;setPrompt(readDraft(c.account,null));setDraftSettings(null);setNotice('账户已切换，旧会话和响应未加入新账户。原账户草稿仍按账户保存。');}else if(wasAnonymous&&c.account){needsFileReconfirm.current=stagedRef.current.length>0;setNotice(stagedRef.current.length?'待上传文件还在本地。请确认要保存到当前账户后继续。':'已登录，可以直接开始创作。');}
    controller.setAccount(c.account).then(async()=>{if(!active||!c.account)return;const query=new URLSearchParams(window.location.search),requested=safeSessionId(query.get('session'));if(requested){try{await controller.open(requested,{revisionId:safeSessionId(query.get('revision')),cardId:safeSessionId(query.get('card')),submissionId:safeSessionId(query.get('submission'))});}catch{}}});return()=>{active=false;};},[c.account,controller]);
  useEffect(()=>{if(!globalThis.ResizeObserver)return;const observer=new ResizeObserver(()=>mainRef.current?.style.setProperty('--qc-compose-height',`${composerRef.current?.offsetHeight||0}px`));if(composerRef.current)observer.observe(composerRef.current);return()=>observer.disconnect();},[]);
  useEffect(()=>{stagedRef.current=staged;},[staged]);useEffect(()=>{textRef.current=prompt;},[prompt]);
  useEffect(()=>{modeRef.current=modeIntent;},[modeIntent]);
  useEffect(()=>{const session=state.session,stored=readMode(c.account,session?.id,session?recipeFor(state.capabilities,session.next_settings)?.mode||'auto':'auto');setModeIntent(stored);modeRef.current=stored;confirmationRef.current?.resolve(false);confirmationRef.current=null;setConfirmation(null);},[c.account,state.session?.id]);
  useEffect(()=>{setHiddenAssetIds(readHidden(c.account,state.session?.id));},[c.account,state.session?.id]);
  useEffect(()=>{const value=notice||state.notice;setToast(value);if(!value)return;const timer=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(timer);},[notice,state.notice]);
  useEffect(()=>{const id=state.session?.id,old=lastDraft.current;if(old.id!==id||old.account!==c.account){const keepAnonymous=old.account===null&&!!c.account&&old.id===null&&!!textRef.current;if(keepAnonymous){carryDraft.current=true;saveDraft(c.account,id,textRef.current);try{localStorage.removeItem(draftKey(null,null));}catch{}}else saveDraft(old.account,old.id,textRef.current);lastDraft.current={account:c.account,id:id||null};if(!keepAnonymous&&!(old.id===null&&id&&carryDraft.current&&textRef.current)){setPrompt(readDraft(c.account,id));}if(id&&old.id===null&&carryDraft.current){saveDraft(c.account,id,textRef.current);try{localStorage.removeItem(draftKey(c.account,null));}catch{}carryDraft.current=false;}setDraftSettings(null);if(state.session?.model_id)setModel(state.session.model_id);}},[c.account,state.session?.id]);
  useEffect(()=>{if(state.session?.id&&lastSelected.current!==state.session.id){lastSelected.current=state.session.id;const query=new URLSearchParams(window.location.search);window.history.replaceState(null,'',query.get('session')===state.session.id?window.location.pathname+window.location.search:sessionHref(state.session.id));}},[state.session?.id]);
  useEffect(()=>{let stopped=false,timer,delay=5000;const tick=async()=>{if(stopped)return;if(document.visibilityState==='hidden'){timer=setTimeout(tick,15000);return;}try{await controller.poll();delay=5000;}catch{delay=Math.min(delay*2,30000);}if(!stopped)timer=setTimeout(tick,delay);};timer=setTimeout(tick,delay);return()=>{stopped=true;clearTimeout(timer);};},[controller,c.account,state.session?.id]);
  useEffect(()=>{const warn=e=>{if(stagedRef.current.length||uploading.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
  const act=async fn=>{setLocalError('');setNotice('');try{return await fn();}catch(err){if(alive.current)setLocalError(err.message||'操作未完成。');}};
  function changePrompt(value,target={account:c.account,id:state.session?.id}){textRef.current=value;setPrompt(value);if(!saveDraft(target.account,target.id,value))setLocalError('输入草稿目前只在页面内存，请先复制保存；刷新可能丢失未发送文字。');}
  async function ensureSession(){if(!c.account){setDialog('login');throw Error('请先登录，待上传文件与文字仍保留。');}if(!state.session?.id){const intent=modeRef.current,next=clone(settings);carryDraft.current=true;const session=await controller.create({model_id:model,title:prompt.trim().slice(0,40)||'新的创作'});saveMode(c.account,session.id,intent);setModeIntent(intent);modeRef.current=intent;if(next.recipe_id&&JSON.stringify(next)!==JSON.stringify(session.next_settings))await controller.patch({next_settings:next});return controller.getState().session;}return state.session;}
  function ask(message,{title='请确认',label='确认并继续'}={}){return new Promise(resolve=>{confirmationRef.current?.resolve(false);const value={message,title,label,resolve};confirmationRef.current=value;setConfirmation(value);});}
  function finishConfirmation(accepted){const value=confirmationRef.current;confirmationRef.current=null;setConfirmation(null);value?.resolve(accepted);}
  function chooseMode(value){setModeIntent(value);modeRef.current=value;saveMode(c.account,controller.getState().session?.id,value);}
  function captureEditor(){const live=controller.getState();if(live.account!==c.account)throw Error('正在切换账户，请连接稳定后再编辑。');return {account:live.account,sessionId:live.session?.id||null,version:live.session?.version??null};}
  function assertEditor(snapshot){const live=controller.getState();if(!snapshot||snapshot.account!==c.account||snapshot.account!==live.account)throw Error('账户已改变，未保存到其他账户。编辑草稿保留，请返回原账户后核对。');if(snapshot.sessionId!==(live.session?.id||null))throw Error('创作已改变，未保存到其他创作。编辑草稿保留，请返回原创作后核对。');if(snapshot.sessionId&&snapshot.version!==live.session.version)throw Error('这次创作已被其他窗口或 Agent 更新。未覆盖新版本，编辑草稿保留；请核对后重新打开。');return live;}
  function openControls(){act(()=>{controlsSnapshot.current={...captureEditor(),settings:clone(settings),capabilities:state.capabilities,bindings:clone(state.materials),modeIntent};setDialog('controls');});}
  function openRename(){act(()=>{const snapshot=captureEditor();if(!snapshot.sessionId)throw Error('请先选择一条创作。');renameSnapshot.current=snapshot;setRename(state.session.title);setRenameError('');setDialog('rename');});}
  async function saveNextControls(value,_prompt,meta){const snapshot=controlsSnapshot.current;assertEditor(snapshot);if(snapshot.sessionId)await controller.patch({expected_version:snapshot.version,next_settings:value});else setDraftSettings(value);chooseMode(meta?.modeIntent||recipeFor(snapshot.capabilities,value)?.mode||'auto');setNotice('下一轮设置已保存，不影响历史卡片。');}
  async function saveRename(){setRenameError('');try{const snapshot=renameSnapshot.current;assertEditor(snapshot);await controller.patch({expected_version:snapshot.version,title:rename.trim()});setDialog(null);}catch(error){setRenameError(error.message||'名称未保存，编辑文字仍保留。');}}
  function hideAsset(id,hidden){setHiddenAssetIds(current=>{const next=hidden?[...new Set([...current,id])]:current.filter(value=>value!==id);try{localStorage.setItem(hiddenKey(c.account,controller.getState().session?.id),JSON.stringify(next));}catch{setLocalError('隐藏选择只在当前页面；刷新后原素材会重新出现。');}return next;});}
  async function removeMaterial(binding){if(binding.version===0){hideAsset(binding.asset_id,true);setNotice('已从本轮隐藏，云端原件仍保留。');return;}return act(()=>updateMaterials(controller.getState().materials.map(item=>({...bindingPayload(item),...(item.asset_id===binding.asset_id?{enabled:false}:{})}))));}
  async function selectSession(id){if(staged.length&&!await ask('待上传文件尚未存云端。切换后仍留在本地，上传前会再次确认目标创作。',{title:'切换创作？',label:'切换并保留本地文件'}))return;if(staged.length)needsFileReconfirm.current=true;saveDraft(c.account,state.session?.id,prompt);await act(()=>controller.open(id));setMobile(false);}
  async function newSession(){carryDraft.current=false;if(!c.account){saveDraft(null,null,prompt);setDialog('login');return;}if(staged.length)needsFileReconfirm.current=true;saveDraft(c.account,state.session?.id,prompt);await act(async()=>{const created=await controller.create({model_id:model});if(newSettings.recipe_id&&JSON.stringify(newSettings)!==JSON.stringify(created.next_settings))await controller.patch({next_settings:newSettings});const id=controller.getState().session.id;saveMode(c.account,id,'auto');chooseMode('auto');setPrompt(readDraft(c.account,id));});setMobile(false);}
  async function stageFiles(files){if(uploading.current||state.busy){setLocalError('原材料操作仍在处理中，请稍后添加。');return;}const errors=[],add=[];for(const file of files){const kind=file.type.split('/')[0];if(!['image','video','audio'].includes(kind)){errors.push(`${file.name}：请选择图片、视频或音频。`);continue;}if(modeRef.current==='fl'&&kind!=='image'){errors.push(`${file.name}：首尾帧只使用图片，请先切换全能参考。`);continue;}if(!file.size){errors.push(`${file.name}：文件为空。`);continue;}const max=state.capabilities?.upload_constraints?.max_bytes;if(Number.isFinite(max)&&file.size>max){errors.push(`${file.name}：超过上传上限 ${(max/1024**2).toFixed(0)} MB。`);continue;}add.push({id:crypto.randomUUID(),file,kind,url:URL.createObjectURL(file),owner:c.account});}const queue=[...stagedRef.current,...add];stagedRef.current=queue;setStaged(queue);if(c.account&&add.length)await act(()=>uploadFiles(queue));if(errors.length)setLocalError(errors.join(' '));}
  async function saveSelection(proposed,{intent=modeRef.current,validate=true,confirmMode=true,nextSettings}={}){
    const original=controller.getState(),sid=original.session?.id;
    if(!sid)throw Error('请先保存到一条创作。');
    const currentSettings=nextSettings||draftSettings||original.session.next_settings||defaultsFor(original.capabilities),currentRecipe=recipeFor(original.capabilities,original.session.next_settings),mode=intent==='auto'?automaticMode(proposed):intent,next=settingsForMode(original.capabilities,currentSettings,mode),nextRecipe=recipeFor(original.capabilities,next);
    const problems=validate?bindingProblems(proposed,nextRecipe,next.controls):[];
    if(problems.length)throw Error(problems.join(' '));
    const excluded=proposed.filter(binding=>binding.enabled!==false&&!bindingParticipates(binding,nextRecipe));
    if(confirmMode&&currentRecipe?.mode!==mode&&excluded.length&&!await ask(`切换为${mode==='fl'?'首尾帧':'全能参考'}后，${excluded.length} 份不兼容素材会保留，但本轮不使用。素材和历史记录不会删除。`,{title:'切换生成方式？',label:'切换并保留素材'}))return false;
    await saveMaterialSelection(controller,{original,next,proposed});
    setDraftSettings(null);chooseMode(intent);return true;
  }
  async function updateMaterials(bindings){const live=controller.getState();return saveSelection(bindings.map(binding=>({...live.materials.find(item=>item.asset_id===binding.asset_id),...binding})));}
  async function roleChange(binding,patch){
    if(materialOperation.current||busy)throw Error('请等待原材料操作完成。');materialOperation.current=true;
    try{const live=controller.getState(),known=live.materials.find(item=>item.asset_id===binding.asset_id);if(!known||known.version!==binding.version)throw Error('这份材料已改变，请刷新后再选择用途。');const intent=['first_frame','last_frame'].includes(patch.slot)?'fl':['images','videos','audios'].includes(patch.slot)?'ref':modeRef.current,proposed=live.materials.map(item=>item.asset_id===binding.asset_id?{...item,...patch,enabled:true}:item);return await saveSelection(proposed,{intent});}finally{materialOperation.current=false;}
  }
  async function reuseMaterial(reference){return act(async()=>{
    const live=controller.getState();if(reference.session&&reference.session!==live.session?.id)throw Error('不同创作的素材保持独立，请在原创作使用。');
    const assetId=reference.asset_id||reference.asset,known=live.materials.find(item=>item.asset_id===assetId);if(!known||known.asset?.status!=='ready')throw Error('这份素材尚未在当前创作完成校验，请先核对原材料。');
    const slot=reference.slot||known.slot,patch={slot,purpose:reference.purpose||known.purpose,enabled:true,...(reference.source_range?{source_range:clone(reference.source_range)}:{}),...(Object.hasOwn(reference,'include_audio')?{include_audio:reference.include_audio}:{}),...(Object.hasOwn(reference,'time_seconds')?{time_seconds:reference.time_seconds}:{}),...(Object.hasOwn(reference,'use_audio')?{use_audio:reference.use_audio}:{})},candidate={...known,...patch};
    if(known.enabled!==false&&bindingParticipates(known,recipeFor(live.capabilities,live.session.next_settings))&&JSON.stringify(bindingPayload(candidate))===JSON.stringify(bindingPayload(known))){setNotice('这份素材已经在本轮输入里。');return;}
    const intent=['first_frame','last_frame'].includes(slot)?'fl':['images','videos','audios'].includes(slot)?'ref':modeRef.current;
    if(await saveSelection(live.materials.map(item=>item.asset_id===assetId?candidate:item),{intent})){hideAsset(assetId,false);setNotice('已重新使用原素材与片段，没有重新上传。');}
  });}
  async function uploadFiles(queue=[...stagedRef.current]){if(uploading.current)return;const session=await ensureSession();if(needsFileReconfirm.current&&!await ask(`将这些本地文件保存到 ${c.account} 的「${session.title}」？`,{title:'确认材料保存位置',label:'保存到这次创作'}))throw Error('未上传，文件保留本地。');needsFileReconfirm.current=false;const account=c.account,sid=session.id;uploading.current=true;setSubmitting(true);
    try{let needsClip=false;for(const item of queue){const live=controller.getState();if(live.account!==account||live.session?.id!==sid)throw Error('目标账户或创作已改变，停止上传；原结果请在原创作核对。');const uploaded=await controller.upload(item.file,item.id),asset={...uploaded,id:uploaded.id||uploaded.asset_id};URL.revokeObjectURL(item.url);stagedRef.current=stagedRef.current.filter(file=>file.id!==item.id);setStaged(stagedRef.current);if(asset.status!=='ready')throw Error('文件已接收但校验尚未完成。先刷新材料状态核对原收据，不重新上传。');const current=controller.getState(),currentSettings=draftSettings||current.session.next_settings,kind=asset.kind;let slot={image:'images',video:'videos',audio:'audios'}[kind];if(kind==='image'&&modeRef.current==='fl')slot=!current.materials.some(b=>b.enabled!==false&&b.slot==='first_frame')?'first_frame':!current.materials.some(b=>b.enabled!==false&&b.slot==='last_frame')?'last_frame':'images';const known=current.materials.find(b=>b.asset_id===asset.id),binding={...known,binding_id:known?.binding_id||'binding-'+crypto.randomUUID(),version:known?.version??0,asset_id:asset.id,asset,kind,slot,purpose:{images:'reference',videos:'motion',audios:'audio',first_frame:'firstFrame',last_frame:'lastFrame'}[slot],enabled:true,...(kind==='video'?{include_audio:effectiveLimits(recipeFor(current.capabilities,currentSettings)).allow_video_audio&&hasOriginalAudio(asset)}:{})},proposed=[...current.materials.filter(b=>b.asset_id!==asset.id),binding],mode=modeRef.current==='auto'?automaticMode(proposed):modeRef.current,next=settingsForMode(current.capabilities,currentSettings,mode),problems=bindingProblems(proposed,recipeFor(current.capabilities,next),next.controls);
      if(problems.length){needsClip=true;if(JSON.stringify(next)!==JSON.stringify(current.session.next_settings))await controller.patch({expected_version:current.session.version,next_settings:next});continue;}
      await saveSelection(proposed,{nextSettings:draftSettings||undefined});
    }setNotice(needsClip?'原素材已保存。请在素材上选择合法片段或用途，再用于本轮。':'素材已保存，输入会沿用到下一轮。');}finally{uploading.current=false;if(alive.current)setSubmitting(false);}}
  async function persistNextSettings(){const live=controller.getState(),base=draftSettings||live.session.next_settings,mode=modeRef.current==='auto'?automaticMode(live.materials):modeRef.current,next=settingsForMode(live.capabilities,base,mode);if(JSON.stringify(next)!==JSON.stringify(live.session.next_settings))await controller.patch({next_settings:next});setDraftSettings(null);return next;}
  async function send(mode='assist'){if(!prompt.trim()||busy)return;const text=prompt.trim();await act(async()=>{await ensureSession();if(stagedRef.current.length)await uploadFiles();await persistNextSettings();const target=controller.getState();await controller.turn(text,model,mode,{createCard:mode==='none'});if(textRef.current.trim()===text)changePrompt('',{account:target.account,id:target.session?.id});setDraftSettings(null);textarea.current?.focus();});}
  async function continueRevision(revision){await act(async()=>{const live=controller.getState(),next={deployment_profile_id:revision.deployment_profile_id??null,recipe_id:revision.recipe_id,controls:clone(revision.controls),copies:revision.copies},mode=recipeFor(live.capabilities,next)?.mode||'fl',original=bindingsForInputs(revision.inputs,live.materials),proposed=[...original,...live.materials.filter(binding=>!original.some(item=>item.asset_id===binding.asset_id)).map(binding=>({...binding,enabled:false}))];if(await saveSelection(proposed,{intent:mode,nextSettings:next,confirmMode:false})){changePrompt(`基于版本 ${revision.version}：${revision.prompt}\n本轮修改：`);setNotice(`已沿用版本 ${revision.version} 的原输入与参数，输出未自动加入参考。`);textarea.current?.focus();}});}
  async function useResult(artifact){await act(async()=>{const imported=await controller.importResult(artifact);if(imported.status!=='ready'){setNotice('结果导入已记录，等待校验；尚未作为生成输入。');return;}const asset=imported.asset||await controller.client.asset(imported.asset_id),live=controller.getState(),known=live.materials.find(b=>b.asset_id===imported.asset_id),binding={...known,binding_id:known?.binding_id||'binding-'+crypto.randomUUID(),version:known?.version??0,asset_id:imported.asset_id,asset,kind:asset.kind,slot:{video:'videos',audio:'audios',image:'images'}[asset.kind],purpose:asset.kind==='video'?'motion':asset.kind==='audio'?'audio':'reference',enabled:true,...(asset.kind==='video'?{include_audio:limits.allow_video_audio&&hasOriginalAudio(asset)}:{})},proposed=[...live.materials.filter(b=>b.asset_id!==imported.asset_id),binding],next=settingsForMode(live.capabilities,live.session.next_settings,'ref');if(bindingProblems(proposed,recipeFor(live.capabilities,next),next.controls).length){setNotice('真实结果已保存到素材库。请先选合法片段或调整用途，再加入本轮。');return;}if(await saveSelection(proposed,{intent:'ref'})){hideAsset(imported.asset_id,false);setNotice('真实结果已作为下一轮参考，原成片保留。');}});}
  const problems=bindingProblems(state.materials,recipe,settings.controls),counts=Object.fromEntries(['image','video','audio'].map(kind=>[kind,state.materials.filter(b=>b.kind===kind&&bindingParticipates(b,recipe)).length])),shownCards=new Set(turns.map(turn=>turn.card_id).filter(Boolean)),unlinked=allCards.filter(card=>!shownCards.has(card.id)),pending=state.pending;
  // Preflight's per-item media selections are technical derivatives, not new
  // user uploads. Keep the complete state for revision provenance/execution;
  // hide only unbound derivative receipts from the composer inventory view.
  const visibleMaterials=state.materials.filter(binding=>!hiddenAssetIds.includes(binding.asset_id)&&!isInternalDerivedInventory(binding)),excluded=state.materials.filter(binding=>binding.enabled!==false&&!bindingParticipates(binding,recipe));
  const cardSequence=new Map();
  for(const event of [...state.timeline].sort((a,b)=>a.seq-b.seq))if(event.type==='card.created'){const id=event.record?.card_id||event.card_id;if(id&&!cardSequence.has(id))cardSequence.set(id,event.seq);}
  const threadEntries=[...turns.map(turn=>({kind:'turn',record:turn,seq:turn.seq??Infinity})),...unlinked.map(card=>({kind:'card',record:card,seq:cardSequence.get(card.id)??Infinity}))].sort((a,b)=>a.seq-b.seq||((a.record.created_at||0)-(b.record.created_at||0)));
  const connectionLabel=!c.account?'● 本地待上传':!state.schema?'● 正在核对云连接':!assistantEnabled?'● 服务已连接 · 助手未启用':'● 服务已连接';
  const settingsSummary=recipe?(settings.controls?.duration??'?')+' 秒 · '+(settings.controls?.resolution||'待选清晰度')+' · '+(settings.copies||1)+'份':'登录后读取可用参数';
  const modeLabel=recipe?.mode==='fl'?'首尾帧':'全能参考';
  const materialLimits=recipe?.mode==='fl'?'首帧 '+state.materials.filter(b=>b.slot==='first_frame'&&bindingParticipates(b,recipe)).length+'/1 · 尾帧 '+state.materials.filter(b=>b.slot==='last_frame'&&bindingParticipates(b,recipe)).length+'/1 · 可不放素材':recipe?'图片 '+counts.image+'/'+(limits.max_images??'?')+' · 视频 '+counts.video+'/'+(limits.max_videos??'?')+' · 音频 '+counts.audio+'/'+(limits.max_audios??'?')+' · 合计 '+(counts.image+counts.video+counts.audio)+'/'+(limits.max_total_files??'?')+' ｜视频单段 '+displaySeconds(limits.min_clip_duration)+'–'+displaySeconds(limits.max_video_clip_duration)+' 秒，累计≤'+displaySeconds(limits.max_total_video_duration)+'秒；音频单段 '+displaySeconds(limits.min_clip_duration)+'–'+displaySeconds(limits.max_audio_clip_duration)+' 秒，累计≤'+displaySeconds(limits.max_total_audio_duration)+'秒':'';
  async function switchComposerMode(mode){await act(async()=>{const live=controller.getState();if(await saveSelection(live.materials,{intent:mode,validate:false}))setNotice('已切换'+(mode==='fl'?'首尾帧':'全能参考')+'；不兼容素材保留。');});}
  function dropIntoComposer(event){
    event.preventDefault();setDragging(false);const raw=event.dataTransfer.getData('application/x-yingxu-asset');
    if(raw){try{const reference=JSON.parse(raw);if(reference.session!==state.session?.id){setLocalError('不同创作的素材保持独立，请在原创作使用。');return;}reuseMaterial(reference);}catch{setLocalError('无法读取这份素材引用。');}}
    else stageFiles([...event.dataTransfer.files]);
  }
  const renderCard=card=><QuickChatCard key={card.id} card={card} state={state} controller={controller} onContinue={continueRevision} onUseResult={useResult} onUseMaterial={reuseMaterial}/>;
  return <div className="qc-shell">
    <a className="skip" href="#quick-chat-main">跳到聊天创作</a>
    <aside className={'qc-sidebar '+(mobile?'qc-sidebar-open':'')} aria-label="创作记录">
      <a className="qc-brand" href="/" title="返回短剧工作台">Ⅱ <b>映序</b><small>STUDIO</small></a>
      <button className="qc-new" disabled={busy} onClick={newSession}><Plus size={16}/>新建创作</button>
      <div className="qc-eyebrow">创作记录</div>
      <nav>{state.sessions.map(session=><button key={session.id} title={(session.title||'新的创作')+' · '+date(session.updated_at)} className={session.id===state.session?.id?'active':''} disabled={busy} onClick={()=>selectSession(session.id)}>{session.title||'新的创作'}</button>)}{state.sessionsCursor&&<button disabled={busy} onClick={()=>quietly(controller.list({more:true}))}>加载更早创作</button>}</nav>
      <OperatorEntry account={c.account} className="qc-operator-entry"/><button className="qc-agent-entry" onClick={()=>setDialog('agent')}><Bot size={15}/>API Key 与 Agent ↗</button>
      <button className="qc-account" onClick={()=>setDialog('login')}><span className="qc-avatar">{(c.account||'访').slice(0,1).toUpperCase()}</span><span><b>{c.account||'我的工作室'}</b><small>{c.account?'云端保存':'登录后云端保存'}</small></span></button>
    </aside>
    <main id="quick-chat-main" className="qc-main" ref={mainRef}>
      <header className="qc-header">
        <button className="qc-mobile-menu" aria-label="打开创作记录" onClick={()=>setMobile(!mobile)}><Menu size={19}/></button>
        <span>{state.session?.title||'新的创作'}{state.session?.version&&<button className="qc-rename" disabled={busy} aria-label="重命名创作" onClick={openRename}>改名</button>}</span>
        <div><button className="qc-connection-state" onClick={()=>setDialog('status')} aria-label="查看真实服务状态">{connectionLabel}</button>{c.account&&<button disabled={busy} onClick={()=>quietly(controller.refresh())} aria-label="刷新会话与真实任务"><RefreshCw size={15}/></button>}</div>
      </header>
      <div className="qc-thread">
        <section className="qc-welcome" hidden={threadEntries.length>0}><span className="qc-eyebrow">FROM AN IDEA TO A SCENE</span><h1>你的想法，从这里成片。</h1><p>放入参考，告诉我你想拍什么。我们一起把画面想清楚。</p><div className="qc-star" aria-hidden="true">✳</div></section>
        {state.historyCursor&&<button disabled={busy} onClick={()=>quietly(controller.history())}>加载更早消息</button>}
        {threadEntries.map(entry=>entry.kind==='card'?renderCard(entry.record):(()=>{const turn=entry.record;return <article className="qc-turn" key={turn.id}>
          <div className="qc-user-message">{turn.text}</div>
          {turn.assistant_mode!=='none'&&<div className="qc-turn-label">✧ {CHAT_MODELS.find(item=>item.id===turn.model_id)?.label||turn.model_id} · {date(turn.created_at)}{turn.assistant_mode==='discuss'?' · 仅讨论':''}</div>}
          {turn.reply?<div className="qc-assistant-text">{turn.reply}</div>:!turn.card_id&&<p className="qc-muted">{({pending:'这一轮已保存，等待助手处理。',running:'助手正在处理原请求…',failed:'助手未完成本轮；原输入已保存，未切换模型。',unknown:'助手调用结果未知，可能已消费额度；不会自动重发。',recorded:'这一轮文字已保存。',completed:'这一轮文字已保存。'})[turn.status]||'这一轮记录已保存。'}{turn.error_code&&'（'+turn.error_code+'）'}</p>}
          {turn.assistant_run?.media_input_manifest?.length>0&&<details><summary>助手实际读取的素材</summary>{turn.assistant_run.media_input_manifest.map((item,index)=><p className="qc-muted" key={index}>{state.materials.find(b=>b.asset_id===item.asset_id)?.asset?.file_name||item.asset_id} · {item.sent?'已确认上游响应':item.included_in_payload?'已装入请求 · 接收结果待核对':'未装入本次请求'}{item.reason?' · '+item.reason:''}</p>)}</details>}
          {(turn.input_exclusions||turn.assistant_run?.input_exclusions)?.length>0&&<details><summary>本轮未参与的材料</summary>{(turn.input_exclusions||turn.assistant_run.input_exclusions).map((item,index)=><p className="qc-muted" key={index}>{state.materials.find(b=>b.asset_id===item.asset_id)?.asset?.file_name||item.asset_id} · {item.reason==='mode_incompatible'?'与本轮生成方式不兼容':'本轮未选择'}</p>)}</details>}
          {turn.status==='unknown'&&!turn.assistant_run?.acknowledged_at&&<button disabled={busy} onClick={()=>act(async()=>{if(await ask('承认这次助手调用结果未知？不会重发原请求，可能已消费的额度仍需核对。',{title:'核对未知结果',label:'承认未知并继续'}))await controller.acknowledge(turn);})}>承认未知后开始新讨论</button>}
          {turn.card_id&&state.cards[turn.card_id]&&renderCard(state.cards[turn.card_id])}
        </article>;})())}
        {pending&&!busy&&<section className="qc-warning" role="alert"><b>有原操作结果待核对</b><p>不自动重投。先打开原创作并用同一操作标识核对。</p>{pending.sessionId&&pending.sessionId!==state.session?.id&&<button disabled={busy} onClick={()=>selectSession(pending.sessionId)}>打开原创作</button>}<button disabled={busy||pending.corrupt||pending.sessionId&&pending.sessionId!==state.session?.id} onClick={()=>quietly(controller.recover())}>核对并恢复原操作</button></section>}
        {Object.values(state.imports).filter(item=>item.status!=='ready').map(item=><p className="qc-warning" key={item.id}>结果导入 {item.id} · {item.status}；原收据保持，未作为输入。</p>)}
      </div>
      <div className="qc-composer-wrap" ref={composerRef}>
        {turns.length>0&&<div className="qc-inherit">素材和设置沿用上一轮 · × 只移除本轮引用，不删除历史素材</div>}
        <div className={'qc-composer '+(dragging?'qc-dragging':'')} onDragOver={event=>{event.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={dropIntoComposer}>
          <div className="qc-input-head"><button disabled={busy} onClick={()=>input.current.click()}><Plus size={14}/>{uploading.current?'正在保存素材…':'添加图片、视频或音频'}</button><span>也可以拖到这里</span><input type="file" ref={input} accept={modeIntent==='fl'?'image/*':'image/*,video/*,audio/*'} multiple hidden onChange={event=>{stageFiles([...event.target.files]);event.target.value='';}}/></div>
          {visibleMaterials.length>0&&<QuickChatMaterials bindings={visibleMaterials} recipe={recipe} client={controller.client} busy={busy} onChange={updateMaterials} onRoleChange={roleChange} onRemove={removeMaterial} onResume={id=>controller.resumeMaterial(id)} compact/>}
          {staged.length>0&&<div className="qc-staged">{staged.map(item=>{const Icon={image:Image,video:Video,audio:Music}[item.kind];return <div className="qc-staged-file" key={item.id}>{item.kind==='image'?<img src={item.url} alt={item.file.name}/>:<Icon size={22}/>}<div><b>{item.file.name}</b><small>{uploading.current?'原文件正在保存…':'本地待上传'}</small></div><button disabled={busy} aria-label={'移除待上传 '+item.file.name} onClick={()=>{URL.revokeObjectURL(item.url);stagedRef.current=stagedRef.current.filter(file=>file.id!==item.id);setStaged(stagedRef.current);}}><X size={14}/></button></div>;})}{!uploading.current&&<button disabled={busy} onClick={()=>act(()=>uploadFiles())}><Upload size={14}/>{c.account?'保存到这次创作':'登录并保存材料'}</button>}</div>}
          {recipe&&(visibleMaterials.length>0||modeIntent!=='auto')&&<div className="qc-mode-note"><span>{modeLabel}模式 · {recipe.mode==='fl'?'普通参考不参与本轮；时间锚点可单独指定。':'使用参考图片、视频、音频，首帧/尾帧不参与本轮。'}</span>{excluded.length>0&&<button disabled={busy} onClick={()=>switchComposerMode(recipe.mode==='fl'?'ref':'fl')}>切换{recipe.mode==='fl'?'全能参考':'首尾帧'}</button>}</div>}
          {materialLimits&&<div className="qc-limits-summary">{materialLimits}</div>}
          {problems.length>0&&visibleMaterials.length>0&&<p className="qc-input-errors" role="alert">{problems.join(' ')}形成生成卡前请调整。</p>}
          {(localError||state.error)&&<p className="qc-input-errors" role="alert">{localError||state.error}</p>}
          <textarea ref={textarea} className="qc-prompt" rows={2} maxLength={12000} aria-label="创作想法" placeholder="描述你想要的画面，也可以继续说「镜头近一点，其他不变」…" value={prompt} onChange={event=>changePrompt(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();send(assistantEnabled?assistantMode:'none');}}}/>
          <DeploymentProfileSelect capabilities={state.capabilities} value={settings.deployment_profile_id} mode={recipe?.mode} disabled={busy||!!pending} onChange={value=>setDraftSettings({...settings,deployment_profile_id:value})}/><div className="qc-composer-bottom">
            <label className="qc-model-label"><span>✧</span><select aria-label="聊天模型" value={model} disabled={busy} onChange={event=>{setModel(event.target.value);if(state.session)quietly(controller.patch({model_id:event.target.value}));}}>{CHAT_MODELS.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label>
            <button className="qc-controls" disabled={busy||!recipe} onClick={openControls}><Settings2 size={14}/>高级控制</button>
            <span className="qc-settings-summary">{settingsSummary}</span>
            <button className="qc-primary qc-send" disabled={busy||!prompt.trim()||!!pending} onClick={()=>send(assistantEnabled?assistantMode:'none')}>{busy?'保存中…':'发送'}<ArrowUp size={15}/></button>
          </div>
        </div>
        <div className="qc-footnote">点「开始生成」才提交视频；助手与执行状态可在右上角查看。</div>
      </div>
    </main>
    {toast&&<div className="qc-toast" role="status"><span>{toast}</span><button aria-label="关闭提示" onClick={()=>setToast('')}><X size={12}/></button></div>}
    {dialog==='status'&&<ChatDialog title="真实服务状态" onClose={()=>setDialog(null)}>
      <p>{c.account?'当前账户：'+c.account+' · '+(state.schema?'已连接工作室':'连接状态待核对'):'还未登录。文字和待上传文件保留在本地；登录后可云端保存。'}</p>
      <p>{assistantEnabled?'所选助手调用已启用；上游是否理解媒体，以每轮真实读取清单为准。':'助手尚未启用。发送会将当前文字、素材和参数直接保存为可编辑任务卡，不会调用聊天模型或自动生成视频。'}</p>
      {modelSchema&&['image','video','audio'].some(kind=>modelSchema.inputs?.[kind]?.implemented===false)&&<p className="qc-muted">这个聊天模型尚未接入{['image','video','audio'].filter(kind=>modelSchema.inputs?.[kind]?.implemented===false).map(kind=>({image:'图片',video:'视频',audio:'音频'})[kind]).join('、')}理解。这些素材仍可供 H3 参考；上传不等于助手已读过。</p>}
      <p>{state.capabilities?.execution_enabled?'视频提交开关已开启；实时预检决定当前能否执行。':'视频生成尚未启用。可保存素材、文字和任务卡并预检，不会租用 GPU。'}</p>
      {assistantEnabled&&<label className="qc-field">助手回复方式<select value={assistantMode} onChange={event=>setAssistantMode(event.target.value)}><option value="assist">创作助手 · 可整理草稿卡</option><option value="discuss">只讨论 · 不出卡</option></select></label>}
      <p className="qc-muted">任务卡的开始生成会检查输入与执行条件，通过后再确认提交。打开网页、上传素材、讨论和保存卡片不启动 GPU。</p>
    </ChatDialog>}
    {dialog==='rename'&&<ChatDialog title="给这次创作起个名字" onClose={()=>setDialog(null)}><form onSubmit={event=>{event.preventDefault();saveRename();}}><label className="qc-field">创作名称<input aria-label="创作名称" value={rename} maxLength={160} required onChange={event=>setRename(event.target.value)}/></label>{renameError&&<p className="qc-error" role="alert">{renameError}</p>}<button className="qc-primary" disabled={busy||!rename.trim()}>保存名称</button></form></ChatDialog>}
    {dialog==='login'&&<Login onClose={()=>setDialog(null)} onDone={()=>setDialog(null)}/>}
    {dialog==='controls'&&controlsSnapshot.current&&<QuickChatControls capabilities={controlsSnapshot.current.capabilities} settings={controlsSnapshot.current.settings} bindings={controlsSnapshot.current.bindings} modeIntent={controlsSnapshot.current.modeIntent} onClose={()=>setDialog(null)} busy={busy} onSave={saveNextControls}/>}
    {dialog==='agent'&&<QuickChatAgent account={c.account} sessionId={state.session?.id} onClose={()=>setDialog(null)} onLogin={()=>setDialog('login')}/>}
    {confirmation&&<ChatDialog title={confirmation.title} onClose={()=>finishConfirmation(false)}><p>{confirmation.message}</p><div className="qc-dialog-footer"><button onClick={()=>finishConfirmation(false)}>先不改变</button><button className="qc-primary" onClick={()=>finishConfirmation(true)}>{confirmation.label}</button></div></ChatDialog>}
  </div>;
}
