import React,{useState} from 'react';
import {store} from './store.js';
import {storyboardPrompt,promptDraftPatch,restorePromptPatch} from './shot-prompt.js';

export default function ShotPromptDraft({project,shot}){
  const [options,setOptions]=useState({includeScene:false,includeCharacters:true,includeLocations:true}),[preview,setPreview]=useState(null),[error,setError]=useState('');
  const source=storyboardPrompt(project,shot.id,options),current=String(shot.data.prompt??shot.description??''),previous=shot.data.promptDraftPrevious;
  const stale=preview&&(preview.source!==source||preview.expected!==current);
  const toggle=(key,value)=>{setOptions(o=>({...o,[key]:value}));setError('');};
  const apply=()=>{try{const live=store.getState();if(live.project.id!==project.id)throw Error('项目已切换，请重新打开镜头。');const latest=live.project.entities.find(e=>e.id===shot.id);if(stale)throw Error('分镜或提示词已改变，请重新预览。');if(store.updateEntity(shot.id,{data:promptDraftPatch(latest,preview.text,preview.expected)})){setPreview(null);setError('');}}catch(e){setError(e.message);}};
  return <details className="shot-prompt-draft"><summary>从分镜整理提示词 · 可预览后采用</summary><p>把已写的画面、拍法、人物和场景整理成草稿，不调用 AI，不替你增加剧情。只有点击采用才替换上方提示词；参考图仍需在输入中关联。</p><div className="shot-prompt-options">{[['includeCharacters','关联人物与当前造型'],['includeLocations','关联地点描述'],['includeScene','本场动作与台词（可能包含其他镜头）']].map(([key,label])=><label key={key}><input type="checkbox" checked={options[key]} onChange={e=>toggle(key,e.target.checked)}/>{label}</label>)}</div><button type="button" disabled={!source.trim()} onClick={()=>{setPreview({source,expected:current,text:source});setError('');}}>预览整理结果</button>{!source.trim()&&<p>先在镜头的“画面与动作”中写下内容，或补充拍法与已关联设定。快速创作也可直接写上方完整提示词。</p>}{preview&&<div className="shot-prompt-preview"><label className="cloud-control"><span>待采用的提示词草稿</span><textarea rows={7} value={preview.text} maxLength={24000} onChange={e=>setPreview(p=>({...p,text:e.target.value}))}/></label><p>请删去不属于本镜头的动作；长度 {preview.text.length} / 12000。原提示词会保留。</p>{stale&&<p className="cloud-warning">来源或原提示词已改变，请重新点“预览整理结果”。</p>}<div className="cloud-actions"><button type="button" disabled={stale||!preview.text.trim()||preview.text.length>12000} onClick={apply}>采用草稿，保留原提示词</button><button type="button" onClick={()=>setPreview(null)}>取消预览</button></div></div>}{previous&&<details><summary>查看上一次采用前的提示词</summary><pre>{previous.text||'（原提示词为空）'}</pre><button type="button" disabled={current!==previous.applied} onClick={()=>{try{store.updateEntity(shot.id,{data:restorePromptPatch(shot)});setError('');}catch(e){setError(e.message);}}}>恢复原提示词</button>{current!==previous.applied&&<p>采用后又有修改，不能直接恢复。可复制上面的原文，或使用项目撤销。</p>}</details>}{error&&<p className="cloud-error" role="alert">{error}</p>}</details>;
}
