import React,{useState} from 'react';
import {store} from './store.js';
import {captionTrack,captionStatus,captionSignature,captionIssues,orderedCues,srtTime} from './caption-model.js';
import './handover.css';

function CueForm({cue,cues,duration,onSave,onCancel}){
  const [text,setText]=useState(cue?.text||''),[start,setStart]=useState(String(cue?.start??0)),[end,setEnd]=useState(String(cue?.end??Math.min(2,duration))),[error,setError]=useState('');
  return <form className="caption-form" onSubmit={event=>{event.preventDefault();if(start===''||end===''){setError('请填写起止秒数。');return;}const next={id:cue?.id||'caption-'+crypto.randomUUID(),start:Number(start),end:Number(end),text:text.trim()},issues=captionIssues([...cues.filter(c=>c.id!==next.id),next],duration);if(issues.length){setError(issues.join(' '));return;}onSave(next);}}><label>字幕正文<textarea aria-label="字幕正文" maxLength={2000} rows={3} value={text} onChange={e=>setText(e.target.value)} placeholder="手动输入这句话；双语可各写一行。"/></label><div className="caption-times"><label>章节开始秒数<input aria-label="字幕开始秒数" type="number" min="0" step="0.001" value={start} onChange={e=>setStart(e.target.value)}/></label><label>章节结束秒数<input aria-label="字幕结束秒数" type="number" min="0" max={duration} step="0.001" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><p>从本章0秒起计算；请对照画面/音频手动校时。按编辑计划秒数填写；粗剪会对齐24fps，请对照最终成片复核。不会识别对白或自动对齐。</p>{error&&<p role="alert" className="cloud-error">{error}</p>}<div className="cloud-actions"><button type="submit">保存这条字幕</button><button type="button" onClick={onCancel}>取消</button></div></form>;
}
export default function SubtitleStudio({project,chapterId}){
  const [editing,setEditing]=useState(null),[adding,setAdding]=useState(false),status=captionStatus(project,chapterId),track=captionTrack(project,chapterId),cues=orderedCues(track.cues);
  const patch=update=>store.editProject(p=>{p.journey={...p.journey,captionTracks:{...p.journey?.captionTracks,[chapterId]:{...captionTrack(p,chapterId),...update}}};});
  return <section className="subtitle-studio" aria-label="章节手动字幕"><h3>手动字幕 · SRT 与可选成片烧录</h3><p>只保存你输入的字幕文字和时间。不会把「对白要求」当成对白稿，也不会自动听写、翻译或校时。确认后可导出独立SRT，或在交付检查中明确选择烧进本次成片；以服务能力为准。</p>{!chapterId?<p>先选择一个章节。</p>:<><p>本章 {Number(status.duration.toFixed(3))} 秒 · {cues.length} 条字幕。改镜头顺序、时长、采用素材、剪辑选段或音轨后需重新确认。</p>{cues.map((cue,index)=><article key={cue.id} className="caption-row"><div><b>{index+1}. {Number.isFinite(cue.start)&&cue.start>=0&&Number.isFinite(cue.end)&&cue.end>=0&&cue.start<360000&&cue.end<360000?`${srtTime(cue.start)} → ${srtTime(cue.end)}`:'时间待修正'}</b><p>{cue.text}</p></div><div className="cloud-actions"><button onClick={()=>{setEditing(cue);setAdding(false);}}>编辑字幕 {index+1}</button><button onClick={()=>{patch({cues:cues.filter(c=>c.id!==cue.id)});setEditing(null);store.notify('字幕已移除，可用顶部撤销恢复。');}}>移除字幕 {index+1}</button></div></article>)}{editing||adding?<CueForm key={editing?.id||'new'} cue={editing} cues={cues} duration={status.duration} onCancel={()=>{setEditing(null);setAdding(false);}} onSave={cue=>{if(patch({cues:[...cues.filter(c=>c.id!==cue.id),cue]})){setEditing(null);setAdding(false);}}}/>:<button disabled={!status.duration||cues.length>=500} onClick={()=>setAdding(true)}>添加一条手动字幕</button>}{cues.length>0&&<><div aria-live="polite">{status.issues.map((issue,index)=><p className="cloud-error" key={index}>{issue}</p>)}{status.previouslyConfirmed&&!status.confirmed&&<p className="cloud-warning">字幕或时间线有变化，原稿保留，请重新核对。</p>}<label className="caption-confirm"><input type="checkbox" disabled={!!status.issues.length||!!editing||adding} checked={status.confirmed} onChange={e=>patch({confirmedSnapshot:e.target.checked?captionSignature(project,chapterId):null,confirmedAt:e.target.checked?new Date().toISOString():null})}/>我已核对这一版字幕的文字与起止时间</label><p>{status.confirmed?'已人工确认，可到交付检查导出本章SRT，或选择符合版式要求的成片烧录。':'尚未确认，不会导出为已校时字幕。'}这不代表系统验证了对白同步。</p></div></>}</>}
  </section>;
}
